# Generated by Django 3.1 on 2020-08-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antstream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antstreammodel",
            name="notification_send_timeout",
            field=models.PositiveSmallIntegerField(default=1, help_text="seconds until timeout"),
        ),
        migrations.AddField(
            model_name="antstreammodel",
            name="notification_url",
            field=models.URLField(default=""),
        ),
    ]
