operator:
  replicaCount: 2

keycloak:
  instances: 2

postgresOperator:
  dbName: keycloak
  dbHost: phoenix-cluster.postgres-operator.svc.cluster.local
  dbOwnerSecretName: keycloak-owner-user.phoenix-cluster.credentials.postgresql

realm:
  name: phoenix

client:
  realm: phoenix
  name: phoenix-backend
