play {
  application.loader = net.flipsports.gmx.widget.argyll.betandwatch.events.Loader

  http {
    context = "/"
    secret {
      key = "changeme"
      key = ${?APPLICATION_SECRET}
    }
  }

  server.pidfile.path = /dev/null
}

app {
  business-rules {
    min-stake = 1.0
    //TODO disabled until we load bets from kafka https://flipsports.atlassian.net/browse/GM-1228
    verify-bets = false
  }
  load-events {
    sbtech-cache {
      interval = 10m
      days-before = 1
      days-ahead = 1
    }
    atr-cache {
      enabled = true
      enabled = ${?ATR_ENABLED}
      interval = 10s
      days-before = 1
      days-ahead = 1
    }
    rmg-cache {
      enabled = true
      enabled = ${?RMG_ENABLED}
      interval = 10m
    }
    sis-cache {
      enabled = true
      enabled = ${?SIS_ENABLED}
      interval = 10m
    }
    mapping {
      interval = 5s
      days-before = 0
      days-ahead = 1
      include-test-data = true
    }
    check {
      interval = 10m
    }
  }
  user-bets {
    sbtech-cache {
      enabled = true
      enabled = ${?BETS_ENABLED}
      interval = 20h
      days-before = 3
      segment-size = 3h
      segment-overlap = 1h
    }
    mapping {
      interval = 5s
    }
  }

  encrypt {
    user {
      seed = ${ENCRYPT_USER_SEED}
    }
  }
  external {
    atr {
      sms-api {
        url = "https://"${app.external.atr.sms-api.operator}".attheraces.com/ps/api"
        operator = ${SMS_API_OPERATOR}
        partner = ${SMS_API_PARTNER}
        password = ${SMS_API_PASSWORD}
        seed = ${SMS_API_SEED}
      }
    }
    rmg {
      csb-desktop {
        url = "https://secure."${app.external.rmg.csb-desktop.partner}".performgroup.com"
        partner = ${CSB_API_DESKTOP_PARTNER}
        partner-id = ${CSB_API_DESKTOP_PARTNER_ID}
        seed = ${CSB_API_DESKTOP_SEED}
      }
      csb-mobile {
        url = "https://secure.mobile."${app.external.rmg.csb-mobile.partner}".performgroup.com"
        partner = ${CSB_API_MOBILE_PARTNER}
        partner-id = ${CSB_API_MOBILE_PARTNER_ID}
        seed = ${CSB_API_MOBILE_SEED}
      }
    }
    sis {
      stream-api {
        url = "https://streamingapi.sis.tv/StreamingService/api/v2"
        customer = ${SIS_API_CUSTOMER}
        seed = ${SIS_API_SEED}
      }
    }
    sbtech {
      odds-api {
        url = "https://oddsfeed-"${app.external.sbtech.odds-api.operator}".sbtech.com"
        operator = ${ODDS_API_OPERATOR}
      }
      data-api {
        url = "https://dataapi.sbtech.com/dataAPI"
        agent = ${DATA_API_AGENT}
        password = ${DATA_API_PASSWORD}
      }
    }
  }
}
