version = "2.5.0"

style = defaultWithAlign

align                                         = more
align.openParenCallSite                       = true
align.openParenDefnSite                       = true
continuationIndent.extendSite                 = 2
continuationIndent.withSiteRelativeToExtends  = 4
rewrite.rules                                 = [AvoidInfix,RedundantBraces,RedundantParens,SortImports]
docstrings                                    = JavaDoc
maxColumn                                     = 120
unindentTopLevelOperators                     = true
rewrite.neverInfix.excludeFilters             = [
  and
  min
  max
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
]
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}
spaces.inImportCurlyBraces     = true
spaces.beforeContextBoundColon = IfMultipleBounds

