cloudflow {

  topics {

    deposit-limit-increases = ${unmanaged-kafka} {
      topic.name = "customer-deposit-limits"
      consumers = [deposit-limit-increase-alert-generator.in]
    }

    timeouts-set = ${unmanaged-kafka} {
      topic.name = "customer-timeouts"
      consumers = [timeout-frequency-alert-generator.in]
    }

    sports-bets-placed = ${unmanaged-kafka} {
      topic.name = "customer-sports-bets"
      consumers = [play-session-duration-alert-generator.sports-bets, sports-bet-liability-alert-generator.sports-bets, daily-avg-bet-liability-calculator.in]
    }

    casino-bets-placed = ${unmanaged-kafka} {
      topic.name = "customer-casino-bets"
      consumers = [play-session-duration-alert-generator.casino-bets]
    }

    customer-logouts = ${unmanaged-kafka} {
      topic.name = "customer-logouts"
      consumers = [play-session-duration-alert-generator.logouts]
    }
  }
}

unmanaged-kafka {
  managed = no
  producer-config = ${kafka-connection-config} {
    # more config can be added here from Kafka ProducerConfig (see org.apache.kafka.clients.producer.ProducerConfig)
  }
  consumer-config = ${kafka-connection-config} {
    # more config can be added here from Kafka ConsumerConfig (see org.apache.kafka.clients.consumer.ConsumerConfig)
  }
}

kafka-connection-config {
  bootstrap.servers = "_tcp-clients._tcp.cloudflow-kafka-brokers.cloudflow:9092"
}