cloudflow {

  streamlets {

    deposit-limit-increase-alert-generator {}

    timeout-frequency-alert-generator {}

    play-session-duration-alert-generator {}

    sports-bet-liability-alert-generator {}

    trunarrative-alert-handler {
      config-parameters {
        url = "http://localhost:9000/trunarrative"
        account-id = "changeme"
      }
    }

    daily-avg-bet-liability-calculator {}
  }
}