# Generated by Django 3.1 on 2020-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0006_auto_20200818_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oidcclientextra",
            name="default_permissions_set",
            field=models.ManyToManyField(
                blank=True, related_name="oidc_extra_default_permission_set", to="oidc.OidcPermissions"
            ),
        ),
        migrations.AlterField(
            model_name="oidcclientextra",
            name="limited_permissions_set",
            field=models.ManyToManyField(
                blank=True, related_name="oidc_extra_limited_permission_set", to="oidc.OidcPermissions"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialsecret",
            unique_together={("oidc_client_extra", "social_type")},
        ),
    ]
