# Generated by Django 3.1 on 2020-08-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0007_auto_20200821_1341"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="socialsecret",
            unique_together=set(),
        ),
    ]
