# Generated by Django 3.1 on 2020-08-28 19:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_auto_20200818_1804"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oidc", "0008_auto_20200825_0835"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUserMappingModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("external_user_id", models.CharField(max_length=150, unique=True)),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_external_mapping",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "originator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="originator_external_mapping",
                        to="profiles.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
