apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cp-kafka-rest
    qcloud-app: cp-kafka-rest
  name: cp-kafka-rest
  namespace: streaming
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: cp-kafka-rest
      qcloud-app: cp-kafka-rest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cp-kafka-rest
        qcloud-app: cp-kafka-rest
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: nodes-type
                operator: In
                values:
                - streaming-nodes
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodes-type
                operator: In
                values:
                - streaming-nodes
      containers:
      - env:
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_CLUSTER_HOST_PORT
              name: common
              optional: false
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              key: SCHEMA_REGISTRY_HOST_PORT
              name: common
              optional: false
        envFrom:
        - configMapRef:
            name: cp-kafka-rest
        image: confluentinc/cp-kafka-rest:7.0.0
        imagePullPolicy: Always
        name: cp-kafka-rest
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
