apiVersion: v1
kind: Service
metadata:
  name: cp-kafka-rest
  namespace: streaming
spec:
  clusterIP: 172.17.254.68
  ports:
  - name: 8082-8082-tcp
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    k8s-app: cp-kafka-rest
    qcloud-app: cp-kafka-rest
  sessionAffinity: None
  type: ClusterIP
