version: '3'

services:
  gstech-paymentserver.test:
    build:
      context: ../../
      dockerfile: packages/gstech-paymentserver/Dockerfile
    image: gstech-paymentserver.test
    container_name: gstech-paymentserver.test
    command: yarn test
    networks:
      - gstech
    environment:
      CI: "true"
      NODE_ENV: test
      RUNNER_DEBUG: ${RUNNER_DEBUG}
      NODE_NO_WARNINGS: ${NODE_NO_WARNINGS}
      BACKEND_URL: http://gstech-backend:3001
      PUBLIC_URL: http://localhost:3006
      LOGGER_FORMAT: nice

networks:
  gstech:
    external: true
