stella {
  achievement {
    # eventually we'll need some proper, secure way of storing this
    secret-box-hex-key = ea87def016584b3c84e5cdbea4dcc868ea87def016584b3c84e5cdbea4dcc868
    secret-box-hex-key = ${?ACHIEVEMENT_SECRET_BOX_HEX_KEY}

    test-user-id = "b080f663-ed46-4b58-8c85-810cef8358ea"
    test-user-id = ${?ACHIEVEMENT_TEST_USER_ID}

    test-project-id = "2353130a-e2b3-47e9-a2cb-3ade99f81b03"
    test-project-id = ${?ACHIEVEMENT_TEST_PROJECT_ID}

    cache {
      windows-timeout = 10 seconds
      windows-timeout = ${?ACHIEVEMENT_WINDOWS_CACHE_TIMEOUT}
      achievement-events-timeout = 10 seconds
      achievement-events-timeout = ${?ACHIEVEMENT_ACHIEVEMENT_EVENTS_CACHE_TIMEOUT}
    }

    jwt {
      require-jwt-auth = true
      require-jwt-auth = ${?ACHIEVEMENT_REQUIRE_JWT_AUTH}
      service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
      service-discovery-endpoint-uri = ${?JWT_SERVICE_DISCOVERY_URI}
      internal-service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
      internal-service-discovery-endpoint-uri = ${?JWT_INTERNAL_SERVICE_DISCOVERY_URI}
      issuer-cache-refresh-frequency = 1 hour
      issuer-cache-refresh-frequency = ${?ACHIEVEMENT_ISSUER_CACHE_REFRESH_FREQUENCY}
      jwks-cache-refresh-frequency = 10 minutes
      jwks-cache-refresh-frequency = ${?ACHIEVEMENT_JWKS_CACHE_REFRESH_FREQUENCY}
    }

    open-api {
      server-url = "http://localhost:12000"
      server-url = ${?ACHIEVEMENT_OPEN_API_SERVER_URL}
    }
  }
}
