slick {
  dbs {
    default {
      profile="slick.jdbc.PostgresProfile$"
      db {
        driver="org.postgresql.Driver"
        host="localhost"
        host=${?ACHIEVEMENT_DB_ADDRESS}
        port=5432
        port=${?ACHIEVEMENT_DB_PORT}
        name="achievement"
        name=${?ACHIEVEMENT_DB_NAME}
        url="jdbc:postgresql://"${slick.dbs.default.db.host}":"${slick.dbs.default.db.port}"/"${slick.dbs.default.db.name}
        username="achievement"
        username=${?ACHIEVEMENT_DB_USERNAME}
        password="achievement"
        password=${?ACHIEVEMENT_DB_PASSWORD}
      }
    }
  }
}
