// flow-typed signature: 6b421559e8e56be0e0ce7bb4b6746cc4
// flow-typed version: <<STUB>>/@sendgrid/mail_v^7.4.5/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sendgrid/mail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sendgrid/mail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sendgrid/mail/src/classes/mail-service' {
  declare module.exports: any;
}

declare module '@sendgrid/mail/src/mail' {
  declare module.exports: any;
}

declare module '@sendgrid/mail/src/mail.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sendgrid/mail/index' {
  declare module.exports: $Exports<'@sendgrid/mail'>;
}
declare module '@sendgrid/mail/index.js' {
  declare module.exports: $Exports<'@sendgrid/mail'>;
}
declare module '@sendgrid/mail/src/classes/mail-service.js' {
  declare module.exports: $Exports<'@sendgrid/mail/src/classes/mail-service'>;
}
declare module '@sendgrid/mail/src/mail.js' {
  declare module.exports: $Exports<'@sendgrid/mail/src/mail'>;
}
declare module '@sendgrid/mail/src/mail.spec.js' {
  declare module.exports: $Exports<'@sendgrid/mail/src/mail.spec'>;
}
