// flow-typed signature: 83a0cae50e1cd2d26c849ac6252ce814
// flow-typed version: <<STUB>>/accept-language-parser_v^1.5.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'accept-language-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'accept-language-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'accept-language-parser/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'accept-language-parser/index' {
  declare module.exports: $Exports<'accept-language-parser'>;
}
declare module 'accept-language-parser/index.js' {
  declare module.exports: $Exports<'accept-language-parser'>;
}
declare module 'accept-language-parser/tests/tests.js' {
  declare module.exports: $Exports<'accept-language-parser/tests/tests'>;
}
