// flow-typed signature: 1ac5f5ae47de02985f32f675ef43b929
// flow-typed version: <<STUB>>/aes256_v^1.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aes256'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aes256' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'aes256/index' {
  declare module.exports: $Exports<'aes256'>;
}
declare module 'aes256/index.js' {
  declare module.exports: $Exports<'aes256'>;
}
