// flow-typed signature: bc0cd5e8aaaf683a00f8e4079c5256d3
// flow-typed version: <<STUB>>/async-q_v^0.3.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-q'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-q' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'async-q/index' {
  declare module.exports: $Exports<'async-q'>;
}
declare module 'async-q/index.js' {
  declare module.exports: $Exports<'async-q'>;
}
