// flow-typed signature: f7aab22dd1bd62d864b9864ecab4855e
// flow-typed version: <<STUB>>/autoprefixer-stylus_v^1.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autoprefixer-stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autoprefixer-stylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'autoprefixer-stylus/index' {
  declare module.exports: $Exports<'autoprefixer-stylus'>;
}
declare module 'autoprefixer-stylus/index.js' {
  declare module.exports: $Exports<'autoprefixer-stylus'>;
}
