// flow-typed signature: d7099ce93f58c70eea139d3da427e006
// flow-typed version: <<STUB>>/axios-debug-log_v^1.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-debug-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-debug-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-debug-log/enable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-debug-log/enable.js' {
  declare module.exports: $Exports<'axios-debug-log/enable'>;
}
declare module 'axios-debug-log/index' {
  declare module.exports: $Exports<'axios-debug-log'>;
}
declare module 'axios-debug-log/index.js' {
  declare module.exports: $Exports<'axios-debug-log'>;
}
