// flow-typed signature: dca4defe41d9af9d3a2ad1192b7b91b5
// flow-typed version: <<STUB>>/axios-cookiejar-support_v^4.0.6/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-cookiejar-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-cookiejar-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-cookiejar-support/dist' {
  declare module.exports: any;
}

declare module 'axios-cookiejar-support/noop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-cookiejar-support/dist/index' {
  declare module.exports: $Exports<'axios-cookiejar-support/dist'>;
}
declare module 'axios-cookiejar-support/dist/index.js' {
  declare module.exports: $Exports<'axios-cookiejar-support/dist'>;
}
declare module 'axios-cookiejar-support/noop.js' {
  declare module.exports: $Exports<'axios-cookiejar-support/noop'>;
}
