// flow-typed signature: 741dffb258ec5fb12619639be25a46d4
// flow-typed version: <<STUB>>/body-parser-xml_v^2.0.3/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'body-parser-xml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'body-parser-xml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'body-parser-xml/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'body-parser-xml/index' {
  declare module.exports: $Exports<'body-parser-xml'>;
}
declare module 'body-parser-xml/index.js' {
  declare module.exports: $Exports<'body-parser-xml'>;
}
declare module 'body-parser-xml/test.js' {
  declare module.exports: $Exports<'body-parser-xml/test'>;
}
