// flow-typed signature: 5c2473ab517a70e093449e83c3151ee8
// flow-typed version: <<STUB>>/bull_v^3.22.10/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare type $npm$bull$jobType =
  | "completed"
  | "waiting"
  | "active"
  | "delayed"
  | "failed";

declare type $npm$bull$jobPriority =
  | "low"
  | "normal"
  | "medium"
  | "high"
  | "critical";

declare type $npm$bull$jobOptions = {
  priority: $npm$bull$jobPriority,
  attempts: number
};

declare class bull$Job {
  static (queue: bull$Queue, data: Object, opts: $npm$bull$jobOptions): bull$Job;
  queue: bull$Queue;
  data: Object;
  opts: Object;
  delay: number;
  timestamp: Date;
  stacktrace: Array<string>;
  attempts: number;
  attemptsMade: number;
  remove(): Promise<any>;
  retry(): Promise<any>;
}

declare class bull$Queue {
  static (
    queueName: string,
    redisPort: number,
    redisHost: string,
    redisOptions?: Object
  ): bull$Queue;
  constructor(
    queueName: string,
    redisOptions?: Object
  ): bull$Queue;
  process(callback: callbackOrPromise): void;
  process(concurrency: number, callback: callbackOrPromise): void;
  add(data: Object, opts: Object): Promise<bull$Job>;
  add(data: Object): Promise<bull$Job>;
  pause(isLocal: boolean): Promise<any>;
  pause(): Promise<any>;
  resume(isLocal: boolean): Promise<any>;
  resume(): Promise<any>;
  count(): Promise<number>;
  close(): Promise<any>;
  getJob(jobId: string): Promise<bull$Job>;
  clean(grace: number, type: $npm$bull$jobType): Promise<Array<bull$Job>>;
  clean(grace: number): Promise<Array<bull$Job>>;
  on(status: string, callback: callbackOrPromise): Promise<any>;
}

declare type jobCallback = (job: bull$Job, done: Function) => void | Promise<any>;
declare type callbackOrPromise = jobCallback;

declare module "bull" {
  declare class PriorityQueue extends bull$Queue {}
  declare module.exports: typeof bull$Queue;
}
