// flow-typed signature: 35656713423179a52137e6cd39ccd6ad
// flow-typed version: <<STUB>>/cheerio_v^1.0.0-rc.10/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cheerio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cheerio/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/css' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio/lib/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/api/attributes' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/api/css' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/api/forms' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/api/manipulation' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/api/traversing' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/cheerio' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/load' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/options' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/parse' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/parsers/parse5-adapter' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/slim' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/static' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/types' {
  declare module.exports: any;
}

declare module 'cheerio/lib/esm/utils' {
  declare module.exports: any;
}

declare module 'cheerio/lib' {
  declare module.exports: any;
}

declare module 'cheerio/lib/load' {
  declare module.exports: any;
}

declare module 'cheerio/lib/options' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parse' {
  declare module.exports: any;
}

declare module 'cheerio/lib/parsers/parse5-adapter' {
  declare module.exports: any;
}

declare module 'cheerio/lib/slim' {
  declare module.exports: any;
}

declare module 'cheerio/lib/static' {
  declare module.exports: any;
}

declare module 'cheerio/lib/types' {
  declare module.exports: any;
}

declare module 'cheerio/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cheerio/lib/api/attributes.js' {
  declare module.exports: $Exports<'cheerio/lib/api/attributes'>;
}
declare module 'cheerio/lib/api/css.js' {
  declare module.exports: $Exports<'cheerio/lib/api/css'>;
}
declare module 'cheerio/lib/api/forms.js' {
  declare module.exports: $Exports<'cheerio/lib/api/forms'>;
}
declare module 'cheerio/lib/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio/lib/api/manipulation'>;
}
declare module 'cheerio/lib/api/traversing.js' {
  declare module.exports: $Exports<'cheerio/lib/api/traversing'>;
}
declare module 'cheerio/lib/cheerio.js' {
  declare module.exports: $Exports<'cheerio/lib/cheerio'>;
}
declare module 'cheerio/lib/esm/api/attributes.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/api/attributes'>;
}
declare module 'cheerio/lib/esm/api/css.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/api/css'>;
}
declare module 'cheerio/lib/esm/api/forms.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/api/forms'>;
}
declare module 'cheerio/lib/esm/api/manipulation.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/api/manipulation'>;
}
declare module 'cheerio/lib/esm/api/traversing.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/api/traversing'>;
}
declare module 'cheerio/lib/esm/cheerio.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/cheerio'>;
}
declare module 'cheerio/lib/esm/index' {
  declare module.exports: $Exports<'cheerio/lib/esm'>;
}
declare module 'cheerio/lib/esm/index.js' {
  declare module.exports: $Exports<'cheerio/lib/esm'>;
}
declare module 'cheerio/lib/esm/load.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/load'>;
}
declare module 'cheerio/lib/esm/options.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/options'>;
}
declare module 'cheerio/lib/esm/parse.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/parse'>;
}
declare module 'cheerio/lib/esm/parsers/parse5-adapter.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/parsers/parse5-adapter'>;
}
declare module 'cheerio/lib/esm/slim.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/slim'>;
}
declare module 'cheerio/lib/esm/static.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/static'>;
}
declare module 'cheerio/lib/esm/types.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/types'>;
}
declare module 'cheerio/lib/esm/utils.js' {
  declare module.exports: $Exports<'cheerio/lib/esm/utils'>;
}
declare module 'cheerio/lib/index' {
  declare module.exports: $Exports<'cheerio/lib'>;
}
declare module 'cheerio/lib/index.js' {
  declare module.exports: $Exports<'cheerio/lib'>;
}
declare module 'cheerio/lib/load.js' {
  declare module.exports: $Exports<'cheerio/lib/load'>;
}
declare module 'cheerio/lib/options.js' {
  declare module.exports: $Exports<'cheerio/lib/options'>;
}
declare module 'cheerio/lib/parse.js' {
  declare module.exports: $Exports<'cheerio/lib/parse'>;
}
declare module 'cheerio/lib/parsers/parse5-adapter.js' {
  declare module.exports: $Exports<'cheerio/lib/parsers/parse5-adapter'>;
}
declare module 'cheerio/lib/slim.js' {
  declare module.exports: $Exports<'cheerio/lib/slim'>;
}
declare module 'cheerio/lib/static.js' {
  declare module.exports: $Exports<'cheerio/lib/static'>;
}
declare module 'cheerio/lib/types.js' {
  declare module.exports: $Exports<'cheerio/lib/types'>;
}
declare module 'cheerio/lib/utils.js' {
  declare module.exports: $Exports<'cheerio/lib/utils'>;
}
