// flow-typed signature: 99571932739c2c7c234a9dd6720069a8
// flow-typed version: <<STUB>>/compress_v^0.99.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compress/index' {
  declare module.exports: $Exports<'compress'>;
}
declare module 'compress/index.js' {
  declare module.exports: $Exports<'compress'>;
}
