// flow-typed signature: 8bb504b0040eb1ef12746ef2ace62be3
// flow-typed version: <<STUB>>/credit-card-identifier_v^0.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'credit-card-identifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'credit-card-identifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'credit-card-identifier/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'credit-card-identifier/lib/index' {
  declare module.exports: $Exports<'credit-card-identifier/lib'>;
}
declare module 'credit-card-identifier/lib/index.js' {
  declare module.exports: $Exports<'credit-card-identifier/lib'>;
}
