// flow-typed signature: b6f34bb01f67e4d9e36cadeecd03704a
// flow-typed version: <<STUB>>/cron-cluster_v^1.1.3/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cron-cluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cron-cluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cron-cluster/lib/cron-cluster' {
  declare module.exports: any;
}

declare module 'cron-cluster/test/cron-cluster-compatibilty-check' {
  declare module.exports: any;
}

declare module 'cron-cluster/test/cron-cluster' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cron-cluster/index' {
  declare module.exports: $Exports<'cron-cluster'>;
}
declare module 'cron-cluster/index.js' {
  declare module.exports: $Exports<'cron-cluster'>;
}
declare module 'cron-cluster/lib/cron-cluster.js' {
  declare module.exports: $Exports<'cron-cluster/lib/cron-cluster'>;
}
declare module 'cron-cluster/test/cron-cluster-compatibilty-check.js' {
  declare module.exports: $Exports<'cron-cluster/test/cron-cluster-compatibilty-check'>;
}
declare module 'cron-cluster/test/cron-cluster.js' {
  declare module.exports: $Exports<'cron-cluster/test/cron-cluster'>;
}
