// flow-typed signature: 08c8218a64bccbefbe2ef82113cb6ca5
// flow-typed version: <<STUB>>/csv_v^2.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv/lib' {
  declare module.exports: any;
}

declare module 'csv/samples/callback' {
  declare module.exports: any;
}

declare module 'csv/samples/pipe' {
  declare module.exports: any;
}

declare module 'csv/samples/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv/lib/index' {
  declare module.exports: $Exports<'csv/lib'>;
}
declare module 'csv/lib/index.js' {
  declare module.exports: $Exports<'csv/lib'>;
}
declare module 'csv/samples/callback.js' {
  declare module.exports: $Exports<'csv/samples/callback'>;
}
declare module 'csv/samples/pipe.js' {
  declare module.exports: $Exports<'csv/samples/pipe'>;
}
declare module 'csv/samples/stream.js' {
  declare module.exports: $Exports<'csv/samples/stream'>;
}
