// flow-typed signature: ea996f8ca36abb0743254a695ec9d2e7
// flow-typed version: <<STUB>>/debug_v^4.3.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'debug/src/browser' {
  declare module.exports: any;
}

declare module 'debug/src/common' {
  declare module.exports: any;
}

declare module 'debug/src' {
  declare module.exports: any;
}

declare module 'debug/src/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'debug/src/browser.js' {
  declare module.exports: $Exports<'debug/src/browser'>;
}
declare module 'debug/src/common.js' {
  declare module.exports: $Exports<'debug/src/common'>;
}
declare module 'debug/src/index' {
  declare module.exports: $Exports<'debug/src'>;
}
declare module 'debug/src/index.js' {
  declare module.exports: $Exports<'debug/src'>;
}
declare module 'debug/src/node.js' {
  declare module.exports: $Exports<'debug/src/node'>;
}
