// flow-typed signature: 7913d56e5322388b0d76ab47e7fee887
// flow-typed version: <<STUB>>/deep-equal-in-any-order_v^2.0.5/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-equal-in-any-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-equal-in-any-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-equal-in-any-order/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-equal-in-any-order/build/index' {
  declare module.exports: $Exports<'deep-equal-in-any-order/build'>;
}
declare module 'deep-equal-in-any-order/build/index.js' {
  declare module.exports: $Exports<'deep-equal-in-any-order/build'>;
}
