// flow-typed signature: 00273dea56d80927faff3626687aad06
// flow-typed version: <<STUB>>/escope_v^4.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'escope/lib/definition' {
  declare module.exports: any;
}

declare module 'escope/lib' {
  declare module.exports: any;
}

declare module 'escope/lib/pattern-visitor' {
  declare module.exports: any;
}

declare module 'escope/lib/reference' {
  declare module.exports: any;
}

declare module 'escope/lib/referencer' {
  declare module.exports: any;
}

declare module 'escope/lib/scope-manager' {
  declare module.exports: any;
}

declare module 'escope/lib/scope' {
  declare module.exports: any;
}

declare module 'escope/lib/variable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'escope/lib/definition.js' {
  declare module.exports: $Exports<'escope/lib/definition'>;
}
declare module 'escope/lib/index' {
  declare module.exports: $Exports<'escope/lib'>;
}
declare module 'escope/lib/index.js' {
  declare module.exports: $Exports<'escope/lib'>;
}
declare module 'escope/lib/pattern-visitor.js' {
  declare module.exports: $Exports<'escope/lib/pattern-visitor'>;
}
declare module 'escope/lib/reference.js' {
  declare module.exports: $Exports<'escope/lib/reference'>;
}
declare module 'escope/lib/referencer.js' {
  declare module.exports: $Exports<'escope/lib/referencer'>;
}
declare module 'escope/lib/scope-manager.js' {
  declare module.exports: $Exports<'escope/lib/scope-manager'>;
}
declare module 'escope/lib/scope.js' {
  declare module.exports: $Exports<'escope/lib/scope'>;
}
declare module 'escope/lib/variable.js' {
  declare module.exports: $Exports<'escope/lib/variable'>;
}
