// flow-typed signature: 214e45555728be50cd18e2fee2b719be
// flow-typed version: <<STUB>>/express-state_v^2.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-state/lib/exposed' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-state/index' {
  declare module.exports: $Exports<'express-state'>;
}
declare module 'express-state/index.js' {
  declare module.exports: $Exports<'express-state'>;
}
declare module 'express-state/lib/exposed.js' {
  declare module.exports: $Exports<'express-state/lib/exposed'>;
}
