// flow-typed signature: 02566d6a8ec87690a907f9c1359788be
// flow-typed version: <<STUB>>/express-rate-limit_v6.7.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-rate-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare type expressRateLimit$Options = {
  windowMs: number,
  max: number | ((req: express$Request, res: express$Response) => number),
  message: string,
  statusCode: number,
  legacyHeaders: boolean,
  standardHeaders: boolean,
  requestPropertyName: string,
  skipFailedRequests: boolean,
  skipSuccessfulRequests: boolean,
  skip: (req: express$Request, res: express$Response) => boolean | Promise<boolean>,
  keyGenerator: (req: express$Request) => string | Promise<string>,
  handler: (
    req: express$Request,
    res: express$Response,
    next: express$NextFunction,
    options: any,
  ) => mixed,
  store: any,
};

declare module 'express-rate-limit' {
  declare module.exports: {
    (options: Partial<expressRateLimit$Options>): express$Middleware<express$Request, express$Response>,
    ...
  };
}
