// flow-typed signature: 0d49799a08687bfa1900de650d6869e6
// flow-typed version: <<STUB>>/express-throttle_v^2.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-throttle/lib/memory-store' {
  declare module.exports: any;
}

declare module 'express-throttle/lib/options' {
  declare module.exports: any;
}

declare module 'express-throttle/lib/throttle' {
  declare module.exports: any;
}

declare module 'express-throttle/test/benchmark' {
  declare module.exports: any;
}

declare module 'express-throttle/test/options.unit' {
  declare module.exports: any;
}

declare module 'express-throttle/test/throttle.unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-throttle/index' {
  declare module.exports: $Exports<'express-throttle'>;
}
declare module 'express-throttle/index.js' {
  declare module.exports: $Exports<'express-throttle'>;
}
declare module 'express-throttle/lib/memory-store.js' {
  declare module.exports: $Exports<'express-throttle/lib/memory-store'>;
}
declare module 'express-throttle/lib/options.js' {
  declare module.exports: $Exports<'express-throttle/lib/options'>;
}
declare module 'express-throttle/lib/throttle.js' {
  declare module.exports: $Exports<'express-throttle/lib/throttle'>;
}
declare module 'express-throttle/test/benchmark.js' {
  declare module.exports: $Exports<'express-throttle/test/benchmark'>;
}
declare module 'express-throttle/test/options.unit.js' {
  declare module.exports: $Exports<'express-throttle/test/options.unit'>;
}
declare module 'express-throttle/test/throttle.unit.js' {
  declare module.exports: $Exports<'express-throttle/test/throttle.unit'>;
}
