// flow-typed signature: 31428d015a688aadd179ab5aef12d889
// flow-typed version: <<STUB>>/express-basic-auth_v^1.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-basic-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-basic-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-basic-auth/example' {
  declare module.exports: any;
}

declare module 'express-basic-auth/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-basic-auth/example.js' {
  declare module.exports: $Exports<'express-basic-auth/example'>;
}
declare module 'express-basic-auth/index' {
  declare module.exports: $Exports<'express-basic-auth'>;
}
declare module 'express-basic-auth/index.js' {
  declare module.exports: $Exports<'express-basic-auth'>;
}
declare module 'express-basic-auth/test.js' {
  declare module.exports: $Exports<'express-basic-auth/test'>;
}
