// flow-typed signature: e67c2cb922c11433fcbf065a3ec48489
// flow-typed version: <<STUB>>/flow-upgrade_v^2.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-upgrade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-upgrade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-upgrade/dist/bin/runSpecificCodemod' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/bin/upgrade' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/collapseObjectInitialization' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/convertImplicitInexactObjectTypes' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/convertShapeToPartial' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/removeAnnotationsInDestructuring' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/removeDuplicateClassProperties' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/removeExplicitlyExactObjectTypeSyntax' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/renamePartial' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/typeParameterBoundExactEmptyObjectToInexact' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemodUtils/getClassMemberName' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemodUtils/replaceMethodWithArrowProp' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/findFlowFiles' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/runCodemods' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/Styled' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/Types' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrade' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.170.0' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.176.0' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.201.0' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.84.0' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/utils/redirectConsole' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-upgrade/dist/bin/runSpecificCodemod.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/bin/runSpecificCodemod'>;
}
declare module 'flow-upgrade/dist/bin/upgrade.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/bin/upgrade'>;
}
declare module 'flow-upgrade/dist/codemods/collapseObjectInitialization.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/collapseObjectInitialization'>;
}
declare module 'flow-upgrade/dist/codemods/convertImplicitInexactObjectTypes.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/convertImplicitInexactObjectTypes'>;
}
declare module 'flow-upgrade/dist/codemods/convertShapeToPartial.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/convertShapeToPartial'>;
}
declare module 'flow-upgrade/dist/codemods/removeAnnotationsInDestructuring.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/removeAnnotationsInDestructuring'>;
}
declare module 'flow-upgrade/dist/codemods/removeDuplicateClassProperties.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/removeDuplicateClassProperties'>;
}
declare module 'flow-upgrade/dist/codemods/removeExplicitlyExactObjectTypeSyntax.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/removeExplicitlyExactObjectTypeSyntax'>;
}
declare module 'flow-upgrade/dist/codemods/renamePartial.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/renamePartial'>;
}
declare module 'flow-upgrade/dist/codemods/typeParameterBoundExactEmptyObjectToInexact.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/typeParameterBoundExactEmptyObjectToInexact'>;
}
declare module 'flow-upgrade/dist/codemodUtils/getClassMemberName.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemodUtils/getClassMemberName'>;
}
declare module 'flow-upgrade/dist/codemodUtils/replaceMethodWithArrowProp.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemodUtils/replaceMethodWithArrowProp'>;
}
declare module 'flow-upgrade/dist/findFlowFiles.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/findFlowFiles'>;
}
declare module 'flow-upgrade/dist/runCodemods.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/runCodemods'>;
}
declare module 'flow-upgrade/dist/Styled.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/Styled'>;
}
declare module 'flow-upgrade/dist/Types.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/Types'>;
}
declare module 'flow-upgrade/dist/upgrade.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrade'>;
}
declare module 'flow-upgrade/dist/upgrades/0.170.0/index' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.170.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.170.0/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.170.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.176.0/index' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.176.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.176.0/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.176.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.201.0/index' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.201.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.201.0/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.201.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.84.0/index' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.84.0'>;
}
declare module 'flow-upgrade/dist/upgrades/0.84.0/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.84.0'>;
}
declare module 'flow-upgrade/dist/upgrades/index' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades'>;
}
declare module 'flow-upgrade/dist/upgrades/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades'>;
}
declare module 'flow-upgrade/dist/utils/redirectConsole.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/utils/redirectConsole'>;
}
