// flow-typed signature: 7f06abade1ea11cdf3b274c18871e45a
// flow-typed version: <<STUB>>/freeport_v^1.0.5/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'freeport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'freeport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'freeport/lib/freeport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'freeport/lib/freeport.js' {
  declare module.exports: $Exports<'freeport/lib/freeport'>;
}
