// flow-typed signature: 8d6da282aa5f9a2594af108ecb2946b3
// flow-typed version: <<STUB>>/google-auth-library_v9.14.0/flow_v0.244.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-auth-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-auth-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-auth-library/build/src/auth/authclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/awsclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/awsrequestsigner' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/baseexternalclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/computeclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/credentials' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/defaultawssecuritycredentialssupplier' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/downscopedclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/envDetect' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/executable-response' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/externalAccountAuthorizedUserClient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/externalclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/filesubjecttokensupplier' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/googleauth' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/iam' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/identitypoolclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/idtokenclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/impersonated' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/jwtaccess' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/jwtclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/loginticket' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/oauth2client' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/oauth2common' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/passthrough' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/pluggable-auth-client' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/pluggable-auth-handler' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/refreshclient' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/stscredentials' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/auth/urlsubjecttokensupplier' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/crypto/browser/crypto' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/crypto/crypto' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/crypto/node/crypto' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/messages' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/options' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/transporters' {
  declare module.exports: any;
}

declare module 'google-auth-library/build/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-auth-library/build/src/auth/authclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/authclient'>;
}
declare module 'google-auth-library/build/src/auth/awsclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/awsclient'>;
}
declare module 'google-auth-library/build/src/auth/awsrequestsigner.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/awsrequestsigner'>;
}
declare module 'google-auth-library/build/src/auth/baseexternalclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/baseexternalclient'>;
}
declare module 'google-auth-library/build/src/auth/computeclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/computeclient'>;
}
declare module 'google-auth-library/build/src/auth/credentials.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/credentials'>;
}
declare module 'google-auth-library/build/src/auth/defaultawssecuritycredentialssupplier.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/defaultawssecuritycredentialssupplier'>;
}
declare module 'google-auth-library/build/src/auth/downscopedclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/downscopedclient'>;
}
declare module 'google-auth-library/build/src/auth/envDetect.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/envDetect'>;
}
declare module 'google-auth-library/build/src/auth/executable-response.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/executable-response'>;
}
declare module 'google-auth-library/build/src/auth/externalAccountAuthorizedUserClient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/externalAccountAuthorizedUserClient'>;
}
declare module 'google-auth-library/build/src/auth/externalclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/externalclient'>;
}
declare module 'google-auth-library/build/src/auth/filesubjecttokensupplier.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/filesubjecttokensupplier'>;
}
declare module 'google-auth-library/build/src/auth/googleauth.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/googleauth'>;
}
declare module 'google-auth-library/build/src/auth/iam.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/iam'>;
}
declare module 'google-auth-library/build/src/auth/identitypoolclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/identitypoolclient'>;
}
declare module 'google-auth-library/build/src/auth/idtokenclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/idtokenclient'>;
}
declare module 'google-auth-library/build/src/auth/impersonated.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/impersonated'>;
}
declare module 'google-auth-library/build/src/auth/jwtaccess.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/jwtaccess'>;
}
declare module 'google-auth-library/build/src/auth/jwtclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/jwtclient'>;
}
declare module 'google-auth-library/build/src/auth/loginticket.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/loginticket'>;
}
declare module 'google-auth-library/build/src/auth/oauth2client.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/oauth2client'>;
}
declare module 'google-auth-library/build/src/auth/oauth2common.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/oauth2common'>;
}
declare module 'google-auth-library/build/src/auth/passthrough.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/passthrough'>;
}
declare module 'google-auth-library/build/src/auth/pluggable-auth-client.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/pluggable-auth-client'>;
}
declare module 'google-auth-library/build/src/auth/pluggable-auth-handler.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/pluggable-auth-handler'>;
}
declare module 'google-auth-library/build/src/auth/refreshclient.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/refreshclient'>;
}
declare module 'google-auth-library/build/src/auth/stscredentials.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/stscredentials'>;
}
declare module 'google-auth-library/build/src/auth/urlsubjecttokensupplier.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/auth/urlsubjecttokensupplier'>;
}
declare module 'google-auth-library/build/src/crypto/browser/crypto.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/crypto/browser/crypto'>;
}
declare module 'google-auth-library/build/src/crypto/crypto.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/crypto/crypto'>;
}
declare module 'google-auth-library/build/src/crypto/node/crypto.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/crypto/node/crypto'>;
}
declare module 'google-auth-library/build/src/index' {
  declare module.exports: $Exports<'google-auth-library/build/src'>;
}
declare module 'google-auth-library/build/src/index.js' {
  declare module.exports: $Exports<'google-auth-library/build/src'>;
}
declare module 'google-auth-library/build/src/messages.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/messages'>;
}
declare module 'google-auth-library/build/src/options.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/options'>;
}
declare module 'google-auth-library/build/src/transporters.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/transporters'>;
}
declare module 'google-auth-library/build/src/util.js' {
  declare module.exports: $Exports<'google-auth-library/build/src/util'>;
}
