// flow-typed signature: c02099e34f15f2323d53566860a4a983
// flow-typed version: <<STUB>>/inline-css_v^4.0.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inline-css/lib/addProps' {
  declare module.exports: any;
}

declare module 'inline-css/lib/cssProperty' {
  declare module.exports: any;
}

declare module 'inline-css/lib/handleRule' {
  declare module.exports: any;
}

declare module 'inline-css/lib/inline-css' {
  declare module.exports: any;
}

declare module 'inline-css/lib/inlineContent' {
  declare module.exports: any;
}

declare module 'inline-css/lib/pseudoCheck' {
  declare module.exports: any;
}

declare module 'inline-css/lib/removeClassId' {
  declare module.exports: any;
}

declare module 'inline-css/lib/setStyleAttrs' {
  declare module.exports: any;
}

declare module 'inline-css/lib/setTableAttrs' {
  declare module.exports: any;
}

declare module 'inline-css/lib/setWidthAttrs' {
  declare module.exports: any;
}

declare module 'inline-css/lib/styleSelector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inline-css/index' {
  declare module.exports: $Exports<'inline-css'>;
}
declare module 'inline-css/index.js' {
  declare module.exports: $Exports<'inline-css'>;
}
declare module 'inline-css/lib/addProps.js' {
  declare module.exports: $Exports<'inline-css/lib/addProps'>;
}
declare module 'inline-css/lib/cssProperty.js' {
  declare module.exports: $Exports<'inline-css/lib/cssProperty'>;
}
declare module 'inline-css/lib/handleRule.js' {
  declare module.exports: $Exports<'inline-css/lib/handleRule'>;
}
declare module 'inline-css/lib/inline-css.js' {
  declare module.exports: $Exports<'inline-css/lib/inline-css'>;
}
declare module 'inline-css/lib/inlineContent.js' {
  declare module.exports: $Exports<'inline-css/lib/inlineContent'>;
}
declare module 'inline-css/lib/pseudoCheck.js' {
  declare module.exports: $Exports<'inline-css/lib/pseudoCheck'>;
}
declare module 'inline-css/lib/removeClassId.js' {
  declare module.exports: $Exports<'inline-css/lib/removeClassId'>;
}
declare module 'inline-css/lib/setStyleAttrs.js' {
  declare module.exports: $Exports<'inline-css/lib/setStyleAttrs'>;
}
declare module 'inline-css/lib/setTableAttrs.js' {
  declare module.exports: $Exports<'inline-css/lib/setTableAttrs'>;
}
declare module 'inline-css/lib/setWidthAttrs.js' {
  declare module.exports: $Exports<'inline-css/lib/setWidthAttrs'>;
}
declare module 'inline-css/lib/styleSelector.js' {
  declare module.exports: $Exports<'inline-css/lib/styleSelector'>;
}
