// flow-typed signature: 9276baa92d801ca39405b32fc40373e6
// flow-typed version: <<STUB>>/ip-range-check_v^0.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ip-range-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ip-range-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ip-range-check/index' {
  declare module.exports: $Exports<'ip-range-check'>;
}
declare module 'ip-range-check/index.js' {
  declare module.exports: $Exports<'ip-range-check'>;
}
