// flow-typed signature: e70b7d592e365325b5dd19c8a1abc33b
// flow-typed version: <<STUB>>/ipware_v^2.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipware/test/ipv4_test' {
  declare module.exports: any;
}

declare module 'ipware/test/ipv6_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipware/index' {
  declare module.exports: $Exports<'ipware'>;
}
declare module 'ipware/index.js' {
  declare module.exports: $Exports<'ipware'>;
}
declare module 'ipware/test/ipv4_test.js' {
  declare module.exports: $Exports<'ipware/test/ipv4_test'>;
}
declare module 'ipware/test/ipv6_test.js' {
  declare module.exports: $Exports<'ipware/test/ipv6_test'>;
}
