// flow-typed signature: 3ec8806997810915638234bcfb966746
// flow-typed version: <<STUB>>/iso-3166-1_v^2.0.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iso-3166-1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iso-3166-1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iso-3166-1/dist' {
  declare module.exports: any;
}

declare module 'iso-3166-1/dist/iso-3166' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iso-3166-1/dist/index' {
  declare module.exports: $Exports<'iso-3166-1/dist'>;
}
declare module 'iso-3166-1/dist/index.js' {
  declare module.exports: $Exports<'iso-3166-1/dist'>;
}
declare module 'iso-3166-1/dist/iso-3166.js' {
  declare module.exports: $Exports<'iso-3166-1/dist/iso-3166'>;
}
