// flow-typed signature: 56a7dd8e938a39468e2bf10d488e530d
// flow-typed version: <<STUB>>/js-yaml_v^4.1.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */


declare module 'js-yaml' {

  // copied from: flow-typed version: c6154227d1/js-yaml_v3.x.x/flow_>=v0.104.x
  declare type Kind = 'sequence' | 'scalar' | 'mapping';

  declare type DumpOptions = {
    indent?: number,
    skipInvalid?: boolean,
    flowLevel?: number,
    styles?: { [string]: any, ... },
    schema?: Schema,
    sortKeys?: boolean | ((a: any, b: any) => number),
    lineWidth?: number,
    noRefs?: boolean,
    noCompatMode?: boolean,
    condenseFlow?: boolean,
  };

  declare type LoadOptions = {
    filename?: string,
    strict?: boolean,
    schema?: Schema,
    json?: boolean,
  };

  declare type SchemaDefinition = {
    implicit?: Array<Type>,
    explicit?: Array<Type>,
    include?: Array<Schema>,
  };

  declare type TypeConstructorOptions = {
    kind?: Kind,
    resolve?: (data: any) => boolean,
    construct?: (data: any) => any,
    instanceOf?: Object,
    predicate?: string,
    represent?: ((data: Object) => any) | { [string]: (data: Object) => any, ... },
    defaultStyle?: string,
    styleAliases?: { [string]: any, ... },
  };

  declare class Schema {  // implements SchemaDefinition
    static DEFAULT: ?Schema;

    implicit: Array<Type>;
    explicit: Array<Type>;
    include: Array<Schema>;

    compiledImplicit: Array<Type>;
    compiledExplicit: Array<Type>;
    compiledTypeMap: { [Kind | 'fallback']: { [string]: Type, ... }, ... };

    constructor(definition: SchemaDefinition): this;

    static create(types: Array<Type> | Type): Schema;
    static create(schemas: Array<Schema> | Schema, types: Array<Type> | Type): Schema;
  }

  declare class Type {
    tag: string;
    kind: Kind;
    instanceOf: ?Object;
    predicate: ?string;
    represent: ((data: Object) => any) | { [string]: (data: Object) => any, ... } | null;
    defaultStyle: ?string;
    styleAliases: { [string]: any, ... };

    constructor(tag: string, opts?: TypeConstructorOptions): this;

    resolve(data: any): boolean;

    construct(data: any): any;
  }

  declare class YAMLException extends Error {
    constructor(reason?: any, mark?: any): this;

    toString(compact?: boolean): string;
  }

  declare var CORE_SCHEMA: Schema;
  declare var DEFAULT_FULL_SCHEMA: Schema;
  declare var DEFAULT_SAFE_SCHEMA: Schema;
  declare var FAILSAFE_SCHEMA: Schema;
  declare var JSON_SCHEMA: Schema;
  declare var MINIMAL_SCHEMA: Schema;
  declare var SAFE_SCHEMA: Schema;

  declare function load(input: string, opts?: LoadOptions): mixed;

  declare function safeLoad(input: string, opts?: LoadOptions): mixed;

  declare function loadAll(input: string, output?: void | null, opts?: LoadOptions): Array<mixed>;
  declare function loadAll(input: string, output: (doc: mixed) => void, opts?: LoadOptions): void;

  declare function safeLoadAll(input: string, output?: void | null, opts?: LoadOptions): Array<mixed>;
  declare function safeLoadAll(input: string, output: (doc: mixed) => void, opts?: LoadOptions): void;

  declare function dump(input: mixed, opts?: DumpOptions): string;

  declare function safeDump(input: mixed, opts?: DumpOptions): string;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-yaml/bin/js-yaml' {
  declare module.exports: any;
}

declare module 'js-yaml/dist/js-yaml' {
  declare module.exports: any;
}

declare module 'js-yaml/dist/js-yaml.min' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/common' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/dumper' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/exception' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/loader' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/schema' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/schema/core' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/schema/default' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/schema/failsafe' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/schema/json' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/snippet' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/binary' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/bool' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/float' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/int' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/map' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/merge' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/null' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/omap' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/pairs' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/seq' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/set' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/str' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/type/timestamp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-yaml/bin/js-yaml.js' {
  declare module.exports: $Exports<'js-yaml/bin/js-yaml'>;
}
declare module 'js-yaml/dist/js-yaml.js' {
  declare module.exports: $Exports<'js-yaml/dist/js-yaml'>;
}
declare module 'js-yaml/dist/js-yaml.min.js' {
  declare module.exports: $Exports<'js-yaml/dist/js-yaml.min'>;
}
declare module 'js-yaml/index' {
  declare module.exports: $Exports<'js-yaml'>;
}
declare module 'js-yaml/index.js' {
  declare module.exports: $Exports<'js-yaml'>;
}
declare module 'js-yaml/lib/common.js' {
  declare module.exports: $Exports<'js-yaml/lib/common'>;
}
declare module 'js-yaml/lib/dumper.js' {
  declare module.exports: $Exports<'js-yaml/lib/dumper'>;
}
declare module 'js-yaml/lib/exception.js' {
  declare module.exports: $Exports<'js-yaml/lib/exception'>;
}
declare module 'js-yaml/lib/loader.js' {
  declare module.exports: $Exports<'js-yaml/lib/loader'>;
}
declare module 'js-yaml/lib/schema.js' {
  declare module.exports: $Exports<'js-yaml/lib/schema'>;
}
declare module 'js-yaml/lib/schema/core.js' {
  declare module.exports: $Exports<'js-yaml/lib/schema/core'>;
}
declare module 'js-yaml/lib/schema/default.js' {
  declare module.exports: $Exports<'js-yaml/lib/schema/default'>;
}
declare module 'js-yaml/lib/schema/failsafe.js' {
  declare module.exports: $Exports<'js-yaml/lib/schema/failsafe'>;
}
declare module 'js-yaml/lib/schema/json.js' {
  declare module.exports: $Exports<'js-yaml/lib/schema/json'>;
}
declare module 'js-yaml/lib/snippet.js' {
  declare module.exports: $Exports<'js-yaml/lib/snippet'>;
}
declare module 'js-yaml/lib/type.js' {
  declare module.exports: $Exports<'js-yaml/lib/type'>;
}
declare module 'js-yaml/lib/type/binary.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/binary'>;
}
declare module 'js-yaml/lib/type/bool.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/bool'>;
}
declare module 'js-yaml/lib/type/float.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/float'>;
}
declare module 'js-yaml/lib/type/int.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/int'>;
}
declare module 'js-yaml/lib/type/map.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/map'>;
}
declare module 'js-yaml/lib/type/merge.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/merge'>;
}
declare module 'js-yaml/lib/type/null.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/null'>;
}
declare module 'js-yaml/lib/type/omap.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/omap'>;
}
declare module 'js-yaml/lib/type/pairs.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/pairs'>;
}
declare module 'js-yaml/lib/type/seq.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/seq'>;
}
declare module 'js-yaml/lib/type/set.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/set'>;
}
declare module 'js-yaml/lib/type/str.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/str'>;
}
declare module 'js-yaml/lib/type/timestamp.js' {
  declare module.exports: $Exports<'js-yaml/lib/type/timestamp'>;
}
