// flow-typed signature: 822756651f567df916f2da9597574c4b
// flow-typed version: <<STUB>>/json2xml_v^0.1.3/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json2xml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json2xml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json2xml/grunt' {
  declare module.exports: any;
}

declare module 'json2xml/lib/json2xml' {
  declare module.exports: any;
}

declare module 'json2xml/test/json2xml_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json2xml/grunt.js' {
  declare module.exports: $Exports<'json2xml/grunt'>;
}
declare module 'json2xml/index' {
  declare module.exports: $Exports<'json2xml'>;
}
declare module 'json2xml/index.js' {
  declare module.exports: $Exports<'json2xml'>;
}
declare module 'json2xml/lib/json2xml.js' {
  declare module.exports: $Exports<'json2xml/lib/json2xml'>;
}
declare module 'json2xml/test/json2xml_test.js' {
  declare module.exports: $Exports<'json2xml/test/json2xml_test'>;
}
