// flow-typed signature: fc6dccb95816428a2a8547c6abfe9f11
// flow-typed version: <<STUB>>/luxon_v^3.2.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luxon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// copied from: flow-typed version: 7a0ca7d60e/luxon_v1.x.x/flow_>=v0.104.x
declare type WeekdayLength = "narrow" | "short" | "long";
declare type EraLength = "narrow" | "short" | "long";
declare type MonthLength =
  | "numeric"
  | "2-digit"
  | "narrow"
  | "short"
  | "long";
declare type NumericLength = "numeric" | "2-digit";

declare type HourCycle = "h11" | "h12" | "h23" | "h24";

declare type IntlDateTimeFormatOptions = {
  localeMatcher?: "lookup" | "best fit",
  timeZone?: string,
  hour12?: boolean,
  hourCycle?: HourCycle,
  formatMatcher?: "basic" | "best fit",
  weekday?: WeekdayLength,
  era?: EraLength,
  year?: NumericLength,
  month?: MonthLength,
  day?: NumericLength,
  hour?: NumericLength,
  minute?: NumericLength,
  second?: NumericLength,
  timeZoneName?: "short" | "long",
};

declare class  Zone {
  static offsetName(
    ts: number,
    opts?: {
      format?: ?string,
      localeCode?: ?string,
      ...
    }
  ): string;
  +isValid: boolean;
  +name: string;
  +type: string;
  +universal: boolean;
  equals(otherZone: Zone): boolean;
  offset(ts: number): number;
}

declare class  Settings {
  static defaultLocale: string;
  static defaultNumberingSystem: ?string;
  static defaultOutputCalendar: ?string;
  static defaultZone: Zone;
  static defaultZoneName: string;
  static now: () => number;
  static throwOnInvalid: boolean;
  static resetCaches(): void;
}

declare type MonthWeekdayOptions = {
  locale?: ?string,
  numberingSystem?: ?string,
  outputCalendar?: ?string,
};

declare class  Info {
  static eras(
    length: EraLength,
    options?: { locale?: ?string, }
  ): Array<string>;
  static features(): {
    intl: boolean,
    intlTokens: boolean,
    timezones: boolean,
    ...
  };
  static hasDST(zone: string | Zone): boolean;
  static isValidIANAZone(zone: string): boolean;
  static meridiems(options?: { locale?: ?string, }): Array<string>;
  static months(
    length: MonthLength,
    options?: MonthWeekdayOptions
  ): Array<string>;
  static monthsFormat(
    length: MonthLength,
    options?: MonthWeekdayOptions
  ): Array<string>;
  static weekdays(
    length: WeekdayLength,
    options?: MonthWeekdayOptions
  ): Array<string>;
  static weekdaysFormat(
    length: WeekdayLength,
    options?: MonthWeekdayOptions
  ): Array<string>;
}

declare type ConversionAccuracy = "longterm" | "casual";

declare type DateTimeUnit =
  | "year"
  | "years"
  | "month"
  | "months"
  | "day"
  | "days"
  | "hour"
  | "hours"
  | "minute"
  | "minutes"
  | "second"
  | "seconds"
  | "millisecond"
  | "milliseconds"
  | "weekNumber"
  | "weekNumbers"
  | "weekYear"
  | "weekYears"
  | "weekday"
  | "weekdays"
  | "week"
  | "weeks"
  | "ordinal";

declare type DurationUnit =
  | "year"
  | "years"
  | "month"
  | "months"
  | "week"
  | "weeks"
  | "day"
  | "days"
  | "hour"
  | "hours"
  | "minute"
  | "minutes"
  | "second"
  | "seconds"
  | "millisecond"
  | "milliseconds";

declare type RelativeUnit =
  | "years"
  | "months"
  | "weeks"
  | "days"
  | "hours"
  | "minutes"
  | "seconds";

declare class  Interval {
  static after(
    start: DateTime | DateTimeFromObjectOptions | Date,
    duration: Duration | number | DurationFromObjectOptions
  ): Interval;
  static before(
    end: DateTime | DateTimeFromObjectOptions | Date,
    duration: Duration | number | DurationFromObjectOptions
  ): Interval;
  static fromDateTimes(
    start: DateTime | DateTimeFromObjectOptions | Date,
    end: DateTime | DateTimeFromObjectOptions | Date
  ): Interval;
  static fromISO(string: string, options?: DateTimeFromOptions): Interval;
  static invalid(reason: string): Interval;
  static merge(intervals: Array<Interval>): Array<Interval>;
  static xor(intervals: Array<Interval>): Array<Interval>;
  end: DateTime;
  invalidReason: ?string;
  isValid: boolean;
  start: DateTime;
  abutsEnd(other: Interval): boolean;
  abutsStart(other: Interval): boolean;
  contains(dateTime: DateTime): boolean;
  count(unit: DurationUnit): number;
  difference(...intervals: Array<Interval>): Interval;
  divideEqually(numberOfParts: number): Array<Interval>;
  engulfs(other: Interval): boolean;
  equals(other: Interval): boolean;
  hasSame(unit: DurationUnit): boolean;
  inspect(): string;
  intersection(other: Interval): Interval;
  isAfter(dateTime: DateTime): boolean;
  isBefore(dateTime: DateTime): boolean;
  isEmpty(): boolean;
  length(unit: DurationUnit): number;
  overlaps(other: Interval): boolean;
  set(values: { start?: DateTime, end?: DateTime, }): Interval;
  splitAt(...dateTimes: Array<DateTime>): Array<Interval>;
  splitBy(duration: number | Duration | DurationFromObjectOptions): Array<Interval>;
  toDuration(
    unit: DurationUnit | Array<DurationUnit>,
    options?: { conversionAccuracy?: ?ConversionAccuracy, }
  ): Duration;
  toFormat(dateFormat: string, options?: { separator?: string, }): string;
  toISO(options?: ToISOOptions): string;
  toString(): string;
  union(other: Interval): Interval;
}

declare type DurationFromOptions = {
  locale?: ?string,
  numberingSystem?: ?string,
  conversionAccuracy?: ?ConversionAccuracy,
};

declare type DurationFromObjectOptions = {
  year?: number,
  years?: number,
  month?: number,
  months?: number,
  week?: number,
  weeks?: number,
  day?: number,
  days?: number,
  hour?: number,
  hours?: number,
  minute?: number,
  minutes?: number,
  second?: number,
  seconds?: number,
  millsecond?: number,
  milliseconds?: number,
  locale?: ?string,
  numberingSystem?: ?string,
  conversionAccuracy?: ?ConversionAccuracy,
};

declare type DurationObject = {
  years?: number,
  months?: number,
  days?: number,
  hours?: number,
  minutes?: number,
  seconds?: number,
  milliseconds?: number,
  ...
};

declare type DurationConfig = {
  locale: string,
  numberingSystem: ?string,
  conversionAccuracy: ConversionAccuracy,
  ...
};

declare class  Duration {
  static fromISO(text: string, options?: DurationFromOptions): Duration;
  static fromObject(obj: DurationFromObjectOptions): Duration;
  static fromMillis(count: number, options?: DurationFromOptions): Duration;
  static invalid(reason: string): Duration;
  days: number;
  hours: number;
  invalidReason: ?string;
  isValid: boolean;
  locale: string;
  milliseconds: number;
  minutes: number;
  months: number;
  numberingSystem: string;
  seconds: number;
  weeks: number;
  years: number;
  as(unit: DurationUnit): number;
  equals(other: Duration): boolean;
  get(unit: DurationUnit): number;
  inspect(): string;
  minus(duration: Duration | number | DurationFromObjectOptions): Duration;
  negate(): Duration;
  normalize(): Duration;
  plus(duration: Duration | number | DurationFromObjectOptions): Duration;
  reconfigure(options: DurationFromOptions): Duration;
  set(values: DurationFromObjectOptions): Duration;
  shiftTo(first: DurationUnit, ...rest: Array<DurationUnit>): Duration;
  toFormat(fmt: string, options?: { round?: boolean, }): string;
  toISO(): string;
  toJSON(): string;
  toObject(options: { includeConfig: true, }): DurationObject &
    DurationConfig;
  toObject(options?: { includeConfig?: boolean, }): DurationObject;
  toString(): string;
  valueOf(): number;
}

declare type DateTimeFromOptions = {
  zone?: ?(string | Zone),
  setZone?: ?boolean,
  locale?: ?string,
  outputCalendar?: ?string,
  numberingSystem?: ?string,
};

declare type ToISOOptions = {
  suppressMilliseconds?: ?boolean,
  suppressSeconds?: ?boolean,
  includeOffset?: ?boolean,
};

declare type SetZoneOptions = {
  keepCalendarTime?: ?boolean, // Support deprecated name for keepLocalTime
  keepLocalTime?: ?boolean,
};

declare type DateTimeFieldsOptions = {
  year?: number,
  years?: number,
  month?: number,
  months?: number,
  day?: number,
  days?: number,
  hour?: number,
  hours?: number,
  minute?: number,
  minutes?: number,
  second?: number,
  seconds?: number,
  millisecond?: number,
  milliseconds?: number,
  weekNumber?: number,
  weekNumbers?: number,
  weekYear?: number,
  weekYears?: number,
  weekday?: number,
  weekdays?: number,
  week?: number,
  weeks?: number,
};

declare type DateTimeFromObjectOptions = {
  year?: number,
  years?: number,
  month?: number,
  months?: number,
  day?: number,
  days?: number,
  hour?: number,
  hours?: number,
  minute?: number,
  minutes?: number,
  second?: number,
  seconds?: number,
  millisecond?: number,
  milliseconds?: number,
  weekNumber?: number,
  weekNumbers?: number,
  weekYear?: number,
  weekYears?: number,
  weekday?: number,
  weekdays?: number,
  week?: number,
  weeks?: number,
  zone?: ?(string | Zone),
  setZone?: ?boolean,
  locale?: ?string,
  outputCalendar?: ?string,
  numberingSystem?: ?string,
};

declare type DateTimeDiffOptions = {
  conversionAccuracy?: ?ConversionAccuracy,
};

declare type DateTimeObject = {
  year: number,
  month: number,
  day: number,
  hour: number,
  minute: number,
  second: number,
  millisecond: number,
  ...
};

declare type DateTimeConfig = {
  locale: string,
  outputCalendar: ?string,
  numberingSystem: ?string,
  ...
};

declare type ResolvedLocaleOptions = {
  locale: string,
  outputCalendar: string,
  numberingSystem: string,
  ...
};

declare class DateTime {
  static DATETIME_FULL: IntlDateTimeFormatOptions;
  static DATETIME_FULL_WITH_SECONDS: IntlDateTimeFormatOptions;
  static DATETIME_HUGE: IntlDateTimeFormatOptions;
  static DATETIME_HUGE_WITH_SECONDS: IntlDateTimeFormatOptions;
  static DATETIME_MED: IntlDateTimeFormatOptions;
  static DATETIME_MED_WITH_SECONDS: IntlDateTimeFormatOptions;
  static DATETIME_SHORT: IntlDateTimeFormatOptions;
  static DATETIME_SHORT_WITH_SECONDS: IntlDateTimeFormatOptions;
  static DATE_FULL: IntlDateTimeFormatOptions;
  static DATE_HUGE: IntlDateTimeFormatOptions;
  static DATE_MED: IntlDateTimeFormatOptions;
  static DATE_SHORT: IntlDateTimeFormatOptions;
  static TIME_24_SIMPLE: IntlDateTimeFormatOptions;
  static TIME_24_WITH_LONG_OFFSET: IntlDateTimeFormatOptions;
  static TIME_24_WITH_SECONDS: IntlDateTimeFormatOptions;
  static TIME_24_WITH_SHORT_OFFSET: IntlDateTimeFormatOptions;
  static TIME_SIMPLE: IntlDateTimeFormatOptions;
  static TIME_WITH_LONG_OFFSET: IntlDateTimeFormatOptions;
  static TIME_WITH_SECONDS: IntlDateTimeFormatOptions;
  static TIME_WITH_SHORT_OFFSET: IntlDateTimeFormatOptions;
  static local(
    year?: number,
    month?: number,
    day?: number,
    hour?: number,
    minute?: number,
    second?: number,
    millisecond?: number,
  ): DateTime;
  static utc(
    year?: number,
    month?: number,
    day?: number,
    hour?: number,
    minute?: number,
    second?: number,
    millisecond?: number,
  ): DateTime;
  static fromHTTP(text: string, options?: DateTimeFromOptions): DateTime;
  static fromObject(obj: DateTimeFromObjectOptions, options?: DateTimeFromOptions): DateTime;
  static fromISO(text: string, options?: DateTimeFromOptions): DateTime;
  static fromJSDate(date: Date, options?: DateTimeFromOptions): DateTime;
  static fromMillis(millseconds: number, options?: DateTimeFromOptions): DateTime;
  static fromSeconds(seconds: number, options?: DateTimeFromOptions): DateTime;
  static fromRFC2822(text: string, options?: DateTimeFromOptions): DateTime;
  static fromSQL(text: string, options?: DateTimeFromOptions): DateTime;
  static fromFormat(text: string, fmt: string, options?: DateTimeFromOptions): DateTime;
  static fromFormatExplain(
    text: string,
    fmt: string,
    options?: DateTimeFromOptions,
  ): {
    input: string,
    tokens: Array<{
      literal: boolean,
      val: string,
      ...
    }>,
    regex: RegExp,
    rawMatches: ?Array<string>,
    matches: Object,
    result: { [unit: DateTimeUnit]: number, ... },
    zone: ?Zone,
    ...
  };
  static invalid(reason: string): DateTime;
  static max(first: DateTime, ...rest: Array<DateTime>): DateTime;
  static min(first: DateTime, ...rest: Array<DateTime>): DateTime;
  static isDateTime(o: Object): boolean;
  day: number;
  daysInMonth: number;
  daysInYear: number;
  hour: number;
  invalidReason: ?string;
  isInDST: boolean;
  isInLeapYear: boolean;
  isOffsetFixed: boolean;
  isValid: boolean;
  locale: string;
  millisecond: number;
  minute: number;
  month: number;
  monthLong: string;
  monthShort: string;
  numberingSystem: ?string;
  offset: number;
  offsetNameLong: string;
  offsetNameShort: string;
  ordinal: number;
  outputCalendar: ?string;
  second: number;
  weekNumber: number;
  weekYear: number;
  weekday: number;
  weekdayLong: string;
  weekdayShort: string;
  weeksInWeekYear: number;
  year: number;
  zoneName: string;
  diff(
    otherDateTime: DateTime,
    unit?: DateTimeUnit | Array<DateTimeUnit>,
    options?: DateTimeDiffOptions,
  ): Duration;
  diffNow(unit?: DateTimeUnit | Array<DateTimeUnit>, options?: DateTimeDiffOptions): Duration;
  endOf(unit: DateTimeUnit): DateTime;
  equals(other: DateTime): boolean;
  get(unit: DateTimeUnit): number;
  hasSame(other: DateTime, unit: DateTimeUnit): boolean;
  inspect(): string;
  minus(duration: Duration | number | DurationFromObjectOptions): DateTime;
  plus(duration: Duration | number | DurationFromObjectOptions): DateTime;
  reconfigure(options: DateTimeFromOptions): DateTime;
  resolvedLocaleOpts(options?: IntlDateTimeFormatOptions): ResolvedLocaleOptions;
  set(values: { [unit: DateTimeUnit]: number, ... }): DateTime;
  setLocale(locale: string): DateTime;
  setZone(zone: string | Zone, options?: SetZoneOptions): DateTime;
  startOf(unit: DateTimeUnit): DateTime;
  toBSON(): Date;
  toFormat(fmt: string, options?: { round?: ?boolean }): string;
  toHTTP(): string;
  toISO(options?: ToISOOptions): string;
  toISODate(): string;
  toISOTime(options?: ToISOOptions): string;
  toISOWeekDate(): string;
  toJSDate(): Date;
  toLocal(): DateTime;
  toLocaleParts(options?: IntlDateTimeFormatOptions): Array<{
    type: string,
    value: number,
    ...
  }>;
  toLocaleString(options?: IntlDateTimeFormatOptions): string;
  toSeconds(): number;
  toMillis(): number;
  toObject(options: { includeConfig: true }): DateTimeObject & DateTimeConfig;
  toObject(options?: { includeConfig?: ?boolean }): DateTimeObject;
  toRFC2822(): string;
  toSQL(opts?: {
    includeZone?: ?boolean,
    includeOffset?: ?boolean,
  }): string;
  toSQLDate(): string;
  toSQLTime(opts?: {
    includeZone?: ?boolean,
    includeOffset?: ?boolean,
  }): string;
  toString(): string;
  toUTC(offset?: number, options?: SetZoneOptions): DateTime;
  until(other: DateTime): Interval;
  valueOf(): number;
  toRelative(options?: {
    base?: DateTime,
    locale?: string,
    style?: EraLength,
    unit?: RelativeUnit,
    padding?: number,
    round?: boolean,
    numberingSystem?: string,
  }): string;
}

declare module "luxon" {
  //declare export type DateTime = DateTime;
  declare module.exports: {
    DateTime: typeof DateTime,
    Interval: typeof Interval,
    Duration: typeof Duration,
    ...
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'luxon/build/amd/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/cjs-browser/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/es6/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/global/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/global/luxon.min' {
  declare module.exports: any;
}

declare module 'luxon/build/node/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/datetime' {
  declare module.exports: any;
}

declare module 'luxon/src/duration' {
  declare module.exports: any;
}

declare module 'luxon/src/errors' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/conversions' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/diff' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/digits' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/english' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formats' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formatter' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/invalid' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/locale' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/regexParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/tokenParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/util' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/zoneUtil' {
  declare module.exports: any;
}

declare module 'luxon/src/info' {
  declare module.exports: any;
}

declare module 'luxon/src/interval' {
  declare module.exports: any;
}

declare module 'luxon/src/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/settings' {
  declare module.exports: any;
}

declare module 'luxon/src/zone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/fixedOffsetZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/IANAZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/invalidZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/systemZone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'luxon/build/amd/luxon.js' {
  declare module.exports: $Exports<'luxon/build/amd/luxon'>;
}
declare module 'luxon/build/cjs-browser/luxon.js' {
  declare module.exports: $Exports<'luxon/build/cjs-browser/luxon'>;
}
declare module 'luxon/build/es6/luxon.js' {
  declare module.exports: $Exports<'luxon/build/es6/luxon'>;
}
declare module 'luxon/build/global/luxon.js' {
  declare module.exports: $Exports<'luxon/build/global/luxon'>;
}
declare module 'luxon/build/global/luxon.min.js' {
  declare module.exports: $Exports<'luxon/build/global/luxon.min'>;
}
declare module 'luxon/build/node/luxon.js' {
  declare module.exports: $Exports<'luxon/build/node/luxon'>;
}
declare module 'luxon/src/datetime.js' {
  declare module.exports: $Exports<'luxon/src/datetime'>;
}
declare module 'luxon/src/duration.js' {
  declare module.exports: $Exports<'luxon/src/duration'>;
}
declare module 'luxon/src/errors.js' {
  declare module.exports: $Exports<'luxon/src/errors'>;
}
declare module 'luxon/src/impl/conversions.js' {
  declare module.exports: $Exports<'luxon/src/impl/conversions'>;
}
declare module 'luxon/src/impl/diff.js' {
  declare module.exports: $Exports<'luxon/src/impl/diff'>;
}
declare module 'luxon/src/impl/digits.js' {
  declare module.exports: $Exports<'luxon/src/impl/digits'>;
}
declare module 'luxon/src/impl/english.js' {
  declare module.exports: $Exports<'luxon/src/impl/english'>;
}
declare module 'luxon/src/impl/formats.js' {
  declare module.exports: $Exports<'luxon/src/impl/formats'>;
}
declare module 'luxon/src/impl/formatter.js' {
  declare module.exports: $Exports<'luxon/src/impl/formatter'>;
}
declare module 'luxon/src/impl/invalid.js' {
  declare module.exports: $Exports<'luxon/src/impl/invalid'>;
}
declare module 'luxon/src/impl/locale.js' {
  declare module.exports: $Exports<'luxon/src/impl/locale'>;
}
declare module 'luxon/src/impl/regexParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/regexParser'>;
}
declare module 'luxon/src/impl/tokenParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/tokenParser'>;
}
declare module 'luxon/src/impl/util.js' {
  declare module.exports: $Exports<'luxon/src/impl/util'>;
}
declare module 'luxon/src/impl/zoneUtil.js' {
  declare module.exports: $Exports<'luxon/src/impl/zoneUtil'>;
}
declare module 'luxon/src/info.js' {
  declare module.exports: $Exports<'luxon/src/info'>;
}
declare module 'luxon/src/interval.js' {
  declare module.exports: $Exports<'luxon/src/interval'>;
}
declare module 'luxon/src/luxon.js' {
  declare module.exports: $Exports<'luxon/src/luxon'>;
}
declare module 'luxon/src/settings.js' {
  declare module.exports: $Exports<'luxon/src/settings'>;
}
declare module 'luxon/src/zone.js' {
  declare module.exports: $Exports<'luxon/src/zone'>;
}
declare module 'luxon/src/zones/fixedOffsetZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/fixedOffsetZone'>;
}
declare module 'luxon/src/zones/IANAZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/IANAZone'>;
}
declare module 'luxon/src/zones/invalidZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/invalidZone'>;
}
declare module 'luxon/src/zones/systemZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/systemZone'>;
}
