// flow-typed signature: cb1038d50e3ff402ad967cccda7dc5c9
// flow-typed version: <<STUB>>/mailchecker_v^5.0.8/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailchecker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailchecker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailchecker/platform/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailchecker/platform/node/index' {
  declare module.exports: $Exports<'mailchecker/platform/node'>;
}
declare module 'mailchecker/platform/node/index.js' {
  declare module.exports: $Exports<'mailchecker/platform/node'>;
}
