// flow-typed signature: be949cf2e933de3668ac7b8e037737d1
// flow-typed version: <<STUB>>/marked-gfm-heading-id_v4.1.0/flow_v0.244.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked-gfm-heading-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked-gfm-heading-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked-gfm-heading-id/lib/index.umd' {
  declare module.exports: any;
}

declare module 'marked-gfm-heading-id/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked-gfm-heading-id/lib/index.umd.js' {
  declare module.exports: $Exports<'marked-gfm-heading-id/lib/index.umd'>;
}
declare module 'marked-gfm-heading-id/src/index' {
  declare module.exports: $Exports<'marked-gfm-heading-id/src'>;
}
declare module 'marked-gfm-heading-id/src/index.js' {
  declare module.exports: $Exports<'marked-gfm-heading-id/src'>;
}
