// flow-typed signature: 9f4a5ac75c2d7ae4e0b2dfbab5c6a38c
// flow-typed version: <<STUB>>/marked_v4.3.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked' {
  declare type Space = {
    type: 'space',
    raw: string,
  };

  declare type Code = {
    type: 'code',
    raw: string,
    codeBlockStyle?: 'indented' | void,
    lang?: string | void,
    text: string,
    escaped?: boolean,
  };

  declare type Heading = {
    type: 'heading',
    raw: string,
    depth: number,
    text: string,
    tokens: Token[],
  };

  declare type Table = {
    type: 'table',
    raw: string,
    align: Array<'center' | 'left' | 'right' | null>,
    header: TableCell[],
    rows: TableCell[][],
  };

  declare type TableRow = {
    text: string,
  };

  declare type TableCell = {
    text: string,
    tokens: Token[],
    header: boolean,
    align: 'center' | 'left' | 'right' | null,
  };

  declare type Hr = {
    type: 'hr',
    raw: string,
  };

  declare type Blockquote = {
    type: 'blockquote',
    raw: string,
    text: string,
    tokens: Token[],
  };

  declare type List = {
    type: 'list',
    raw: string,
    ordered: boolean,
    start: number | '',
    loose: boolean,
    items: ListItem[],
  };

  declare type ListItem = {
    type: 'list_item',
    raw: string,
    task: boolean,
    checked?: boolean | void,
    loose: boolean,
    text: string,
    tokens: Token[],
  };

  declare type Checkbox = {
    checked: boolean,
  };

  declare type Paragraph = {
    type: 'paragraph',
    raw: string,
    pre?: boolean | void,
    text: string,
    tokens: Token[],
  };

  declare type HTML = {
    type: 'html',
    raw: string,
    pre: boolean,
    text: string,
    block: boolean,
  };

  declare type Text = {
    type: 'text',
    raw: string,
    text: string,
    tokens?: Token[],
  };

  declare type Def = {
    type: 'def',
    raw: string,
    tag: string,
    href: string,
    title: string,
  };

  declare type Escape = {
    type: 'escape',
    raw: string,
    text: string,
  };

  declare type Tag = {
    type: 'text' | 'html',
    raw: string,
    inLink: boolean,
    inRawBlock: boolean,
    text: string,
    block: boolean,
  };

  declare type Link = {
    type: 'link',
    raw: string,
    href: string,
    title?: string | null,
    text: string,
    tokens: Token[],
  };

  declare type Image = {
    type: 'image',
    raw: string,
    href: string,
    title: string | null,
    text: string,
  };

  declare type Strong = {
    type: 'strong',
    raw: string,
    text: string,
    tokens: Token[],
  };

  declare type Em = {
    type: 'em',
    raw: string,
    text: string,
    tokens: Token[],
  };

  declare type Codespan = {
    type: 'codespan',
    raw: string,
    text: string,
  };

  declare type Br = {
    type: 'br',
    raw: string,
  };

  declare type Del = {
    type: 'del',
    raw: string,
    text: string,
    tokens: Token[],
  };

  declare type Generic = {
    [index: string]: any,
    type: string,
    raw: string,
    tokens?: Token[] | void,
  };

  declare type Token =
    | Space
    | Code
    | Heading
    | Table
    | TableRow
    | TableCell
    | Hr
    | Blockquote
    | List
    | ListItem
    | Checkbox
    | Paragraph
    | HTML
    | Text
    | Def
    | Escape
    | Tag
    | Link
    | Image
    | Strong
    | Em
    | Codespan
    | Br
    | Del
    | Generic;

  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked/bin/marked' {
  declare module.exports: any;
}

declare module 'marked/lib/marked.esm' {
  declare module.exports: any;
}

declare module 'marked/lib/marked.umd' {
  declare module.exports: any;
}

declare module 'marked/marked.min' {
  declare module.exports: any;
}

declare module 'marked/src/defaults' {
  declare module.exports: any;
}

declare module 'marked/src/helpers' {
  declare module.exports: any;
}

declare module 'marked/src/Hooks' {
  declare module.exports: any;
}

declare module 'marked/src/Lexer' {
  declare module.exports: any;
}

declare module 'marked/src/marked' {
  declare module.exports: any;
}

declare module 'marked/src/Parser' {
  declare module.exports: any;
}

declare module 'marked/src/Renderer' {
  declare module.exports: any;
}

declare module 'marked/src/rules' {
  declare module.exports: any;
}

declare module 'marked/src/Slugger' {
  declare module.exports: any;
}

declare module 'marked/src/TextRenderer' {
  declare module.exports: any;
}

declare module 'marked/src/Tokenizer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked/bin/marked.js' {
  declare module.exports: $Exports<'marked/bin/marked'>;
}
declare module 'marked/lib/marked.esm.js' {
  declare module.exports: $Exports<'marked/lib/marked.esm'>;
}
declare module 'marked/lib/marked.umd.js' {
  declare module.exports: $Exports<'marked/lib/marked.umd'>;
}
declare module 'marked/marked.min.js' {
  declare module.exports: $Exports<'marked/marked.min'>;
}
declare module 'marked/src/defaults.js' {
  declare module.exports: $Exports<'marked/src/defaults'>;
}
declare module 'marked/src/helpers.js' {
  declare module.exports: $Exports<'marked/src/helpers'>;
}
declare module 'marked/src/Hooks.js' {
  declare module.exports: $Exports<'marked/src/Hooks'>;
}
declare module 'marked/src/Lexer.js' {
  declare module.exports: $Exports<'marked/src/Lexer'>;
}
declare module 'marked/src/marked.js' {
  declare module.exports: $Exports<'marked/src/marked'>;
}
declare module 'marked/src/Parser.js' {
  declare module.exports: $Exports<'marked/src/Parser'>;
}
declare module 'marked/src/Renderer.js' {
  declare module.exports: $Exports<'marked/src/Renderer'>;
}
declare module 'marked/src/rules.js' {
  declare module.exports: $Exports<'marked/src/rules'>;
}
declare module 'marked/src/Slugger.js' {
  declare module.exports: $Exports<'marked/src/Slugger'>;
}
declare module 'marked/src/TextRenderer.js' {
  declare module.exports: $Exports<'marked/src/TextRenderer'>;
}
declare module 'marked/src/Tokenizer.js' {
  declare module.exports: $Exports<'marked/src/Tokenizer'>;
}
