// flow-typed signature: c11423a4fb194998ccc0caaaf32ad2a8
// flow-typed version: <<STUB>>/maskdata_v^1.2.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'maskdata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'maskdata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'maskdata/lib/ExceptionsHandler/BadOption' {
  declare module.exports: any;
}

declare module 'maskdata/lib/helpers/Constants' {
  declare module.exports: any;
}

declare module 'maskdata/lib/helpers/jsonGetSet' {
  declare module.exports: any;
}

declare module 'maskdata/lib/helpers/MaskHelper' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/CardMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/EmailMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/JsonMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/PasswordMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/PhoneMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/StringMask' {
  declare module.exports: any;
}

declare module 'maskdata/lib/maskService/UuidMask' {
  declare module.exports: any;
}

declare module 'maskdata/tests/scribble' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testCard' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testEmail' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testJsonFields' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testJsonGetSet' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testMaskHelper' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testPassword' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testPhone' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testString' {
  declare module.exports: any;
}

declare module 'maskdata/tests/testUuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'maskdata/index' {
  declare module.exports: $Exports<'maskdata'>;
}
declare module 'maskdata/index.js' {
  declare module.exports: $Exports<'maskdata'>;
}
declare module 'maskdata/lib/ExceptionsHandler/BadOption.js' {
  declare module.exports: $Exports<'maskdata/lib/ExceptionsHandler/BadOption'>;
}
declare module 'maskdata/lib/helpers/Constants.js' {
  declare module.exports: $Exports<'maskdata/lib/helpers/Constants'>;
}
declare module 'maskdata/lib/helpers/jsonGetSet.js' {
  declare module.exports: $Exports<'maskdata/lib/helpers/jsonGetSet'>;
}
declare module 'maskdata/lib/helpers/MaskHelper.js' {
  declare module.exports: $Exports<'maskdata/lib/helpers/MaskHelper'>;
}
declare module 'maskdata/lib/maskService/CardMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/CardMask'>;
}
declare module 'maskdata/lib/maskService/EmailMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/EmailMask'>;
}
declare module 'maskdata/lib/maskService/JsonMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/JsonMask'>;
}
declare module 'maskdata/lib/maskService/PasswordMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/PasswordMask'>;
}
declare module 'maskdata/lib/maskService/PhoneMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/PhoneMask'>;
}
declare module 'maskdata/lib/maskService/StringMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/StringMask'>;
}
declare module 'maskdata/lib/maskService/UuidMask.js' {
  declare module.exports: $Exports<'maskdata/lib/maskService/UuidMask'>;
}
declare module 'maskdata/tests/scribble.js' {
  declare module.exports: $Exports<'maskdata/tests/scribble'>;
}
declare module 'maskdata/tests/testCard.js' {
  declare module.exports: $Exports<'maskdata/tests/testCard'>;
}
declare module 'maskdata/tests/testEmail.js' {
  declare module.exports: $Exports<'maskdata/tests/testEmail'>;
}
declare module 'maskdata/tests/testJsonFields.js' {
  declare module.exports: $Exports<'maskdata/tests/testJsonFields'>;
}
declare module 'maskdata/tests/testJsonGetSet.js' {
  declare module.exports: $Exports<'maskdata/tests/testJsonGetSet'>;
}
declare module 'maskdata/tests/testMaskHelper.js' {
  declare module.exports: $Exports<'maskdata/tests/testMaskHelper'>;
}
declare module 'maskdata/tests/testPassword.js' {
  declare module.exports: $Exports<'maskdata/tests/testPassword'>;
}
declare module 'maskdata/tests/testPhone.js' {
  declare module.exports: $Exports<'maskdata/tests/testPhone'>;
}
declare module 'maskdata/tests/testString.js' {
  declare module.exports: $Exports<'maskdata/tests/testString'>;
}
declare module 'maskdata/tests/testUuid.js' {
  declare module.exports: $Exports<'maskdata/tests/testUuid'>;
}
