// flow-typed signature: b770012de902a28706c50a64a8e75c3e
// flow-typed version: <<STUB>>/minio_v^7.0.33/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minio/dist/main/AssumeRoleProvider' {
  declare module.exports: any;
}

declare module 'minio/dist/main/CredentialProvider' {
  declare module.exports: any;
}

declare module 'minio/dist/main/Credentials' {
  declare module.exports: any;
}

declare module 'minio/dist/main/errors' {
  declare module.exports: any;
}

declare module 'minio/dist/main/extensions' {
  declare module.exports: any;
}

declare module 'minio/dist/main/helpers' {
  declare module.exports: any;
}

declare module 'minio/dist/main/minio' {
  declare module.exports: any;
}

declare module 'minio/dist/main/notification' {
  declare module.exports: any;
}

declare module 'minio/dist/main/object-uploader' {
  declare module.exports: any;
}

declare module 'minio/dist/main/s3-endpoints' {
  declare module.exports: any;
}

declare module 'minio/dist/main/signing' {
  declare module.exports: any;
}

declare module 'minio/dist/main/transformers' {
  declare module.exports: any;
}

declare module 'minio/dist/main/xml-parsers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minio/dist/main/AssumeRoleProvider.js' {
  declare module.exports: $Exports<'minio/dist/main/AssumeRoleProvider'>;
}
declare module 'minio/dist/main/CredentialProvider.js' {
  declare module.exports: $Exports<'minio/dist/main/CredentialProvider'>;
}
declare module 'minio/dist/main/Credentials.js' {
  declare module.exports: $Exports<'minio/dist/main/Credentials'>;
}
declare module 'minio/dist/main/errors.js' {
  declare module.exports: $Exports<'minio/dist/main/errors'>;
}
declare module 'minio/dist/main/extensions.js' {
  declare module.exports: $Exports<'minio/dist/main/extensions'>;
}
declare module 'minio/dist/main/helpers.js' {
  declare module.exports: $Exports<'minio/dist/main/helpers'>;
}
declare module 'minio/dist/main/minio.js' {
  declare module.exports: $Exports<'minio/dist/main/minio'>;
}
declare module 'minio/dist/main/notification.js' {
  declare module.exports: $Exports<'minio/dist/main/notification'>;
}
declare module 'minio/dist/main/object-uploader.js' {
  declare module.exports: $Exports<'minio/dist/main/object-uploader'>;
}
declare module 'minio/dist/main/s3-endpoints.js' {
  declare module.exports: $Exports<'minio/dist/main/s3-endpoints'>;
}
declare module 'minio/dist/main/signing.js' {
  declare module.exports: $Exports<'minio/dist/main/signing'>;
}
declare module 'minio/dist/main/transformers.js' {
  declare module.exports: $Exports<'minio/dist/main/transformers'>;
}
declare module 'minio/dist/main/xml-parsers.js' {
  declare module.exports: $Exports<'minio/dist/main/xml-parsers'>;
}
