// flow-typed signature: 5511b3bb5f65511f9ea289160bfa5871
// flow-typed version: <<STUB>>/minisearch_v^6.0.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minisearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minisearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minisearch/dist/es' {
  declare module.exports: any;
}

declare module 'minisearch/dist/es/SearchableMap' {
  declare module.exports: any;
}

declare module 'minisearch/dist/es5m' {
  declare module.exports: any;
}

declare module 'minisearch/dist/es5m/SearchableMap' {
  declare module.exports: any;
}

declare module 'minisearch/dist/umd' {
  declare module.exports: any;
}

declare module 'minisearch/dist/umd/SearchableMap' {
  declare module.exports: any;
}

declare module 'minisearch/src/MiniSearch.test' {
  declare module.exports: any;
}

declare module 'minisearch/src/SearchableMap/SearchableMap.test' {
  declare module.exports: any;
}

declare module 'minisearch/src/testSetup/jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minisearch/dist/es/index' {
  declare module.exports: $Exports<'minisearch/dist/es'>;
}
declare module 'minisearch/dist/es/index.js' {
  declare module.exports: $Exports<'minisearch/dist/es'>;
}
declare module 'minisearch/dist/es/SearchableMap.js' {
  declare module.exports: $Exports<'minisearch/dist/es/SearchableMap'>;
}
declare module 'minisearch/dist/es5m/index' {
  declare module.exports: $Exports<'minisearch/dist/es5m'>;
}
declare module 'minisearch/dist/es5m/index.js' {
  declare module.exports: $Exports<'minisearch/dist/es5m'>;
}
declare module 'minisearch/dist/es5m/SearchableMap.js' {
  declare module.exports: $Exports<'minisearch/dist/es5m/SearchableMap'>;
}
declare module 'minisearch/dist/umd/index' {
  declare module.exports: $Exports<'minisearch/dist/umd'>;
}
declare module 'minisearch/dist/umd/index.js' {
  declare module.exports: $Exports<'minisearch/dist/umd'>;
}
declare module 'minisearch/dist/umd/SearchableMap.js' {
  declare module.exports: $Exports<'minisearch/dist/umd/SearchableMap'>;
}
declare module 'minisearch/src/MiniSearch.test.js' {
  declare module.exports: $Exports<'minisearch/src/MiniSearch.test'>;
}
declare module 'minisearch/src/SearchableMap/SearchableMap.test.js' {
  declare module.exports: $Exports<'minisearch/src/SearchableMap/SearchableMap.test'>;
}
declare module 'minisearch/src/testSetup/jest.js' {
  declare module.exports: $Exports<'minisearch/src/testSetup/jest'>;
}
