// flow-typed signature: c47df5ef7d3600fc21ce5b80abb38dfc
// flow-typed version: <<STUB>>/mocha-prepare_v^0.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-prepare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-prepare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-prepare/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-prepare/index' {
  declare module.exports: $Exports<'mocha-prepare'>;
}
declare module 'mocha-prepare/index.js' {
  declare module.exports: $Exports<'mocha-prepare'>;
}
declare module 'mocha-prepare/test/tests.js' {
  declare module.exports: $Exports<'mocha-prepare/test/tests'>;
}
