// flow-typed signature: 798d9273a2de41db8435592798a06170
// flow-typed version: <<STUB>>/node-redis-pubsub_v^5.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-redis-pubsub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-redis-pubsub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-redis-pubsub/lib/node-redis-pubsub' {
  declare module.exports: any;
}

declare module 'node-redis-pubsub/test/redisQueue.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-redis-pubsub/index' {
  declare module.exports: $Exports<'node-redis-pubsub'>;
}
declare module 'node-redis-pubsub/index.js' {
  declare module.exports: $Exports<'node-redis-pubsub'>;
}
declare module 'node-redis-pubsub/lib/node-redis-pubsub.js' {
  declare module.exports: $Exports<'node-redis-pubsub/lib/node-redis-pubsub'>;
}
declare module 'node-redis-pubsub/test/redisQueue.test.js' {
  declare module.exports: $Exports<'node-redis-pubsub/test/redisQueue.test'>;
}
