// flow-typed signature: 85a4ba14e5e06475a0710390073bb398
// flow-typed version: <<STUB>>/postgres-range_v1.1.3/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postgres-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postgres-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postgres-range/index' {
  declare module.exports: $Exports<'postgres-range'>;
}
declare module 'postgres-range/index.js' {
  declare module.exports: $Exports<'postgres-range'>;
}
