// flow-typed signature: f7c5ed513f6b220715b6bfddf0373cc6
// flow-typed version: <<STUB>>/postgres-array_v^3.0.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postgres-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postgres-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postgres-array/index' {
  declare module.exports: $Exports<'postgres-array'>;
}
declare module 'postgres-array/index.js' {
  declare module.exports: $Exports<'postgres-array'>;
}
