// flow-typed signature: 20cd521a5d43be6d45e6760bcfa53823
// flow-typed version: <<STUB>>/pug_v^3.0.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug/lib' {
  declare module.exports: any;
}

declare module 'pug/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug/lib/index' {
  declare module.exports: $Exports<'pug/lib'>;
}
declare module 'pug/lib/index.js' {
  declare module.exports: $Exports<'pug/lib'>;
}
declare module 'pug/register.js' {
  declare module.exports: $Exports<'pug/register'>;
}
