// flow-typed signature: 00697d23583b37c560b7c8ef3de07c07
// flow-typed version: <<STUB>>/rate-limit-redis_v3.0.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rate-limit-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare type rateLimitRedis$Options = {
  prefix?: string,
  resetExpiryOnChange?: boolean,
  sendCommand: (...args: string[]) => Promise<number> | number
}

declare module 'rate-limit-redis' {
  declare class RedisRateLimiter {
    constructor(options: rateLimitRedis$Options): void,
  }

  declare type rateLimitRedis = {
    RedisStore: typeof RedisRateLimiter,
  }

  declare module.exports: rateLimitRedis;
}
