// flow-typed signature: 290d6c6388b28269aeedd87b100f7243
// flow-typed version: <<STUB>>/raw-body_v^2.4.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raw-body'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raw-body' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'raw-body/index' {
  declare module.exports: $Exports<'raw-body'>;
}
declare module 'raw-body/index.js' {
  declare module.exports: $Exports<'raw-body'>;
}
