// flow-typed signature: 8e974cbfc27517e8e31d9bd3b4d26210
// flow-typed version: <<STUB>>/redis-leader_v0.1.0/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis-leader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redis-leader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redis-leader/index' {
  declare module.exports: $Exports<'redis-leader'>;
}
declare module 'redis-leader/index.js' {
  declare module.exports: $Exports<'redis-leader'>;
}
