// flow-typed signature: 60d921f2ff4ca9c29a7221af4f96f8b9
// flow-typed version: <<STUB>>/request-ip_v^3.3.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-ip/lib' {
  declare module.exports: any;
}

declare module 'request-ip/lib/is' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-ip/lib/index' {
  declare module.exports: $Exports<'request-ip/lib'>;
}
declare module 'request-ip/lib/index.js' {
  declare module.exports: $Exports<'request-ip/lib'>;
}
declare module 'request-ip/lib/is.js' {
  declare module.exports: $Exports<'request-ip/lib/is'>;
}
