// flow-typed signature: aaa4547473f7bcb4fdac6833a27840d8
// flow-typed version: <<STUB>>/sax_v^1.2.4/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sax/lib/sax' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sax/lib/sax.js' {
  declare module.exports: $Exports<'sax/lib/sax'>;
}
