// flow-typed signature: 37eec25013d92fe75a81a47e4c222665
// flow-typed version: <<STUB>>/short-uuid_v^4.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'short-uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'short-uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'short-uuid/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'short-uuid/index' {
  declare module.exports: $Exports<'short-uuid'>;
}
declare module 'short-uuid/index.js' {
  declare module.exports: $Exports<'short-uuid'>;
}
declare module 'short-uuid/test/index' {
  declare module.exports: $Exports<'short-uuid/test'>;
}
declare module 'short-uuid/test/index.js' {
  declare module.exports: $Exports<'short-uuid/test'>;
}
