// flow-typed signature: 9b8f80c6ef80df12a4edc060c787a4c1
// flow-typed version: <<STUB>>/smsapi_v^2.0.6/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smsapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smsapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smsapi/dist' {
  declare module.exports: any;
}

declare module 'smsapi/dist/smsapi.cjs.development' {
  declare module.exports: any;
}

declare module 'smsapi/dist/smsapi.cjs.production.min' {
  declare module.exports: any;
}

declare module 'smsapi/dist/smsapi.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smsapi/dist/index' {
  declare module.exports: $Exports<'smsapi/dist'>;
}
declare module 'smsapi/dist/index.js' {
  declare module.exports: $Exports<'smsapi/dist'>;
}
declare module 'smsapi/dist/smsapi.cjs.development.js' {
  declare module.exports: $Exports<'smsapi/dist/smsapi.cjs.development'>;
}
declare module 'smsapi/dist/smsapi.cjs.production.min.js' {
  declare module.exports: $Exports<'smsapi/dist/smsapi.cjs.production.min'>;
}
declare module 'smsapi/dist/smsapi.esm.js' {
  declare module.exports: $Exports<'smsapi/dist/smsapi.esm'>;
}
