// flow-typed signature: 4ac51ace9ecc824182872c2ee8a94605
// flow-typed version: <<STUB>>/sql-migrations_v^1.0.6/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sql-migrations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sql-migrations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sql-migrations/adapters/mysql' {
  declare module.exports: any;
}

declare module 'sql-migrations/adapters/pg' {
  declare module.exports: any;
}

declare module 'sql-migrations/commands/create-migration-command' {
  declare module.exports: any;
}

declare module 'sql-migrations/commands/rollback-migration-command' {
  declare module.exports: any;
}

declare module 'sql-migrations/commands/run-migrations-command' {
  declare module.exports: any;
}

declare module 'sql-migrations/config' {
  declare module.exports: any;
}

declare module 'sql-migrations/migrate' {
  declare module.exports: any;
}

declare module 'sql-migrations/migration-provider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sql-migrations/adapters/mysql.js' {
  declare module.exports: $Exports<'sql-migrations/adapters/mysql'>;
}
declare module 'sql-migrations/adapters/pg.js' {
  declare module.exports: $Exports<'sql-migrations/adapters/pg'>;
}
declare module 'sql-migrations/commands/create-migration-command.js' {
  declare module.exports: $Exports<'sql-migrations/commands/create-migration-command'>;
}
declare module 'sql-migrations/commands/rollback-migration-command.js' {
  declare module.exports: $Exports<'sql-migrations/commands/rollback-migration-command'>;
}
declare module 'sql-migrations/commands/run-migrations-command.js' {
  declare module.exports: $Exports<'sql-migrations/commands/run-migrations-command'>;
}
declare module 'sql-migrations/config.js' {
  declare module.exports: $Exports<'sql-migrations/config'>;
}
declare module 'sql-migrations/index' {
  declare module.exports: $Exports<'sql-migrations'>;
}
declare module 'sql-migrations/index.js' {
  declare module.exports: $Exports<'sql-migrations'>;
}
declare module 'sql-migrations/migrate.js' {
  declare module.exports: $Exports<'sql-migrations/migrate'>;
}
declare module 'sql-migrations/migration-provider.js' {
  declare module.exports: $Exports<'sql-migrations/migration-provider'>;
}
