// flow-typed signature: 652f56e8cae05d0db17809f6a1ba0b67
// flow-typed version: <<STUB>>/ssh2-sftp-client_v^9.0.4/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssh2-sftp-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssh2-sftp-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssh2-sftp-client/src/constants' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/src' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssh2-sftp-client/src/constants.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/src/constants'>;
}
declare module 'ssh2-sftp-client/src/index' {
  declare module.exports: $Exports<'ssh2-sftp-client/src'>;
}
declare module 'ssh2-sftp-client/src/index.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/src'>;
}
declare module 'ssh2-sftp-client/src/utils.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/src/utils'>;
}
