// flow-typed signature: 4c6d1ab9c6b11dad6043735d6d599a5d
// flow-typed version: <<STUB>>/stream-worker_v^2.0.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-worker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-worker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-worker/stream-worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-worker/stream-worker.js' {
  declare module.exports: $Exports<'stream-worker/stream-worker'>;
}
