// flow-typed signature: e2eb1e2a155784c47eb5131d611ede42
// flow-typed version: <<STUB>>/supertest-session_v^4.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supertest-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supertest-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'supertest-session/test/app' {
  declare module.exports: any;
}

declare module 'supertest-session/test/main_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'supertest-session/index' {
  declare module.exports: $Exports<'supertest-session'>;
}
declare module 'supertest-session/index.js' {
  declare module.exports: $Exports<'supertest-session'>;
}
declare module 'supertest-session/test/app.js' {
  declare module.exports: $Exports<'supertest-session/test/app'>;
}
declare module 'supertest-session/test/main_spec.js' {
  declare module.exports: $Exports<'supertest-session/test/main_spec'>;
}
