// flow-typed signature: b1e1b13d83e3195f9290e22e5d330ec5
// flow-typed version: <<STUB>>/swagger-ui-express_v^4.1.6/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-ui-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-ui-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'swagger-ui-express/index' {
  declare module.exports: $Exports<'swagger-ui-express'>;
}
declare module 'swagger-ui-express/index.js' {
  declare module.exports: $Exports<'swagger-ui-express'>;
}
