// flow-typed signature: fdaaaf25dbb5a1c3dbb933c86ef68537
// flow-typed version: <<STUB>>/tough-cookie_v^4.1.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tough-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tough-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tough-cookie/lib/cookie' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/memstore' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/pathMatch' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/permuteDomain' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/pubsuffix-psl' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/store' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/utilHelper' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/validators' {
  declare module.exports: any;
}

declare module 'tough-cookie/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tough-cookie/lib/cookie.js' {
  declare module.exports: $Exports<'tough-cookie/lib/cookie'>;
}
declare module 'tough-cookie/lib/memstore.js' {
  declare module.exports: $Exports<'tough-cookie/lib/memstore'>;
}
declare module 'tough-cookie/lib/pathMatch.js' {
  declare module.exports: $Exports<'tough-cookie/lib/pathMatch'>;
}
declare module 'tough-cookie/lib/permuteDomain.js' {
  declare module.exports: $Exports<'tough-cookie/lib/permuteDomain'>;
}
declare module 'tough-cookie/lib/pubsuffix-psl.js' {
  declare module.exports: $Exports<'tough-cookie/lib/pubsuffix-psl'>;
}
declare module 'tough-cookie/lib/store.js' {
  declare module.exports: $Exports<'tough-cookie/lib/store'>;
}
declare module 'tough-cookie/lib/utilHelper.js' {
  declare module.exports: $Exports<'tough-cookie/lib/utilHelper'>;
}
declare module 'tough-cookie/lib/validators.js' {
  declare module.exports: $Exports<'tough-cookie/lib/validators'>;
}
declare module 'tough-cookie/lib/version.js' {
  declare module.exports: $Exports<'tough-cookie/lib/version'>;
}
