// flow-typed signature: 8d0b0893078ac74e1b36f7f1ea3da240
// flow-typed version: <<STUB>>/trustly-client_v^3.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trustly-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trustly-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trustly-client/build/main' {
  declare module.exports: any;
}

declare module 'trustly-client/build/main/Interfaces' {
  declare module.exports: any;
}

declare module 'trustly-client/build/main/lib/Client' {
  declare module.exports: any;
}

declare module 'trustly-client/build/main/lib/trustlySerializeData' {
  declare module.exports: any;
}

declare module 'trustly-client/build/main/lib/utils' {
  declare module.exports: any;
}

declare module 'trustly-client/build/main/specs' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module/Interfaces' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module/lib/Client' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module/lib/trustlySerializeData' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module/lib/utils' {
  declare module.exports: any;
}

declare module 'trustly-client/build/module/specs' {
  declare module.exports: any;
}

declare module 'trustly-client/config/exports/build-tests' {
  declare module.exports: any;
}

declare module 'trustly-client/tests/config.dist' {
  declare module.exports: any;
}

declare module 'trustly-client/tests/notification-server/test-notification-server' {
  declare module.exports: any;
}

declare module 'trustly-client/tests/serialization' {
  declare module.exports: any;
}

declare module 'trustly-client/tests/test.deposit' {
  declare module.exports: any;
}

declare module 'trustly-client/tests/test.refund' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trustly-client/build/main/index' {
  declare module.exports: $Exports<'trustly-client/build/main'>;
}
declare module 'trustly-client/build/main/index.js' {
  declare module.exports: $Exports<'trustly-client/build/main'>;
}
declare module 'trustly-client/build/main/Interfaces.js' {
  declare module.exports: $Exports<'trustly-client/build/main/Interfaces'>;
}
declare module 'trustly-client/build/main/lib/Client.js' {
  declare module.exports: $Exports<'trustly-client/build/main/lib/Client'>;
}
declare module 'trustly-client/build/main/lib/trustlySerializeData.js' {
  declare module.exports: $Exports<'trustly-client/build/main/lib/trustlySerializeData'>;
}
declare module 'trustly-client/build/main/lib/utils.js' {
  declare module.exports: $Exports<'trustly-client/build/main/lib/utils'>;
}
declare module 'trustly-client/build/main/specs.js' {
  declare module.exports: $Exports<'trustly-client/build/main/specs'>;
}
declare module 'trustly-client/build/module/index' {
  declare module.exports: $Exports<'trustly-client/build/module'>;
}
declare module 'trustly-client/build/module/index.js' {
  declare module.exports: $Exports<'trustly-client/build/module'>;
}
declare module 'trustly-client/build/module/Interfaces.js' {
  declare module.exports: $Exports<'trustly-client/build/module/Interfaces'>;
}
declare module 'trustly-client/build/module/lib/Client.js' {
  declare module.exports: $Exports<'trustly-client/build/module/lib/Client'>;
}
declare module 'trustly-client/build/module/lib/trustlySerializeData.js' {
  declare module.exports: $Exports<'trustly-client/build/module/lib/trustlySerializeData'>;
}
declare module 'trustly-client/build/module/lib/utils.js' {
  declare module.exports: $Exports<'trustly-client/build/module/lib/utils'>;
}
declare module 'trustly-client/build/module/specs.js' {
  declare module.exports: $Exports<'trustly-client/build/module/specs'>;
}
declare module 'trustly-client/config/exports/build-tests.js' {
  declare module.exports: $Exports<'trustly-client/config/exports/build-tests'>;
}
declare module 'trustly-client/tests/config.dist.js' {
  declare module.exports: $Exports<'trustly-client/tests/config.dist'>;
}
declare module 'trustly-client/tests/notification-server/test-notification-server.js' {
  declare module.exports: $Exports<'trustly-client/tests/notification-server/test-notification-server'>;
}
declare module 'trustly-client/tests/serialization.js' {
  declare module.exports: $Exports<'trustly-client/tests/serialization'>;
}
declare module 'trustly-client/tests/test.deposit.js' {
  declare module.exports: $Exports<'trustly-client/tests/test.deposit'>;
}
declare module 'trustly-client/tests/test.refund.js' {
  declare module.exports: $Exports<'trustly-client/tests/test.refund'>;
}
