// flow-typed signature: 29345567438420037db7c48cc55d19f0
// flow-typed version: <<STUB>>/tweetnacl-util_v^0.15.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tweetnacl-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tweetnacl-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tweetnacl-util/nacl-util' {
  declare module.exports: any;
}

declare module 'tweetnacl-util/nacl-util.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tweetnacl-util/nacl-util.js' {
  declare module.exports: $Exports<'tweetnacl-util/nacl-util'>;
}
declare module 'tweetnacl-util/nacl-util.min.js' {
  declare module.exports: $Exports<'tweetnacl-util/nacl-util.min'>;
}
