// flow-typed signature: 65d566fdb56c675d8fb05eed1e9a4792
// flow-typed version: <<STUB>>/twitter_cldr_v^2.3.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twitter_cldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twitter_cldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twitter_cldr/full/af' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ar' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/be' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/bg' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/bn' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ca' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/core' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/cs' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/cy' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/da' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/de-CH' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/de' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/el' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-150' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-AU' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-CA' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-GB' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-IE' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-SG' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en-ZA' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/en' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/es-419' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/es-CO' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/es-MX' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/es-US' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/es' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/eu' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fa' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fi' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fil' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fr-BE' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fr-CA' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fr-CH' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/fr' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ga' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/gl' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/he' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/hi' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/hr' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/hu' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/id' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/is' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/it-CH' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/it' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ja' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ko' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/lv' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/msa' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/nl' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/no' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/pl' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/pt' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ro' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ru' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/sk' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/sq' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/sr' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/sv' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ta' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/th' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/tr' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/uk' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/ur' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/vi' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/zh-cn' {
  declare module.exports: any;
}

declare module 'twitter_cldr/full/zh-tw' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/af.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ar.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/be.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/bg.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/bn.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ca.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/core.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/cs.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/cy.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/da.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/de-CH.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/de.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/el.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-150.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-AU.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-CA.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-GB.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-IE.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-SG.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en-ZA.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/en.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/es-419.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/es-CO.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/es-MX.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/es-US.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/es.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/eu.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fa.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fi.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fil.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fr-BE.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fr-CA.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fr-CH.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/fr.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ga.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/gl.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/he.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/hi.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/hr.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/hu.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/id.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/is.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/it-CH.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/it.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ja.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ko.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/lv.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/msa.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/nl.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/no.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/pl.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/pt.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ro.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ru.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/sk.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/sq.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/sr.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/sv.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ta.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/th.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/tr.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/uk.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/ur.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/vi.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/zh-cn.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/min/zh-tw.min' {
  declare module.exports: any;
}

declare module 'twitter_cldr/twitter_cldr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twitter_cldr/full/af.js' {
  declare module.exports: $Exports<'twitter_cldr/full/af'>;
}
declare module 'twitter_cldr/full/ar.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ar'>;
}
declare module 'twitter_cldr/full/be.js' {
  declare module.exports: $Exports<'twitter_cldr/full/be'>;
}
declare module 'twitter_cldr/full/bg.js' {
  declare module.exports: $Exports<'twitter_cldr/full/bg'>;
}
declare module 'twitter_cldr/full/bn.js' {
  declare module.exports: $Exports<'twitter_cldr/full/bn'>;
}
declare module 'twitter_cldr/full/ca.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ca'>;
}
declare module 'twitter_cldr/full/core.js' {
  declare module.exports: $Exports<'twitter_cldr/full/core'>;
}
declare module 'twitter_cldr/full/cs.js' {
  declare module.exports: $Exports<'twitter_cldr/full/cs'>;
}
declare module 'twitter_cldr/full/cy.js' {
  declare module.exports: $Exports<'twitter_cldr/full/cy'>;
}
declare module 'twitter_cldr/full/da.js' {
  declare module.exports: $Exports<'twitter_cldr/full/da'>;
}
declare module 'twitter_cldr/full/de-CH.js' {
  declare module.exports: $Exports<'twitter_cldr/full/de-CH'>;
}
declare module 'twitter_cldr/full/de.js' {
  declare module.exports: $Exports<'twitter_cldr/full/de'>;
}
declare module 'twitter_cldr/full/el.js' {
  declare module.exports: $Exports<'twitter_cldr/full/el'>;
}
declare module 'twitter_cldr/full/en-150.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-150'>;
}
declare module 'twitter_cldr/full/en-AU.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-AU'>;
}
declare module 'twitter_cldr/full/en-CA.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-CA'>;
}
declare module 'twitter_cldr/full/en-GB.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-GB'>;
}
declare module 'twitter_cldr/full/en-IE.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-IE'>;
}
declare module 'twitter_cldr/full/en-SG.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-SG'>;
}
declare module 'twitter_cldr/full/en-ZA.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en-ZA'>;
}
declare module 'twitter_cldr/full/en.js' {
  declare module.exports: $Exports<'twitter_cldr/full/en'>;
}
declare module 'twitter_cldr/full/es-419.js' {
  declare module.exports: $Exports<'twitter_cldr/full/es-419'>;
}
declare module 'twitter_cldr/full/es-CO.js' {
  declare module.exports: $Exports<'twitter_cldr/full/es-CO'>;
}
declare module 'twitter_cldr/full/es-MX.js' {
  declare module.exports: $Exports<'twitter_cldr/full/es-MX'>;
}
declare module 'twitter_cldr/full/es-US.js' {
  declare module.exports: $Exports<'twitter_cldr/full/es-US'>;
}
declare module 'twitter_cldr/full/es.js' {
  declare module.exports: $Exports<'twitter_cldr/full/es'>;
}
declare module 'twitter_cldr/full/eu.js' {
  declare module.exports: $Exports<'twitter_cldr/full/eu'>;
}
declare module 'twitter_cldr/full/fa.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fa'>;
}
declare module 'twitter_cldr/full/fi.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fi'>;
}
declare module 'twitter_cldr/full/fil.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fil'>;
}
declare module 'twitter_cldr/full/fr-BE.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fr-BE'>;
}
declare module 'twitter_cldr/full/fr-CA.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fr-CA'>;
}
declare module 'twitter_cldr/full/fr-CH.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fr-CH'>;
}
declare module 'twitter_cldr/full/fr.js' {
  declare module.exports: $Exports<'twitter_cldr/full/fr'>;
}
declare module 'twitter_cldr/full/ga.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ga'>;
}
declare module 'twitter_cldr/full/gl.js' {
  declare module.exports: $Exports<'twitter_cldr/full/gl'>;
}
declare module 'twitter_cldr/full/he.js' {
  declare module.exports: $Exports<'twitter_cldr/full/he'>;
}
declare module 'twitter_cldr/full/hi.js' {
  declare module.exports: $Exports<'twitter_cldr/full/hi'>;
}
declare module 'twitter_cldr/full/hr.js' {
  declare module.exports: $Exports<'twitter_cldr/full/hr'>;
}
declare module 'twitter_cldr/full/hu.js' {
  declare module.exports: $Exports<'twitter_cldr/full/hu'>;
}
declare module 'twitter_cldr/full/id.js' {
  declare module.exports: $Exports<'twitter_cldr/full/id'>;
}
declare module 'twitter_cldr/full/is.js' {
  declare module.exports: $Exports<'twitter_cldr/full/is'>;
}
declare module 'twitter_cldr/full/it-CH.js' {
  declare module.exports: $Exports<'twitter_cldr/full/it-CH'>;
}
declare module 'twitter_cldr/full/it.js' {
  declare module.exports: $Exports<'twitter_cldr/full/it'>;
}
declare module 'twitter_cldr/full/ja.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ja'>;
}
declare module 'twitter_cldr/full/ko.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ko'>;
}
declare module 'twitter_cldr/full/lv.js' {
  declare module.exports: $Exports<'twitter_cldr/full/lv'>;
}
declare module 'twitter_cldr/full/msa.js' {
  declare module.exports: $Exports<'twitter_cldr/full/msa'>;
}
declare module 'twitter_cldr/full/nl.js' {
  declare module.exports: $Exports<'twitter_cldr/full/nl'>;
}
declare module 'twitter_cldr/full/no.js' {
  declare module.exports: $Exports<'twitter_cldr/full/no'>;
}
declare module 'twitter_cldr/full/pl.js' {
  declare module.exports: $Exports<'twitter_cldr/full/pl'>;
}
declare module 'twitter_cldr/full/pt.js' {
  declare module.exports: $Exports<'twitter_cldr/full/pt'>;
}
declare module 'twitter_cldr/full/ro.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ro'>;
}
declare module 'twitter_cldr/full/ru.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ru'>;
}
declare module 'twitter_cldr/full/sk.js' {
  declare module.exports: $Exports<'twitter_cldr/full/sk'>;
}
declare module 'twitter_cldr/full/sq.js' {
  declare module.exports: $Exports<'twitter_cldr/full/sq'>;
}
declare module 'twitter_cldr/full/sr.js' {
  declare module.exports: $Exports<'twitter_cldr/full/sr'>;
}
declare module 'twitter_cldr/full/sv.js' {
  declare module.exports: $Exports<'twitter_cldr/full/sv'>;
}
declare module 'twitter_cldr/full/ta.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ta'>;
}
declare module 'twitter_cldr/full/th.js' {
  declare module.exports: $Exports<'twitter_cldr/full/th'>;
}
declare module 'twitter_cldr/full/tr.js' {
  declare module.exports: $Exports<'twitter_cldr/full/tr'>;
}
declare module 'twitter_cldr/full/uk.js' {
  declare module.exports: $Exports<'twitter_cldr/full/uk'>;
}
declare module 'twitter_cldr/full/ur.js' {
  declare module.exports: $Exports<'twitter_cldr/full/ur'>;
}
declare module 'twitter_cldr/full/vi.js' {
  declare module.exports: $Exports<'twitter_cldr/full/vi'>;
}
declare module 'twitter_cldr/full/zh-cn.js' {
  declare module.exports: $Exports<'twitter_cldr/full/zh-cn'>;
}
declare module 'twitter_cldr/full/zh-tw.js' {
  declare module.exports: $Exports<'twitter_cldr/full/zh-tw'>;
}
declare module 'twitter_cldr/min/af.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/af.min'>;
}
declare module 'twitter_cldr/min/ar.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ar.min'>;
}
declare module 'twitter_cldr/min/be.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/be.min'>;
}
declare module 'twitter_cldr/min/bg.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/bg.min'>;
}
declare module 'twitter_cldr/min/bn.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/bn.min'>;
}
declare module 'twitter_cldr/min/ca.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ca.min'>;
}
declare module 'twitter_cldr/min/core.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/core.min'>;
}
declare module 'twitter_cldr/min/cs.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/cs.min'>;
}
declare module 'twitter_cldr/min/cy.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/cy.min'>;
}
declare module 'twitter_cldr/min/da.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/da.min'>;
}
declare module 'twitter_cldr/min/de-CH.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/de-CH.min'>;
}
declare module 'twitter_cldr/min/de.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/de.min'>;
}
declare module 'twitter_cldr/min/el.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/el.min'>;
}
declare module 'twitter_cldr/min/en-150.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-150.min'>;
}
declare module 'twitter_cldr/min/en-AU.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-AU.min'>;
}
declare module 'twitter_cldr/min/en-CA.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-CA.min'>;
}
declare module 'twitter_cldr/min/en-GB.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-GB.min'>;
}
declare module 'twitter_cldr/min/en-IE.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-IE.min'>;
}
declare module 'twitter_cldr/min/en-SG.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-SG.min'>;
}
declare module 'twitter_cldr/min/en-ZA.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en-ZA.min'>;
}
declare module 'twitter_cldr/min/en.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/en.min'>;
}
declare module 'twitter_cldr/min/es-419.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/es-419.min'>;
}
declare module 'twitter_cldr/min/es-CO.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/es-CO.min'>;
}
declare module 'twitter_cldr/min/es-MX.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/es-MX.min'>;
}
declare module 'twitter_cldr/min/es-US.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/es-US.min'>;
}
declare module 'twitter_cldr/min/es.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/es.min'>;
}
declare module 'twitter_cldr/min/eu.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/eu.min'>;
}
declare module 'twitter_cldr/min/fa.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fa.min'>;
}
declare module 'twitter_cldr/min/fi.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fi.min'>;
}
declare module 'twitter_cldr/min/fil.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fil.min'>;
}
declare module 'twitter_cldr/min/fr-BE.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fr-BE.min'>;
}
declare module 'twitter_cldr/min/fr-CA.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fr-CA.min'>;
}
declare module 'twitter_cldr/min/fr-CH.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fr-CH.min'>;
}
declare module 'twitter_cldr/min/fr.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/fr.min'>;
}
declare module 'twitter_cldr/min/ga.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ga.min'>;
}
declare module 'twitter_cldr/min/gl.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/gl.min'>;
}
declare module 'twitter_cldr/min/he.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/he.min'>;
}
declare module 'twitter_cldr/min/hi.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/hi.min'>;
}
declare module 'twitter_cldr/min/hr.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/hr.min'>;
}
declare module 'twitter_cldr/min/hu.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/hu.min'>;
}
declare module 'twitter_cldr/min/id.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/id.min'>;
}
declare module 'twitter_cldr/min/is.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/is.min'>;
}
declare module 'twitter_cldr/min/it-CH.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/it-CH.min'>;
}
declare module 'twitter_cldr/min/it.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/it.min'>;
}
declare module 'twitter_cldr/min/ja.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ja.min'>;
}
declare module 'twitter_cldr/min/ko.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ko.min'>;
}
declare module 'twitter_cldr/min/lv.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/lv.min'>;
}
declare module 'twitter_cldr/min/msa.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/msa.min'>;
}
declare module 'twitter_cldr/min/nl.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/nl.min'>;
}
declare module 'twitter_cldr/min/no.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/no.min'>;
}
declare module 'twitter_cldr/min/pl.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/pl.min'>;
}
declare module 'twitter_cldr/min/pt.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/pt.min'>;
}
declare module 'twitter_cldr/min/ro.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ro.min'>;
}
declare module 'twitter_cldr/min/ru.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ru.min'>;
}
declare module 'twitter_cldr/min/sk.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/sk.min'>;
}
declare module 'twitter_cldr/min/sq.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/sq.min'>;
}
declare module 'twitter_cldr/min/sr.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/sr.min'>;
}
declare module 'twitter_cldr/min/sv.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/sv.min'>;
}
declare module 'twitter_cldr/min/ta.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ta.min'>;
}
declare module 'twitter_cldr/min/th.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/th.min'>;
}
declare module 'twitter_cldr/min/tr.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/tr.min'>;
}
declare module 'twitter_cldr/min/uk.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/uk.min'>;
}
declare module 'twitter_cldr/min/ur.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/ur.min'>;
}
declare module 'twitter_cldr/min/vi.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/vi.min'>;
}
declare module 'twitter_cldr/min/zh-cn.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/zh-cn.min'>;
}
declare module 'twitter_cldr/min/zh-tw.min.js' {
  declare module.exports: $Exports<'twitter_cldr/min/zh-tw.min'>;
}
declare module 'twitter_cldr/twitter_cldr.js' {
  declare module.exports: $Exports<'twitter_cldr/twitter_cldr'>;
}
