// flow-typed signature: be9972387ce819ff85a21f288d55c5bb
// flow-typed version: <<STUB>>/weighted_v^1.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'weighted'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'weighted' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'weighted/bench/weighted' {
  declare module.exports: any;
}

declare module 'weighted/examples/simple' {
  declare module.exports: any;
}

declare module 'weighted/lib/weighted' {
  declare module.exports: any;
}

declare module 'weighted/test/weighted' {
  declare module.exports: any;
}

// Filename aliases
declare module 'weighted/bench/weighted.js' {
  declare module.exports: $Exports<'weighted/bench/weighted'>;
}
declare module 'weighted/examples/simple.js' {
  declare module.exports: $Exports<'weighted/examples/simple'>;
}
declare module 'weighted/index' {
  declare module.exports: $Exports<'weighted'>;
}
declare module 'weighted/index.js' {
  declare module.exports: $Exports<'weighted'>;
}
declare module 'weighted/lib/weighted.js' {
  declare module.exports: $Exports<'weighted/lib/weighted'>;
}
declare module 'weighted/test/weighted.js' {
  declare module.exports: $Exports<'weighted/test/weighted'>;
}
