// flow-typed signature: 26798b3a8d0ad5a691e7560b18de409c
// flow-typed version: <<STUB>>/winston-loki_v^6.0.6/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-loki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-loki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-loki/src/batcher' {
  declare module.exports: any;
}

declare module 'winston-loki/src/proto/helpers' {
  declare module.exports: any;
}

declare module 'winston-loki/src/proto' {
  declare module.exports: any;
}

declare module 'winston-loki/src/requests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-loki/index' {
  declare module.exports: $Exports<'winston-loki'>;
}
declare module 'winston-loki/index.js' {
  declare module.exports: $Exports<'winston-loki'>;
}
declare module 'winston-loki/src/batcher.js' {
  declare module.exports: $Exports<'winston-loki/src/batcher'>;
}
declare module 'winston-loki/src/proto/helpers.js' {
  declare module.exports: $Exports<'winston-loki/src/proto/helpers'>;
}
declare module 'winston-loki/src/proto/index' {
  declare module.exports: $Exports<'winston-loki/src/proto'>;
}
declare module 'winston-loki/src/proto/index.js' {
  declare module.exports: $Exports<'winston-loki/src/proto'>;
}
declare module 'winston-loki/src/requests.js' {
  declare module.exports: $Exports<'winston-loki/src/requests'>;
}
