version: '3'

services:
  gstech-minio:
    build:
      context: .
      dockerfile: Dockerfile
    image: gstech-minio
    container_name: gstech-minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /export
    networks:
      - gstech

networks:
  gstech:
    external: true
