# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "cos" {
    bucket  = "waysun-dev-1307473405"
    encrypt = true
    key     = "tke/terraform.tfstate"
    prefix  = "terraform/state"
    region  = "eu-frankfurt"
  }
}
