# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('orig_commission', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01, 'Minimal value is 0.01 percent.'), django.core.validators.MaxValueValidator(99.99, 'Maximal value is 99.99 percent.')], verbose_name='Originator commission percent')),
                ('user_commission', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01, 'Minimal value is 0.01 percent.'), django.core.validators.MaxValueValidator(99.99, 'Maximal value is 99.99 percent.')], verbose_name='User commission percent')),
                ('rm_commission', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01, 'Minimal value is 0.01 percent.'), django.core.validators.MaxValueValidator(99.99, 'Maximal value is 99.99 percent.')], verbose_name='RewardMatrix commission percent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('INO', 'Reward Points - Origin'), ('INC', 'Reward Points'), ('INI', 'Wallet initialization'), ('INR', 'Reward Points - Origin Commission'), ('CMO', 'Commission - Origin'), ('CMC', 'Commission - Reward Points'), ('CMR', 'Commission - Reward Matrix'), ('BPR', 'Product - Buy'), ('SPR', 'Product - Sell')], db_index=True, max_length=3)),
                ('src_transaction_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('src_title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=11)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=11)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_lines', to='wallet.Wallet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='walletline',
            unique_together=set([('wallet', 'operation_date', 'id'), ('wallet', 'partner', 'src_transaction_id', 'operation_type')]),
        ),
        migrations.AlterIndexTogether(
            name='walletline',
            index_together=set([('wallet', 'src_title'), ('wallet', 'partner', 'src_transaction_id'), ('wallet', 'operation_type'), ('wallet', 'src_transaction_id'), ('wallet', 'partner')]),
        ),
        migrations.AlterIndexTogether(
            name='wallet',
            index_together=set([('user', 'is_default')]),
        ),
        migrations.AlterUniqueTogether(
            name='commissionconfig',
            unique_together=set([('user', 'tier')]),
        ),
    ]
