# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionconfig',
            name='user_commission',
        ),
        migrations.AlterField(
            model_name='walletline',
            name='operation_type',
            field=models.CharField(choices=[('INI', 'Wallet initialization'), ('INC', 'Reward Points'), ('INO', 'Reward Points - Origin'), ('INR', 'Reward Points - Origin Commission'), ('INS', 'Reward Points - Sell Commission'), ('CMC', 'Commission - Reward Points'), ('CMO', 'Commission - Origin'), ('CMR', 'Commission - Reward Matrix'), ('BPR', 'Product - Buy'), ('SPR', 'Product - Sell')], db_index=True, max_length=3),
        ),
    ]
