# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20161020_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='is_default',
            new_name='_is_default',
        ),
        migrations.AddField(
            model_name='wallet',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='operation_type',
            field=models.CharField(choices=[('INI', 'Wallet initialization'), ('INC', 'Reward Points'), ('INO', 'Reward Points - Origin'), ('INR', 'Reward Points - Origin Commission'), ('INS', 'Reward Points - Sell Commission'), ('CMC', 'Commission - Reward Points'), ('CMO', 'Commission - Origin'), ('CMR', 'Commission - Reward Matrix'), ('CMX', 'Commission - Reward Matrix - Sell'), ('BPR', 'Product - Buy'), ('SPR', 'Product - Sell'), ('MCR', 'Manual correction')], db_index=True, max_length=3),
        ),
        migrations.AlterIndexTogether(
            name='wallet',
            index_together=set([('user', '_is_default')]),
        ),
    ]
