# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20171211_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='balance_after',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='balance_before',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=20),
        ),
    ]
