# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 13:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20171219_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionconfig',
            name='orig_commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Minimal value is 0 percent.'), django.core.validators.MaxValueValidator(99.99, 'Maximal value is 99.99 percent.')], verbose_name='Originator commission percent'),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='rm_commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Minimal value is 0 percent.'), django.core.validators.MaxValueValidator(99.99, 'Maximal value is 99.99 percent.')], verbose_name='RewardMatrix commission percent'),
        ),
    ]
