# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_auto_20180117_1351'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='walletline',
            index_together=set([('wallet', 'operation_date', 'operation_type', 'amount', 'partner'), ('wallet', 'operation_type'), ('wallet', 'partner'), ('wallet', 'src_transaction_id'), ('wallet', 'partner', 'src_transaction_id'), ('wallet', 'src_title')]),
        ),
    ]
