# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20180509_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentChargeTokenChaneyPaymentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=36)),
                ('wallet_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.WalletLine')),
            ],
        ),
    ]
