# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_silentchargetokenchaneypaymentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentchargetokenchaneypaymentsmodel',
            name='channel',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='silentchargetokenchaneypaymentsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
