# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20180711_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentchargetokenchaneypaymentsmodel',
            name='external_user_id',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
