# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-01 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0009_silentchargetokenchaneypaymentsmodel_external_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletline',
            name='operation_subtype',
            field=models.CharField(choices=[('STD', 'Standard Reward Points'), ('BNS', 'Bonus Reward Points'), ('SLN', 'Silent line'), ('MCR', 'Manual correction')], db_index=True, default='STD', max_length=3),
        ),
        migrations.AlterIndexTogether(
            name='walletline',
            index_together=set([('wallet', 'operation_type', 'operation_subtype'), ('wallet', 'partner'), ('wallet', 'src_title'), ('wallet', 'operation_date', 'operation_type', 'operation_subtype', 'amount', 'partner'), ('wallet', 'partner', 'src_transaction_id'), ('wallet', 'src_transaction_id')]),
        ),
    ]
