# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20181103_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletline',
            name='operation_subtype',
            field=models.CharField(choices=[('STD', 'Standard Reward Points'), ('BRP', 'Bonus Referral Reward - Parent'), ('BRC', 'Bonus Referral Reward - Child'), ('BNS', 'Bonus Referral Reward - Obsolete'), ('BPG', 'Bonus Reward Points - General'), ('SLN', 'Silent line'), ('VSP', 'VirtualShop payment'), ('MCR', 'Manual correction')], db_index=True, default='STD', max_length=3),
        ),
    ]
