# Generated by Django 2.1.7 on 2019-03-20 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20190109_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentchargetokenchaneypaymentsmodel',
            name='wallet_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.WalletLine'),
        ),
        migrations.AlterField(
            model_name='walletline',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
