# Generated by Django 2.1.10 on 2019-10-18 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0013_auto_20190320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletline',
            name='src_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='walletline',
            unique_together={('wallet', 'partner', 'src_transaction_id', 'operation_type')},
        ),
        migrations.AlterIndexTogether(
            name='walletline',
            index_together=set(),
        ),
    ]
