# Generated by Django 2.1.10 on 2020-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20191018_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletline',
            name='src_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
