# Generated by Django 3.1 on 2020-09-18 12:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("virtual_store", "0003_auto_20200918_1108"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "payment_type",
                    models.CharField(choices=[("CM", "China Mobile"), ("DEF", "Default")], default="CM", max_length=12),
                ),
                ("payment_configuration", models.JSONField()),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_payment_configuration_set",
                        to="virtual_store.partner",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(related_name="payment_configuration_set", to="virtual_store.Product"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChinaMobilePayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("ext_product_id", models.CharField(max_length=30)),
                ("ext_content_id", models.CharField(max_length=30)),
                ("ext_order_type", models.PositiveIntegerField()),
                ("ext_commit", models.CharField(max_length=30)),
                ("ext_auto_sub", models.CharField(max_length=10)),
                (
                    "payment_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="china_mobile_set",
                        to="payment_gateway.paymentconfiguration",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_china_mobile_set",
                        to="virtual_store.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
