# Generated by Django 3.1.1 on 2020-10-16 13:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import payment_gateway.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_store", "0008_auto_20201016_1346"),
        ("payment_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChinaMobilePaymentConfigurationModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "success_url_text",
                    models.TextField(blank=True, help_text="Newline separated list of allowed redirections"),
                ),
                (
                    "error_url_text",
                    models.TextField(blank=True, help_text="Newline separated list of allowed redirections"),
                ),
                (
                    "ext_cp_id",
                    models.CharField(
                        help_text="CM Content Provider ID",
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                    ),
                ),
                ("ext_back_url", models.URLField(help_text="CM Notifications and back url", max_length=2000)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="virtual_store.currency"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChinaMobileProductPaymentModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("ext_product_id", models.CharField(max_length=30)),
                ("ext_product_name", models.CharField(blank=True, max_length=150)),
                ("ext_amount", models.CharField(blank=True, max_length=20)),
                ("ext_description", models.CharField(blank=True, max_length=150)),
                ("ext_content_id", models.CharField(max_length=30)),
                ("ext_content_name", models.CharField(blank=True, max_length=150)),
                ("ext_order_type", models.CharField(max_length=1)),
                ("ext_commit", models.CharField(max_length=200)),
                ("ext_auto_sub", models.CharField(max_length=1)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="virtual_store.partner"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentConfigurationModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("CM", "China Mobile - IFrame type")], db_index=True, default="CM", max_length=12
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_payment_configuration_set",
                        to="virtual_store.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiptLogModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiptModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("payment_id", models.CharField(default=payment_gateway.models._generate_payment_id, max_length=32)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("DECLINED", "Declined"),
                            ("MANUAL_VERIFICATION_REQUIRED", "Manual Verification Required"),
                        ],
                        default="PENDING",
                        max_length=28,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts_set",
                        to="virtual_store.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="product",
        ),
        migrations.DeleteModel(
            name="ChinaMobilePayment",
        ),
        migrations.DeleteModel(
            name="PaymentConfiguration",
        ),
        migrations.AddField(
            model_name="receiptlogmodel",
            name="receipt",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="payment_gateway.receiptmodel"),
        ),
        migrations.AddField(
            model_name="chinamobileproductpaymentmodel",
            name="payment_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="payment_gateway.paymentconfigurationmodel",
            ),
        ),
        migrations.AddField(
            model_name="chinamobileproductpaymentmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="virtual_store.product"
            ),
        ),
        migrations.AddField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="payment_configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_cm_config",
                to="payment_gateway.paymentconfigurationmodel",
            ),
        ),
    ]
