# Generated by Django 3.1.1 on 2020-10-16 14:10

from django.db import migrations, models

import payment_gateway.models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0002_auto_20201016_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptmodel",
            name="payment_id",
            field=models.CharField(
                default=payment_gateway.models._generate_payment_id,
                help_text="external ID used to communicate with payment provider",
                max_length=32,
            ),
        ),
    ]
