# Generated by Django 3.1.1 on 2020-10-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0008_auto_20201016_1346"),
        ("payment_gateway", "0003_auto_20201016_1410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="currency",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="virtual_store.currency"
            ),
        ),
    ]
