# Generated by Django 3.1.1 on 2020-10-21 13:58

from django.db import migrations, models

import payment_gateway.models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0004_auto_20201016_1417"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="currency",
        ),
        migrations.AddField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="ext_payment_url",
            field=models.URLField(
                default="http://change_me.local", help_text="CM Payment Gateway URL", max_length=2000
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="redirect_failure_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="redirect_on_callback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="redirect_success_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="receiptmodel",
            name="payment_id",
            field=models.CharField(
                db_index=True,
                default=payment_gateway.models._generate_payment_id,
                help_text="external ID used to communicate with payment provider",
                max_length=32,
            ),
        ),
    ]
