# Generated by Django 3.1.1 on 2020-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0005_auto_20201021_1358"),
    ]

    operations = [
        migrations.AddField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="_ext_app_secret",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="ext_app_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="receipt_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
