# Generated by Django 3.1.2 on 2020-11-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0006_auto_20201021_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="chinamobilepaymentconfigurationmodel",
            name="cm_proxy_url",
            field=models.URLField(blank=True, help_text="China Mobile proxy used as a gateway to outside internet."),
        ),
    ]
