# Generated by Django 3.1.2 on 2020-12-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0007_chinamobilepaymentconfigurationmodel_cm_proxy_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chinamobileproductpaymentmodel", old_name="ext_content_id", new_name="_ext_content_id"
        ),
        migrations.AddField(
            model_name="chinamobileproductpaymentmodel",
            name="randomize_ext_content_id",
            field=models.BooleanField(default=False),
        ),
    ]
