# Generated by Django 3.1.4 on 2021-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0008_auto_20201213_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chinamobileproductpaymentmodel",
            name="_ext_content_id",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
