# Generated by Django 3.1.4 on 2021-03-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0009_auto_20210316_1249"),
        ("payment_gateway", "0009_auto_20210322_2115"),
    ]

    operations = []
