phoenix {
  bets {
    domain {
      maximum-allowed-stake-amount = 500
    }
    projections {
      bet-lifecycle.name = "bets-for-bet-lifecycle"
      read-side-view.name = "bets-for-read-side-view"
      punter-bets-history.name = "bets-for-punter-bets-history"
      market-lifecycle.name = "bets-for-market-lifecycle"
    }
  }
}
