dge {
  sftp {
    host = "localhost"
    host = ${?PHOENIX_DGE_SFTP_HOST}

    port = 2222
    port = ${?PHOENIX_DGE_SFTP_PORT}

    user = "backend"
    user = ${?PHOENIX_DGE_SFTP_USER}

    password = "backend"
    password = ${?PHOENIX_DGE_SFTP_PASSWORD}

    root-directory = "phoenix"
    root-directory = ${?PHOENIX_DGE_SFTP_ROOT_DIRECTORY}
  }
}