phoenix.idcomply {

  api-key = "[i-should-be-set-from-env]"
  api-key = ${?ID_COMPLY_API_KEY}
  base-url = "[i-should-be-set-from-env]"
  base-url = ${?ID_COMPLY_BASE_URL}

  //  IDPV endpoint is passed inside the request body (unlike KYC, KBA)
  idpv-endpoint = "[i-should-be-set-from-env]"
  idpv-endpoint = ${?ID_COMPLY_ENDPOINT_PATH_IDPV}

  photo-verification-base-url = "[i-should-be-set-from-env]"
  photo-verification-base-url = ${?ID_COMPLY_PHOTO_VERIFICATION_BASE_URL}
  front-end-redirection-endpoint = "[i-should-be-set-from-env]"
  front-end-redirection-endpoint = ${?ID_COMPLY_FRONT_END_REDIRECTION_ENDPOINT}

  endpoint-paths {
    id-photo-verification-token = ${phoenix.idcomply.base-url}"/tokens"
    id-photo-verification-token-status = ${phoenix.idcomply.base-url}"/token/tokenId/status"
    knowledge-based-authentication = ${phoenix.idcomply.base-url}"/i-should-be-set-from-env"
    knowledge-based-authentication = ${phoenix.idcomply.base-url}${?ID_COMPLY_ENDPOINT_PATH_KBA}
    know-your-customer = ${phoenix.idcomply.base-url}"/i-should-be-set-from-env"
    know-your-customer = ${phoenix.idcomply.base-url}${?ID_COMPLY_ENDPOINT_PATH_KYC}
  }
}
