keycloak {
  # Location of keycloak.json configuration file.
  # Locally should always point to the docker-composed Keycloak
  # (and not e.g. to Keycloak from dev/int environments, to avoid discrepancies between Keycloak and phoenix-backend database).
  client-conf-location = "./dev/keycloak/keycloak.json"
  client-conf-location = ${?KEYCLOAK_CLIENT_CONF_LOCATION}
}
