# JDBC/Slick specific config

jdbc-journal {
  use-shared-db = "slick"
}

# the akka-persistence-snapshot-store in use
jdbc-snapshot-store {
  use-shared-db = "slick"
}

# the akka-persistence-query provider in use
jdbc-read-journal {
  use-shared-db = "slick"
}

akka-persistence-jdbc {
  shared-databases {
    slick = ${slick}
  }
}

slick {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    name = "backend"
    name = ${?POSTGRES_DB}
    host = "localhost"
    host = ${?POSTGRES_HOST}
    port = 5432
    port = ${?POSTGRES_PORT}
    url = "jdbc:postgresql://"${slick.db.host}":"${slick.db.port}"/"${slick.db.name}"?reWriteBatchedInserts=true"
    user = "backend"
    user = ${?POSTGRES_USER}
    password = "backend"
    password = ${?POSTGRES_PASSWORD}
    driver = "org.postgresql.Driver"
    numThreads = 30
    numThreads = ${?DB_SLICK_THREADS_NUMBER}
    maxConnections = 30
    maxConnections = ${?DB_MAX_CONNECTIONS}
    minConnections = 30
    minConnections = ${?DB_MIN_CONNECTIONS}
  }
}

akka.projection.jdbc {
  dialect = postgres-dialect
  blocking-jdbc-dispatcher {
    thread-pool-executor {
      fixed-pool-size = 30
      fixed-pool-size = ${?AKKA_PERSISTENCE_JDBC_POOL_SIZE}
    }
  }

  offset-store {
    # set this to your database schema if applicable, empty by default
    schema = ""
    # the database table name for the offset store
    table = "akka_projection_offset_store"
  }
}

akka.persistence {

  journal {
    plugin = "jdbc-journal"
    auto-start-journals = ["jdbc-journal"]
  }

  journal-plugin-fallback {
    recovery-event-timeout = 30s
    recovery-event-timeout = ${?AKKA_PERSISTENCE_RECOVERY_TIMEOUT}
    circuit-breaker {
      call-timeout = 30s
      call-timeout = ${?AKKA_PERSISTENCE_RECOVERY_TIMEOUT}
    }
  }

  snapshot-store {
    plugin = "jdbc-snapshot-store"
    auto-start-snapshot-stores = ["jdbc-snapshot-store"]
  }

  snapshot-store-plugin-fallback {
    circuit-breaker {
      call-timeout = 30s
      call-timeout = ${?AKKA_PERSISTENCE_RECOVERY_TIMEOUT}
    }
  }

  state-plugin-fallback {
    recovery-timeout = 30s
    recovery-timeout = ${?AKKA_PERSISTENCE_RECOVERY_TIMEOUT}
  }
}