phoenix.pxp {
  base-url = "[i-should-be-replaced-by-env-var]"
  base-url = ${?PXP_BASE_URL}
  get-redirect-data-url = ${phoenix.pxp.base-url}"/PaymentRedirectionService/PaymentRedirectionService.svc/pox/getRedirectData"
  initiate-payment-url = ${phoenix.pxp.base-url}"/PaymentRedirectionService/PaymentService.svc/pox/initiatepayment"
  merchant-id = "[i-should-be-replaced-by-env-var]"
  merchant-id = ${?PXP_MERCHANT_ID}
  shop-id = "[i-should-be-replaced-by-env-var]"
  shop-id = ${?PXP_SHOP_ID}
  username = "[i-should-be-replaced-by-env-var]"
  username = ${?PXP_USERNAME}
  password = "[i-should-be-replaced-by-env-var]"
  password = ${?PXP_PASSWORD}
  webhook-username = "[i-should-be-replaced-by-env-var]"
  webhook-username = ${?PXP_WEBHOOK_USERNAME}
  webhook-password = "[i-should-be-replaced-by-env-var]"
  webhook-password = ${?PXP_WEBHOOK_PASSWORD}
}