include "dge"

phoenix {
  reports {
    default-cache {
      initial-capacity = 100
      max-capacity = 100
      # 12h so the cache invalidated between report executions, and we load new values in next execution
      time-to-live = 12.hours
      time-to-idle = 1.hour
    }

    fixture-market-cache = ${phoenix.reports.default-cache} {
      # we should be able to cache all required markets that has bets in given period
      max-capacity = 1000
    }

    projections {
      bets.name = "reporting-bets"
      bet-events.name = "reporting-bet-events"
      fixtures.name = "reporting-fixtures"
      markets.name = "reporting-markets"
      wallets.name = "reporting-wallets"
      wallet-transactions.name = "reporting-wallet-transactions"
      // TODO (PHXD-3293): remove after release of PHXD-3293
      wallet-pending-withdrawals.name = "reporting-pending-withdrawals"
      punters.name = "reporting-punters"
      verification-data.name = "reporting-verification-data"
    }

    dge {
      sftp = ${dge.sftp}
      directory = "Rev_Reports"
      daily-reports {
        name = "dge-daily-reports-periodic-worker"
        schedule = "mode=daily,start-time=\"01:00\""
        schedule = ${?DGE_DAILY_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
    }

    aml {
      reports-recipient = "blackhole@sink.sendgrid.net"
      reports-recipient = ${?AML_EMAIL_REPORTS_RECIPIENT}
      daily-reports {
        name = "aml-daily-reports-periodic-worker"
        schedule = "mode=daily,start-time=\"06:00\""
        schedule = ${?AML_DAILY_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
      weekly-reports {
        name = "aml-weekly-reports-periodic-worker"
        schedule = "mode=weekly,day-of-week=MONDAY,start-time=\"06:00\""
        schedule = ${?AML_WEEKLY_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
      monthly-reports {
        name = "aml-monthly-reports-periodic-worker"
        schedule = "mode=monthly,day-of-month=1,start-time=\"06:00\""
        schedule = ${?AML_MONTHLY_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
      deceased-reports {
        name = "aml-deceased-reports-periodic-worker"
        schedule = "mode=weekly,day-of-week=WEDNESDAY,start-time=\"06:00\""
        schedule = ${?AML_DECEASED_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
      manually-unsuspended-punters-reports {
        name = "aml-manually-unsuspended-punters-reports-periodic-worker"
        schedule = "mode=weekly,day-of-week=TUESDAY,start-time=\"09:00\""
        schedule = ${?AML_MANUALLY_UNSUSPENDED_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
      multi-device-activity-reports {
        name = "aml-multi-device-activity-reports-periodic-worker"
        schedule = "mode=daily,start-time=\"06:00\""
        schedule = ${?AML_MULTI_DEVICE_ACTIVITY_REPORTS_SCHEDULE}
        time-restriction = 5.minutes
        max-retries = 5
      }
    }
  }
}
