from datetime import datetime
from time import time
from urllib import parse
from uuid import uuid4

import faker
from aws_rest_default.permissions import TokenHasScope
from aws_rest_default.tools import decrypt_b64, encrypt_b64
from aws_rest_default.views import DefaultLogAdapterViewMixing, DefaultJsonRestViewMixing
from django.conf import settings
from django.contrib.auth import login, authenticate
from django.core.cache import cache
from django.db import transaction
from django.http.response import HttpResponseNotFound, HttpResponseRedirect, HttpResponseGone
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.base import RedirectView
from django.views.generic.edit import BaseFormView
from oidc_provider.models import Client
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from oidc.models import SocialSecret
from oidc_rest.serializers import EmailKeyGenerator
from oidc_rest.serializers.registration import RegistrationSerializer
from oidc_rest.serializers.validate_email import VerifyEmailSerializer
from oidc_signals.signals import TrustedUserRegisteredSignal
from oidc_social.forms import EmailForm
from oidc_social.models import SocialUserProfile, SocialTokens
from oidc_social.serializers import SocialTokenSerializer
from oidc_social.utils import HandleErrorException, SocialProfile, SocialValveMixing, SimpleResponseHandler, \
    get_social_token_session_key
from profiles.models import Email
from project.authentication_backends import OidcJsonTokenAuth

fake = faker.Faker()


class AbstractSocialLoginRedirectView(SocialValveMixing, DefaultLogAdapterViewMixing, RedirectView):
    """
    This class based view is used by 3rd social logins to prepare redirect response to social OAuth endpoints.
    3rd party class should only extend `get_redirect_params` method and `target_url` with `social_type` properties.
    """

    http_method_names = ['get']
    # we only handling GET method - which is link generated by `oidc_social_buttons` template tags

    target_url = None
    # Target url which is OAuth endpoint

    permanent = False
    # Never change this to TRUE! We need HTTP302 instead of HTTP 301

    _redirect_url = None

    @property
    def redirect_url(self):
        if self._redirect_url is None:
            self._redirect_url = settings.SITE_URL + reverse('oidc_social:oauth_response')
        return self._redirect_url

    def get_redirect_params(self, client_id, state):
        """
        Method should be overwritten to return all params need by social OAuth endpoint.

        :param client_id: RMX client ID
        :param state: CSRT token
        :type state: str
        :return: dictionary of params needed by OAuth to authorize
        :rtype: dict
        """
        raise NotImplementedError()

    def get(self, request, *args, **kwargs):
        """
        This method is kinda tricky. Link generated by `oidc_social_buttons` generates link valid for a special time.
        Of course we could generate unique ID and store this in Redis but this is faster.
        It contains:
            - `n` means `next` param (in this case redirection to RMX OIDC Auth module with all params send by partner
            - `c` means `client_id` which is Partner's ID in RMX OIDC
            - `e` means `expiration` which is unix timestamp how long link is valid.

        While dictionary is encrypted by RMX encryption library and encoded using url safe base64 encoding.

        Please note that `key` parameter is being exchanged into dictionary described above, like View has been invoked with this parameters.

        :return:    When `key` is somehow broken, View returns HTTP 404.
                    When `key` expired, View returns HTTP 410 GONE
                    When everything is OK, View return HTTP 302 - Moved Temporary

        """
        key = kwargs.pop('key')
        try:
            obj = decrypt_b64(key)
            kwargs = {
                'next_param': obj.get('n'),
                'client_id': obj.get('c'),
                'expiration': int(obj.get('e', '0'))
            }
        except Exception as e:
            self.logger.warn('Wrong KEY {}: {}'.format(key, e))
            return HttpResponseNotFound()

        if kwargs['expiration'] < int(time()):
            self.logger.warn('Expired KEY: {}'.format(key))
            return HttpResponseGone()
        else:
            return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        """
        This method basically generates CSRF token used in OAuth flows named `state` and invokes `get_redirect_params()` method to get all params needed by OAuth endpoint.
        After that it stores CSRF token in Redis with all information needed to perform final redirect to RMX OAuth, like `client_id` `next` param and whole `redirect params`

        :return: URL to OAuth endpoint with redirect params
        """
        next_param = kwargs.get('next_param')
        if not next_param:
            self.logger.warn('No "next_param" found. returning empty URL - GONE')
            return None
        client_id = kwargs.get('client_id')
        state = uuid4().hex
        params = self.get_redirect_params(client_id=client_id, state=state)
        if params is None:
            self.logger.warn('Unable to find configuration for social "{}" for client_id "{}"'.format(self.social_type, client_id))
            return None

        self.store_social_data(client_id=client_id, state=state, request_params=params, next_param=next_param)

        return self._format_url(params)

    def _format_url(self, params):
        """
        Private method encode params to URL GET query params and appends them to `self.target_url` property.
        :param params: Params to encode
        :type params: dict

        :return: final URL
        :rtype: str
        """
        encoded = parse.urlencode(params, doseq=True)
        return '{}?{}'.format(self.target_url, encoded)


class RedirectUriResponseView(DefaultLogAdapterViewMixing, SocialValveMixing, BaseFormView):
    """
    This view does almost everything with response from social authorization endpoint.
    Any response from authentication endpoint must be exchanged for long-term token using social client secret. Every social 
    """
    http_method_names = ['get', 'post']
    _simple_handler = None
    _facebook_handler = None
    _google_handler = None

    form_class = EmailForm

    def init_handlers(self):
        """
        Every handler has request.session object so I want to initialize only one object this type because `request.session` has connection pool that speed up connectivity.
        That's the reason why this method is being called only once during initialization of views.
        """
        from .social.facebook import FacebookResponseHandler
        from .social.google import GoogleResponseHandler
        self._simple_handler = SimpleResponseHandler(self)
        self._facebook_handler = FacebookResponseHandler(self)
        self._google_handler = GoogleResponseHandler(self)

    def handle_error(self, request, **context):
        """
        Shortcut function to pass cached errors into `simple_handler`.
        """
        return self._simple_handler.handle_error(request, **context)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.init_handlers()

    def get(self, request, *args, **kwargs):
        state = request.GET.get('state')
        if not state:
            self.logger.warn('"STATE" parameter not found! Redirecting to error page.')
            return self.handle_error(request, error='missing_state', error_description='CSRF detected')
        next_param = None
        with cache.lock('oidc:social:response_handling:{}'.format(state), expire=settings.CACHE_LOCK_MAX_TIMEOUT):
            valve = self.get_social_data(state)
            if not valve:
                self.logger.warn('No valve for state="{}" found. Redirecting to error page.'.format(state))
                return self.handle_error(request, error='missing_valve', error_description='CSRF detected. Missing Valve.')

            try:
                if 'error' in request.GET:
                    self.logger.error('Received STATE={} (client_id={}, {}) and error response: {}'.format(
                        state,
                        valve['client_id'],
                        valve['social_type'],
                        request.GET.dict()
                    ))
                    return self.handle_error(request, **request.GET.dict())

                social_type = valve.get('social_type', 'unknown')
                next_param = valve.get('next_param')
                client_id = valve.get('client_id')

                if social_type == SocialSecret.SOCIAL_TYPE_CHOICES.FACEBOOK:
                    profile = self._facebook_handler.handle(request, valve)
                elif social_type == SocialSecret.SOCIAL_TYPE_CHOICES.GOOGLE_PLUS:
                    profile = self._google_handler.handle(request, valve)
                else:
                    raise HandleErrorException(error='unknown_handler', error_description='Unknown handler for social type: {}'.format(social_type))

                if profile.social_type is None or not profile.social_type or profile.social_id is None or not profile.social_id:
                    raise HandleErrorException(error='empty_profile', error_description='Unable to determine your identity')

                return self.handle_profile(profile, next_param, client_id, social_type)
            except HandleErrorException as e:
                return self.handle_error(request, error=e.error, error_description=e.error_description, next=next_param)
            except Exception as e:
                self.logger.exception('Catch Exception {}'.format(e))
                return self.handle_error(request, error='server_error', error_description='Yes.. this is bad..', next=next_param)
            finally:
                self.clear_social_data(state)

    def store_token_and_login_user(self, request, user, profile, client_id, social_type):
        try:
            social_token = SocialTokens.objects.create(
                user=user,
                oidc_client_id=Client.objects.only('id').get(client_id=client_id).id,
                social_type=social_type,
                social_token=profile.social_token
            )
            social_token.created_at = datetime.now()

            social_serializer = SocialTokenSerializer(instance=social_token)

            request.session[get_social_token_session_key()] = social_serializer.data

        except Client.DoesNotExist:
            self.logger.exception('Client for {} does not exists'.format(client_id))
            raise HandleErrorException(error='store_token_and_login_user', error_description='Unable to process tokens - problem with client')
        except Exception as e:
            self.logger.exception(e)
            raise HandleErrorException(error='store_token_and_login_user', error_description='Unable to process tokens!')
        login(request, user)

    def handle_profile(self, profile, next_param, client_id, social_type):
        assert isinstance(profile, SocialProfile)

        # checking if I have this user
        user = authenticate(self.request, social_type=profile.social_type, social_id=profile.social_id)
        if user:
            self.store_token_and_login_user(self.request, user, profile, client_id, social_type)
            return HttpResponseRedirect(next_param)

        # If i don't have this user i must check an email
        if profile.email is None:
            data_bag_profile = profile.to_data_bag()
            data_bag = {
                'p': data_bag_profile,
                'n': next_param,
                'c': client_id,
                'st': social_type,
                'tk': profile.social_token
            }
            data_bag_encrypted = encrypt_b64(data_bag)
            templates = [
                'oidc_social/email_form/{}.html'.format(client_id),
                'oidc_social/email_form/default.html',
            ]
            form = self.form_class(initial={'data_bag': data_bag_encrypted})
            return render(self.request, template_name=templates, context={'form': form})

        # ok we have an email, check if exists, if so we need to ask user to log in using his different account and then add social
        #
        # here is the place where modification for temp user starts
        if Email.objects.filter(email=profile.email, user__is_temporary=False).exists():
            templates = [
                'oidc_social/email_exists/{}.html'.format(client_id),
                'oidc_social/email_exists/default.html',
            ]
            return render(self.request, template_name=templates, context={'next': next_param})

        # now we creating user (limited one if no validated email)
        serializer_data = {
            'username': 'social_{}'.format(uuid4().hex),
            'email': profile.email,
            'password': fake.password(length=60, special_chars=True, digits=True, upper_case=True, lower_case=True),
            'originators_client_id': client_id
        }
        serializer = RegistrationSerializer(context={'request': self.request}, data=serializer_data)
        if not serializer.is_valid(raise_exception=False):
            return self.handle_error(self.request, error='user_create_serializer', error_description='{}'.format(serializer.errors))

        # email is verified by Social - creating not-limited user
        with transaction.atomic():
            skip_signal_sending = bool(profile.email_verified)
            self.logger.info('Creating Social(verified={}) user: {}'.format(profile.email_verified, profile))
            user = serializer.save(skip_signal_sending=skip_signal_sending)

            if skip_signal_sending:
                key, _ = EmailKeyGenerator.get_key_and_expiration_date(user, profile.email)
                self.logger.info('Autoactivating user because we can trust it')
                verify_serializer = VerifyEmailSerializer(data={'key': key})
                if not verify_serializer.is_valid(raise_exception=False):
                    return self.handle_error(self.request, error='email_autoactivation_key_error', error_description=verify_serializer.errors)
                verify_serializer.save()
                self.logger.info('Sending TrustedUserRegisteredSignal')
                TrustedUserRegisteredSignal.send(
                    sender=self.__class__,
                    user=user,
                    msg_id=self.logger.request_msg_id
                )
            SocialUserProfile.objects.create(user=user, social_id=profile.social_id, social_type=profile.social_type)

        user = authenticate(self.request, social_type=profile.social_type, social_id=profile.social_id)
        if user:
            self.store_token_and_login_user(self.request, user, profile, client_id, social_type)

            return HttpResponseRedirect(next_param)
        return self.handle_error(self.request, error='post_creation_user_auth', error_description='Unable to authenticate You. Contact with US!')

    def form_invalid(self, form):
        if 'data_bag' in form.errors.keys():
            return self.handle_error(self.request, error='form_databag_corrupt', error_description='Fatal error for data_bag')
        client_id = form.cleaned_data['client_id']

        templates = [
            'oidc_social/email_form/{}.html'.format(client_id),
            'oidc_social/email_form/default.html',
        ]
        return render(self.request, template_name=templates, context={'form': form})

    def form_valid(self, form):
        client_id = form.cleaned_data['client_id']
        next_param = form.cleaned_data['next_param']
        profile = form.cleaned_data['profile']
        social_type = form.cleaned_data['social_type']
        social_token = form.cleaned_data['social_token']
        profile = SocialProfile(profile, social_token=social_token)
        return self.handle_profile(profile=profile, client_id=client_id, next_param=next_param, social_type=social_type)


class OAuth1RedirectUriResponseView(RedirectUriResponseView):
    _twitter_handler = None

    form_class = EmailForm

    def init_handlers(self):
        from oidc_social.social.twitter import TwitterResponseHandler
        super().init_handlers()
        self._twitter_handler = TwitterResponseHandler(self.logger)

    def get(self, request, *args, **kwargs):
        self.init_handlers()

        denied = request.GET.get('denied')
        if denied:
            valve = self.get_social_data(denied)
            if valve and 'next_param' in valve:
                next_param = valve['next_param']
                self.clear_social_data(denied)
            else:
                next_param = None
            return self.handle_error(request, error='social_denied', error_description='You denied access to your profile', next=next_param)

        state = request.GET.get('oauth_token')
        verifier = request.GET.get('oauth_verifier')

        if not state:
            self.logger.warn('"STATE" parameter not found! Redirecting to error page.')
            return self.handle_error(request, error='missing_state', error_description='CSRF detected')

        if not verifier:
            self.logger.warn('"VERIFIER" parameter not found! Redirecting to error page.')
            return self.handle_error(request, error='missing_verifier', error_description='Error during OAuth login flow.')

        next_param = None
        with cache.lock('oidc:social:response_handling:{}'.format(state), expire=settings.CACHE_LOCK_MAX_TIMEOUT):
            valve = self.get_social_data(state)
            if not valve:
                self.logger.warn('No valve for state="{}" found. Redirecting to error page.'.format(state))
                return self.handle_error(request, error='missing_valve', error_description='CSRF detected. Missing Valve.')

            try:
                social_type = valve.get('social_type', 'unknown')
                next_param = valve.get('next_param')
                client_id = valve.get('client_id')

                if social_type == SocialSecret.SOCIAL_TYPE_CHOICES.TWITTER:
                    profile = self._twitter_handler.handle(request, valve)
                else:
                    raise HandleErrorException(error='unknown_handler', error_description='Unknown handler for social type: {}'.format(social_type))

                if profile.social_type is None or not profile.social_type or profile.social_id is None or not profile.social_id:
                    raise HandleErrorException(error='empty_profile', error_description='Unable to determine your identity')

                return self.handle_profile(profile, next_param, client_id, social_type)
            except HandleErrorException as e:
                return self.handle_error(request, error=e.error, error_description=e.error_description, next=next_param)
            except Exception as e:
                self.logger.exception('Catch Exception {}'.format(e))
                return self.handle_error(request, error='server_error', error_description='Yes.. this is bad..', next=next_param)
            finally:
                self.clear_social_data(state)


class SocialTokenView(DefaultJsonRestViewMixing, generics.RetrieveAPIView):
    serializer_class = SocialTokenSerializer
    required_scopes = ('oidc:social:token:read',)
    authentication_classes = (OidcJsonTokenAuth,)
    permission_classes = (IsAuthenticated, TokenHasScope)
    http_method_names = ('get', 'options',)

    def get_object(self):
        return self.request.session.get(get_social_token_session_key(), {})

    def retrieve(self, request, *args, **kwargs):
        data = self.get_object()
        return Response(data)
