# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 12:25
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0003_auto_20170415_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default=profiles.utils.get_random_display_name, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub',
            field=models.CharField(default=profiles.utils.generate_user_sub, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('user', 'phone_number')]),
        ),
        migrations.AlterIndexTogether(
            name='phone',
            index_together=set([('user', 'phone_number'), ('user', 'phone_number', 'is_primary')]),
        ),
    ]
