# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 10:56
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
import phonenumber_field.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0004_auto_20170415_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('country', models.CharField(choices=[('uk', 'United Kingdom')], default='uk', max_length=2)),
                ('line_1', models.CharField(max_length=100)),
                ('line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('user', 'is_primary')]),
        ),
    ]
