# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 15:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0006_auto_20170418_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.Company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='originator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='introduced_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
