# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0005_auto_20170420_0918'),
        ('profiles', '0009_auto_20170419_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='oidc_permissions',
            field=models.ManyToManyField(related_name='_customuser_oidc_permissions_+', to='oidc.BaseTreeNode'),
        ),
    ]
