# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0010_auto_20170420_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='oidc_permissions',
            field=models.ManyToManyField(blank=True, related_name='_customuser_oidc_permissions_+', to='oidc.BaseTreeNode'),
        ),
    ]
