# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0011_auto_20170420_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_limited',
            field=models.BooleanField(default=True, help_text='User must confirm email to become not limited'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
