# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0012_auto_20170421_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
