# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:15
from __future__ import unicode_literals

from django.db import migrations

import profiles.managers


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0013_remove_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', profiles.managers.CustomUserManager()),
            ],
        ),
    ]
