# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0014_auto_20170616_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='User created as temporary user. If user is temporary, it can NOT login and is limited!'),
        ),
    ]
