rules = [
  NoEnumToString,
  OrganizeImports,
]

OrganizeImports {
  expandRelative = true
  groupedImports = Explode
  groups = [
    "java.",
    "scala.",
    "*",
    "phoenix"
  ]
  removeUnused = true
}
