# Generated by Django 3.1.1 on 2020-10-19 14:11

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import virtual_store.managers
import virtual_store.tools


class Migration(migrations.Migration):

    replaces = [
        ("virtual_store", "0001_initial"),
        ("virtual_store", "0002_auto_20200918_1049"),
        ("virtual_store", "0003_auto_20200918_1108"),
        ("virtual_store", "0004_auto_20200921_1311"),
        ("virtual_store", "0005_auto_20200924_1313"),
        ("virtual_store", "0006_customuser_is_test_user"),
        ("virtual_store", "0007_auto_20200929_1130"),
        ("virtual_store", "0008_auto_20201016_1346"),
        ("virtual_store", "0009_auto_20201019_0823"),
        ("virtual_store", "0010_partner_provisioning_meta"),
        ("virtual_store", "0011_auto_20201019_1146"),
        ("virtual_store", "0012_auto_20201019_1158"),
        ("virtual_store", "0013_auto_20201019_1410"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "originator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_company": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="introduced_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.CharField(max_length=50)),
                ("symbol2", models.CharField(max_length=2)),
                ("symbol3", models.CharField(max_length=3)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("AWAITING_FULFILLMENT", "Awaiting Fulfillment"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("DECLINED", "Declined"),
                            ("MANUAL_VERIFICATION_REQUIRED", "Manual Verification Required"),
                        ],
                        max_length=28,
                        null=True,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("order_sum", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_currency_set",
                        to="virtual_store.currency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "provision_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("PARTIAL_DELIVERED", "Partial Delivered"),
                        ],
                        default="PENDING",
                        max_length=17,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("line_sum", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_line_set",
                        to="virtual_store.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("BP", "Base Product"), ("SP", "Subscription Product"), ("CP", "Consumable Product")],
                        default="BP",
                        max_length=2,
                    ),
                ),
                (
                    "product_subtype",
                    models.CharField(choices=[("NR", "Normal"), ("VR", "Virtual")], default="VR", max_length=2),
                ),
                (
                    "provision_type",
                    models.CharField(
                        choices=[("NONE", "None"), ("ANTSTREAM", "AntStream")], default="NONE", max_length=20
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_index", models.PositiveIntegerField(default=0)),
                (
                    "max_quantity_per_user",
                    models.PositiveIntegerField(
                        blank=True, help_text="The number of times a single user can purchase this product", null=True
                    ),
                ),
                ("subscription_duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "subscription_duration_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MINUTE", "Minute"),
                            ("HOUR", "Hour"),
                            ("DAY", "Day"),
                            ("WEEK", "Week"),
                            ("MONTH", "Month"),
                            ("YEAR", "Year"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("subscription_level", models.PositiveIntegerField(blank=True, default=1, null=True)),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Product is active from the start date. Leave this empty if the product has no start date.",
                        null=True,
                    ),
                ),
                (
                    "available_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Product is active to the end date. Leave this empty if the product has no end date.",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Show this product in search results.",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "photo_small",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                (
                    "photo_medium",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                (
                    "photo_large",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                (
                    "photo_thumbnail",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                (
                    "photo_purchased",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                (
                    "photo_not_available",
                    models.FileField(blank=True, null=True, upload_to=virtual_store.tools.get_member_upload_to),
                ),
                ("photo_index", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_set",
                        to="virtual_store.currency",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_set",
                        to="virtual_store.partner",
                    ),
                ),
                ("provision_meta", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="UserPurchasedCount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_purchased_count",
                        to="virtual_store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("message", models.TextField()),
                ("order_log_object_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_log_set",
                        to="virtual_store.order",
                    ),
                ),
                (
                    "order_log_content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("app_label", "virtual_store"), ("model__in", ("Order", "OrderLine", "OrderLineItem"))
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_log_content_type_obj",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("position", models.PositiveIntegerField()),
                (
                    "sub_provision_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered")], default="PENDING", max_length=9
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_line_items_set",
                        to="virtual_store.orderline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtual_store.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="order_set", to="virtual_store.partner"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="currency",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="partner_currency", to="virtual_store.partner"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="originator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="introduced_partner",
                to="virtual_store.partner",
            ),
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", virtual_store.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="object_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_test_user",
            field=models.BooleanField(default=False, help_text="User test flag"),
        ),
        migrations.CreateModel(
            name="BackpackItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("is_consumed", models.BooleanField(default=False)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_backpack_items_set",
                        to="virtual_store.order",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_line_backpack_items_set",
                        to="virtual_store.orderline",
                    ),
                ),
                (
                    "order_line_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_line_items_backpack_items_set",
                        to="virtual_store.orderlineitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_backpack_items_set",
                        to="virtual_store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_backpack_items_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("AWAITING_PAYMENT", "Awaiting for Payment"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="NEW",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                    ("MANUAL_VERIFICATION_REQUIRED", "Manual Verification Required"),
                ],
                db_index=True,
                default="PENDING",
                max_length=28,
            ),
        ),
        migrations.CreateModel(
            name="UserSubscriptions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("sub", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "backpack_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscription_set",
                        to="virtual_store.backpackitem",
                    ),
                ),
                ("is_deprovisioned", models.BooleanField(db_index=True, default=False)),
                ("is_provisioned", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
