# Generated by Django 3.1.1 on 2020-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0001_squashed_0013_auto_20201019_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="partner_meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("ANTSTREAM", "AntStream"), ("DEFAULT_TYPE", "Default Type")],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
