# Generated by Django 3.1 on 2020-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subscription_level",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
