# Generated by Django 3.1.1 on 2020-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0002_auto_20201026_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                choices=[("ANTSTREAM", "AntStream"), ("DEFAULT_TYPE", "Default Type")],
                db_index=True,
                default="DEFAULT_TYPE",
                max_length=50,
            ),
        ),
    ]
