# Generated by Django 3.1 on 2020-09-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0002_auto_20200918_1049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_company",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="originator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="introduced_partner",
                to="virtual_store.partner",
            ),
        ),
    ]
