# Generated by Django 3.1.1 on 2020-10-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0003_auto_20201026_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="line_sum",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="provision_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
