# Generated by Django 3.1 on 2020-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0003_auto_20200918_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backpackitem",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
