# Generated by Django 3.1 on 2020-09-24 13:13

import uuid

import django.utils.timezone
from django.db import migrations, models

import virtual_store.managers


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0004_auto_20200921_1311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", virtual_store.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="object_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
