# Generated by Django 3.1.2 on 2020-11-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0004_auto_20201028_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auto_provision",
            field=models.BooleanField(
                default=False, help_text="When TRUE, backpack item will be automatically activated"
            ),
        ),
    ]
