# Generated by Django 3.1.2 on 2020-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0005_product_auto_provision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backpackitem",
            old_name="order_line_items",
            new_name="order_line_item",
        ),
    ]
