# Generated by Django 3.1 on 2020-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0005_auto_20200924_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_test_user",
            field=models.BooleanField(default=False, help_text="User test flag"),
        ),
    ]
