# Generated by Django 3.1.2 on 2020-11-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0007_chinamobilepaymentconfigurationmodel_cm_proxy_url"),
        ("virtual_store", "0006_auto_20201110_1928"),
    ]

    operations = [
        migrations.AddField(
            model_name="backpackitem",
            name="receipt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="payment_gateway.receiptmodel",
            ),
        ),
    ]
