# Generated by Django 3.1 on 2020-09-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0006_customuser_is_test_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backpackitem",
            name="order_line_items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_line_items_backpack_items_set",
                to="virtual_store.orderlineitem",
            ),
        ),
    ]
