# Generated by Django 3.1.2 on 2020-11-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0007_backpackitem_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscriptions",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="virtual_store.customuser"
            ),
            preserve_default=False,
        ),
    ]
