# Generated by Django 3.1.1 on 2020-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0007_auto_20200929_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("AWAITING_PAYMENT", "Awaiting for Payment"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="NEW",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                    ("MANUAL_VERIFICATION_REQUIRED", "Manual Verification Required"),
                ],
                db_index=True,
                default="PENDING",
                max_length=28,
            ),
        ),
    ]
