# Generated by Django 3.1.1 on 2020-10-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0008_auto_20201016_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="provision_type",
            field=models.CharField(
                choices=[("NONE", "None"), ("ANTSTREAM", "AntStream")], default="NONE", max_length=20
            ),
        ),
    ]
