# Generated by Django 3.1.2 on 2020-11-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("virtual_store", "0008_usersubscriptions_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscriptions",
            name="is_send_for_deprovisioning",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="orderlog",
            name="order_log_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("app_label", "virtual_store"),
                    ("model__in", ("Order", "OrderLine", "OrderLineItem", "BackpackItem", "UserSubscriptions")),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_log_content_type_obj",
                to="contenttypes.contenttype",
            ),
        ),
    ]
