# Generated by Django 3.1.4 on 2021-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0009_auto_20201123_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="backpackitem",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backpackitem",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
