# Generated by Django 3.1.1 on 2020-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0009_auto_20201019_0823"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="provisioning_meta",
            field=models.JSONField(default=dict),
        ),
    ]
