# Generated by Django 3.1.1 on 2020-10-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0010_partner_provisioning_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="provisioning_meta",
        ),
        migrations.AddField(
            model_name="product",
            name="provisioning_meta",
            field=models.JSONField(default=dict),
        ),
    ]
