# Generated by Django 3.1.1 on 2020-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0011_auto_20201019_1146"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="provisioning_meta",
            new_name="provision_meta",
        ),
    ]
