# Generated by Django 3.1.1 on 2020-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_store", "0012_auto_20201019_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscriptions",
            name="is_deprovisioned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="usersubscriptions",
            name="is_provisioned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="usersubscriptions",
            name="end_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="usersubscriptions",
            name="start_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
