app {
  auth {
    rmx {
      url = "https://api.rewardsmatrix.com"
      client_id = ${RMX_CLIENT_ID}
      client_password = ${RMX_CLIENT_PASSWORD}
      user_name = ${RMX_USER}
      user_password = ${RMX_PASSWORD}
    }
    token {
      expiry {
        offset = 60s
        clock_skew = 0s
      }
    }
    jwks {
      cache {
        expire = 1h
        resilience = 1m
      }
    }
    oidc-discovery {
      cache {
        expire = 1h
        resilience = 1m
      }
    }
  }
}