stella {
  leaderboard {
    kafka {
      topic-name = "streaming.stella-aggregated"
      topic-name = ${?LEADERBOARD_KAFKA_AGGREGATES_TOPIC_NAME}
      bootstrap-servers = "localhost:9092"
      bootstrap-servers = ${?LEADERBOARD_KAFKA_BOOTSTRAP_SERVERS}

      serializer {
        schema-registry-url = "http://localhost:8081"
        schema-registry-url = ${?LEADERBOARD_KAFKA_SCHEMA_REGISTRY_URL}
      }

      consumer {
        client-id = "messaging.stella-leaderboard"
        client-id = ${?LEADERBOARD_KAFKA_CLIENT_ID}
        group-id = "messaging.stella-leaderboard"
        group-id = ${?LEADERBOARD_KAFKA_GROUP_ID}
        kafka-poll-timeout = 5 seconds
        kafka-poll-timeout = ${?LEADERBOARD_KAFKA_POLL_TIMEOUT}
      }
    }
  }
}
