nameOverride: "prod-freshspins-client-service"
fullnameOverride: "prod-freshspins-client-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: true
  port: 3000

ingress:
  enabled: false

env:
  SITE_NAME: sportnation
  NODE_ENV: production
  PORT: 3000
  API: http://prod-freshspins-backend-service:3000
  CAPTCHA_KEY: "6LfyVVclAAAAAIw3hAyv7XzJlhMaCz-ksqQMNSDl"
