play {
  application.loader = net.flipsports.gmx.widget.argyll.betandwatch.webgateway.Loader

  http {
    context = "/"
    secret {
      key = "changeme"
      key = ${?APPLICATION_SECRET}
    }
    forwarded.trustedProxies=["10.4.64.0/23", "10.4.68.0/23",
      "10.6.0.0/23", "10.6.4.0/23", "10.6.8.0/23"]
  }

  server.pidfile.path = /dev/null
}

lagom {
  services {
    event = internal-lagom-addres
    event-SN = ${SERVICE_EVENT_SN_URL}
    event-RZ = ${SERVICE_EVENT_RZ_URL}
  }
  circuit-breaker {
    default {
      max-failures = 1

      call-timeout = 60s

      reset-timeout = 60s

      exception-whitelist = [
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.EventNotFoundException,
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.StreamingNotAvailableException,
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.UnauthorizedException,
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.InvalidUserCountryException,
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.NoQualifyingBetException,
        net.flipsports.gmx.widget.argyll.betandwatch.events.api.exception.VideoNotAvailableException,
        net.flipsports.gmx.common.internal.scala.core.exception.BaseException
      ]
    }
  }
}

SIMULATE_EXCEPTIONS = true