apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-ecr-credentials
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: aws-ecr-credentials
    creationPolicy: Owner
  dataFrom:
    - key: {{ .Values.externalSecrets.secretPath }}
