nameOverride: "prod-gstech-campaignserver-backend-service"
fullnameOverride: "prod-gstech-campaignserver-backend-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: true
  port: 3013

extraTCPPorts:
  private-api: 3014

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"

ingressClassName: nginx

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::743851384875:role/luckydino-prod-fasttrack-csv-s3

ingress:
  enabled: true

  name: alb-ingress-prod-gstech-campaignserver-backend-service
  hosts:
  - host: admin.luckydino.com
    paths:
    - path: /api/v1/
      pathType: Prefix
      serviceName: prod-gstech-campaignserver-backend-service
      servicePort: 3013
    - path: /
      pathType: Prefix
      serviceName: prod-gstech-campaignserver-client-service
      servicePort: 3051
  - host: campaignserver-binder.luckydino.com
    paths:
    - path: /api/
      pathType: Prefix
      serviceName: prod-gstech-campaignserver-backend-service
      servicePort: 3014

  annotations: {}

  tls: []

env:
  POSTGRES_HOST: rds-campaignserver.prod.eeg.viegg.net
  POSTGRES_USER: gstech
  REDIS_HOST: redis-campaignserver.prod.eeg.viegg.net
  REDIS_PORT: 6379
  CAMPAIGN_SERVER_URL: https://admin.luckydino.com/api/v1
  BACKEND_URL: http://prod-gstech-backend-service:3001
  REWARD_SERVER_URL: http://prod-gstech-rewardserver-service:3012/api/v1
  REWARD_SERVER_MANAGEMENT_URL: http://prod-gstech-rewardserver-service:3011/api/v1
  POSTGRES_POOL_SIZE: 40
  KAFKA_ENABLED: "true"
  KAFKA_HOST: b-3.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com,b-2.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com,b-1.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com
  KAFKA_PORT: 9094
  KAFKA_SSL: "true"
  NODE_ENV: production
  # KAFKAJS_LOG_LEVEL: "debug"
  REWARD_SERVER_AUTH_TOKEN: "GS[fPcXPQo5QKmJmzfcAbL1eqz6JZJwnT94otkZ5CP6EBWwqRBhB0r9TgMVRpRttQnV/dEE+L2MAbfulWpy2OmaEKZnqB/RTmvQ2ZNbaZWlfwFgGLMlUCo=]"
  CAMPAIGN_SERVER_AUTH_TOKEN: "GS[xZ/zWD5Fzs0NLQ+Ry9W/uxO6rManr2j6zu0REYhLJhhs69FemQMPgnJYOLzPkUjo34EVy3tBtYF8VauC6oVetz+X76J00hjV8yTCwL5w9IBFGCYLGA==]"
  CF_CERTS_URL: https://admin.luckydino.com/cdn-cgi/access/certs
  FT_MIGRATION_S3: prod-fasttrack-csv-content
  FT_MIGRATION_S3_REGION: eu-west-1
secretEnv:
  POSTGRES_PASSWORD:
    prod-gstech-campaignserver-backend-service: postgres-password
  PRIVATE_KEY:
    prod-common-secrets: private-key
  GOOGLE_CLIENT_ID:
    prod-gstech-campaignserver-backend-service: google-client-id
  GOOGLE_CLIENT_SECRET:
    prod-gstech-campaignserver-backend-service: google-client-secret
