# Generated by Django 3.1 on 2020-08-28 13:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oidc", "0008_auto_20200825_0835"),
        ("oidc_provider", "0026_client_multiple_response_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntstreamModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "oidc_client_extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antstream_client",
                        to="oidc.oidcclientextra",
                    ),
                ),
                (
                    "rsa_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antstream_key",
                        to="oidc_provider.rsakey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
