# Generated by Django 3.1.4 on 2021-01-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("antstream", "0002_auto_20200831_2231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antstreammodel",
            name="notification_send_timeout",
        ),
        migrations.RemoveField(
            model_name="antstreammodel",
            name="notification_url",
        ),
    ]
