play {
  application.loader = net.flipsports.gmx.game.argyll.racingroulette.webgateway.WebGatewayLoader

  http {
    context = "/"
    secret {
      key = "changeme"
      key = ${?APPLICATION_SECRET}
    }
  }

  // endpoints with tags on balcklist will be accessible only from localhost
  filters.hosts {
    allowed = ["localhost"]
    routeModifiers {
      whiteList = []
      blackList = [operations]
    }
  }

  server.pidfile.path = /dev/null
}

akka {
  loglevel = "DEBUG"
  //  log-config-on-start = on
  actor {
    debug {
      receive = on
      autoreceive = on
      lifecycle = on
      unhandled = on
    }
  }

  kafka.consumer {
    kafka-clients {
      enable.auto.commit = true
      auto.commit.interval.ms = 100
      auto.offset.reset = earliest
      max.poll.records = 100
      max.poll.interval.ms = 3000
    }
  }
}

app {
  play.http.filters {
    origins {
      allowed = ["https://www.sportnation.bet",
        "https://rsportnation.staging.sbtech.com/",
        // required to connect for debugging https://chrome.google.com/webstore/detail/smart-websocket-client/omalebghpgejjiaoknljcfmglgbpocdp
        "chrome-extension://omalebghpgejjiaoknljcfmglgbpocdp"
      ]
    }
  }
  event-updates {
    kafka-source {
      dump-records = false

      horse-racing-events = "gmx-messaging.sportnation-racing-roulette-horse-events"

      bootstrap-servers = "localhost:9092"
      bootstrap-servers = ${?GMX_KAFKA_BOOTSTRAP}

      schema-registry = "http://localhost:8081"
      schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY}
    }
    mock-source {
      enabled = false
      enabled = ${?GMX_MOCK_SOURCE_ENABLED}
    }
  }
  external {
    sbtech {
      betting-api {
        url = "https://stgapi.sbtech.com/"${app.external.sbtech.betting-api.operator}"/betting/v2"
      }
    }
  }
}
