sbTech {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    casino-bets = "ds_casinobets_%d"
    customer-details = "ds_customerdetails_%d"
    logins = "ds_logins_%d"
    sport-bets-info = "ds_sportbets_%d"
    wallet-transaction = "ds_wallettransactions_%d"
    customer-deposit = "ds_customerdeposit_%d"
    operator-events = "SD.External.Operator%d.Events.v2.PROD"
    operator-markets = "SD.External.Operator%d.Markets.v2.PROD"
    operator-selections = "SD.External.Operator%d.Selections.v2.PROD"
    offer-events = "ds_offerevents_%d"
    offer-options = "ds_offeroptions_%d"
    schema-registry = "http://datastream-schema.sbtech.com/"
  }
  target-topics {
    casino-bets = "gmx-messaging.%s-ds-casinobets"
    customer-details = "gmx-messaging.%s-ds-customerdetails"
    logins = "gmx-messaging.%s-ds-logins"
    sport-bets-info = "gmx-messaging.%s-ds-sportbets"
    wallet-transaction = "gmx-messaging.%s-ds-wallettransactions"
    customer-deposit = "gmx-messaging.%s-ds-customerdeposit"
    operator-events = "gmx-messaging.%s-sd-external-operator-events"
    operator-markets = "gmx-messaging.%s-sd-external-operator-markets"
    operator-selections = "gmx-messaging.%s-sd-external-operator-selections"
    offer-events = "gmx-messaging.%s-ds-offerevents"
    offer-options = "gmx-messaging.%s-ds-offeroptions"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }

}

include "dev.conf"