app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?EEG_WAYSUN_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    event-definition = "eeg-messaging.%s-event-definition"
    event-validated = "eeg-streaming.%s-event-validated"
    aggregation-definition = "eeg-messaging.%s-aggregation-definition"
    aggregation-control = "eeg-messaging.%s-aggregation-control"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
  target-topics {
    aggregation-result = "eeg-streaming.%s-aggregated"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
  cleaning-policy = [
  ]
}

include "dev.conf"