# The hook should be able to read admin password from a secret in Keycloak's namespace,
# and write the OIDC JSON as `keycloak-config-backend` secret in the current namespace.

kind: ServiceAccount
apiVersion: v1
metadata:
  name: keycloak-config-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # We use a smaller weight than for keycloak-config-setup-pod so that the resources are created before the pod.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-config-setup-read-secret
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-config-setup-read-secret
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-config-setup-read-secret
subjects:
  - kind: ServiceAccount
    name: keycloak-config-setup
    namespace: {{ .Release.Namespace }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-config-setup-write-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, get, patch]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-config-setup-write-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "40"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-config-setup-write-secret
subjects:
  - kind: ServiceAccount
    name: keycloak-config-setup
    namespace: {{ .Release.Namespace }}
