FLINK_HOST=10.4.73.131:8081

SCALA_VERSION=2.12
GROUP_ID=net.flipsports.gmx.streaming.sbtech.internalmodel
ARTIFACT_ID=internal-model-mapping-jobs
JOBS=('net.flipsports.gmx.streaming.sbtech.job.v1.CasinoBetSportsNationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.CustomerDetailsSportsNationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.SettlementDataSportsNationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.WalletTransactionSportsNationJob')
JOBS_NAMES=('Casino bets events to internal model on brand sportnation' 'Customer details events to internal model on brand sportnation' 'Sport bets events to internal model on brand sportnation' 'Wallet transactions events to internal model on brand sportnation')