apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  restartPolicy: Never
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.registry }}/phoenix-load-tests:{{ .Values.image.tag }}"
      imagePullPolicy: IfNotPresent
      args: ['-s', 'phoenix.bets.SampleLoadTest']
      env:
        - name: JAVA_OPTS
          value: '-Dgatling.base-url=http://phoenix-backend -Dgatling.ramp-users-during.seconds=15'
