livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 10

image:
  repository: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/vie-bet-strapi-cms
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  create: false

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

containerPort: 3000

prometheus:
  enabled: false
