akka.loglevel = "INFO"

phoenix {
  public-api-url = "https://api.dev.phoenix.darkstormlabs.net"
  public-api-url = ${?CONTRACT_TESTS_PUBLIC_API_URL}

  dev-api-url = "https://dev-api.dev.phoenix.darkstormlabs.net"
  dev-api-url = ${?CONTRACT_TESTS_DEV_API_URL}
  dev-api-credentials {
    username = ${CONTRACT_TESTS_DEV_API_USERNAME}
    password = ${CONTRACT_TESTS_DEV_API_PASSWORD}
  }

  web-sockets-url = "wss://ws-api.dev.phoenix.darkstormlabs.net"
  web-sockets-url = ${?CONTRACT_TESTS_WEB_SOCKETS_URL}
}

pxp {
  enable-pxp-tests = "true"
  enable-pxp-tests = ${?CONTRACT_TESTS_ENABLE_PXP_TESTS}
  api-url = "https://api.test.kalixa.com"
  api-credentials {
    username = ${CONTRACT_TESTS_PXP_API_USERNAME}
    password = ${CONTRACT_TESTS_PXP_API_PASSWORD}
  }
  merchant-id = "GMBLNewJerseyDev"
  merchant-id = ${?CONTRACT_TESTS_PXP_MERCHANT_ID}
  shop-id = "GMBLNewJerseyDev"
  shop-id = ${?CONTRACT_TESTS_PXP_SHOP_ID}
}
