FLINK_HOST=10.6.13.196:8081

SCALA_VERSION=2.12
GROUP_ID=net.flipsports.gmx.streaming.sbtech.odds
ARTIFACT_ID=jobs
JOBS=('net.flipsports.gmx.streaming.sbtech.job.v1.EventsSportsNationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.MarketsSportsNationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.SelectionsSportsNationJob')
JOBS_NAMES=('Race card roulette events events on brand sportnation' 'Race card roulette markets events on brand sportnation' 'Race card roulette selections events on brand sportnation')