helm:
  parameters:
  - name: image.repository
    value: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/gstech-walletserver
    forcestring: true
  - name: image.tag
    value: beta-70fab6084517e33e334c07f0c3eec89f132c5a38
    forcestring: true
