helm:
  parameters:
  - name: image.repository
    value: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/sn-affiliate-cms
    forcestring: true
  - name: image.tag
    value: v0.1.6-de0f9820fa2e6d09e803983aa90e3e5f478c23b7
    forcestring: true
