helm:
  parameters:
  - name: image.repository
    value: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/gstech-compliance
    forcestring: true
  - name: image.tag
    value: beta-b20e600f17b407154bb73a9b2c459df1a2c688ff
    forcestring: true
