helm:
  parameters:
  - name: image.repository
    value: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/gstech-campaignserver-client
    forcestring: true
  - name: image.tag
    value: beta-41d3070567ef52adfe693c3f18ec1bbcaa5208d1
    forcestring: true
