version: '3'

services:
  gstech-walletserver.test:
    build:
      context: ../../
      dockerfile: packages/gstech-walletserver/Dockerfile
    image: gstech-walletserver.test
    container_name: gstech-walletserver.test
    command: yarn test
    networks:
      - gstech
    environment:
      CI: "true"
      NODE_ENV: test
      RUNNER_DEBUG: ${RUNNER_DEBUG}
      NODE_NO_WARNINGS: ${NODE_NO_WARNINGS}
      REDIS_HOST: gstech-redis
      WALLET_URL: http://gstech-backend:3005/api/v1/wallet
      BACKEND_URL: http://gstech-backend:3001
      LOTTO_BACKEND_URL: http://lotto-backend:3040/api/v1/lottocasino
      LOGGER_FORMAT: nice

networks:
  gstech:
    external: true
