{{- $name := .Values.fullnameOverride -}}
{{- $secrets := .Values.secretEnv -}}

{{- if $secrets }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret" $name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: luckydino-secretstore
    kind: SecretStore
  target:
    name: {{ printf "%s-external-secret" $name }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := $secrets }}
  {{- range $k, $v := $value }}
    - secretKey: {{ printf "%s" $v | lower }}
      remoteRef:
        key: {{ printf "eso-%s" $k }}
        property: {{  $v }}
    {{- end}}
  {{- end }}
{{- end -}}
