slick {
  dbs {
    default {
      profile="slick.jdbc.PostgresProfile$"
      db {
        driver="org.postgresql.Driver"
        host="localhost"
        host=${?LEADERBOARD_DB_ADDRESS}
        port=5432
        port=${?LEADERBOARD_DB_PORT}
        name="leaderboard"
        name=${?LEADERBOARD_DB_NAME}
        url="jdbc:postgresql://"${slick.dbs.default.db.host}":"${slick.dbs.default.db.port}"/"${slick.dbs.default.db.name}
        user="leaderboard"
        user=${?LEADERBOARD_DB_USERNAME}
        password="leaderboard"
        password=${?LEADERBOARD_DB_PASSWORD}
      }
    }
  }
}
