# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 09:50
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
import polymorphic_tree.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Tree node',
                'verbose_name_plural': 'Tree nodes',
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oidc.BaseTreeNode')),
            ],
            options={
                'verbose_name': 'Group node',
                'verbose_name_plural': 'Group nodes',
            },
            bases=('oidc.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oidc.BaseTreeNode')),
            ],
            options={
                'verbose_name': 'Permission node',
                'verbose_name_plural': 'Permission nodes',
            },
            bases=('oidc.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='basetreenode',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='oidc.BaseTreeNode', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='basetreenode',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_oidc.basetreenode_set+', to='contenttypes.ContentType'),
        ),
    ]
