# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetreenode',
            options={'ordering': ('tree_id', 'lft'), 'verbose_name': 'Permission/group node', 'verbose_name_plural': 'Permissions and groups tree'},
        ),
        migrations.AddField(
            model_name='permissionnode',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='basetreenode',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
