# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0002_auto_20170419_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetreenode',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
