# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 16:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import oidc.utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_provider', '0022_auto_20170331_1626'),
        ('oidc', '0003_auto_20170419_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcClientExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed25519_private_key_hex', models.CharField(default=oidc.utils.get_private_ed25519_sign_key_hex, editable=False, max_length=64, unique=True)),
                ('ed25519_public_key_hex', models.CharField(default='unknown', editable=False, max_length=64, unique=True)),
                ('default_permissions', models.ManyToManyField(related_name='_oidcclientextra_default_permissions_+', to='oidc.BaseTreeNode')),
                ('limited_permissions', models.ManyToManyField(related_name='_oidcclientextra_limited_permissions_+', to='oidc.BaseTreeNode')),
                ('oidc_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='oidc_provider.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('fb', 'FACEBOOK'), ('tw', 'TWITTER'), ('g+', 'GOOGLE PLUS')], max_length=2)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('oidc_client_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_secrets', to='oidc.OidcClientExtra')),
            ],
        ),
    ]
