# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0004_oidcclientextra_socialsecret'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialsecret',
            unique_together=set([('oidc_client_extra', 'social_type')]),
        ),
    ]
