# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0005_auto_20170420_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcclientextra',
            name='default_permissions',
            field=models.ManyToManyField(blank=True, related_name='_oidcclientextra_default_permissions_+', to='oidc.BaseTreeNode'),
        ),
        migrations.AlterField(
            model_name='oidcclientextra',
            name='limited_permissions',
            field=models.ManyToManyField(blank=True, related_name='_oidcclientextra_limited_permissions_+', to='oidc.BaseTreeNode'),
        ),
    ]
