# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_provider', '0022_auto_20170331_1626'),
        ('oidc', '0006_auto_20170421_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClientGrantTypeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_client', models.ForeignKey(help_text='OIDC client for which it is allowed to generate token with limited functionality only', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oidc_provider.Client')),
                ('permissions', models.ManyToManyField(blank=True, related_name='_externalclientgranttypeconfiguration_permissions_+', to='oidc.BaseTreeNode')),
                ('source_client', models.ForeignKey(help_text='Source OIDC Client ID trying to generate token', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oidc_provider.Client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalclientgranttypeconfiguration',
            unique_together=set([('source_client', 'for_client')]),
        ),
    ]
