# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 23:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0007_auto_20170712_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcclientextra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_client_extra', to=settings.AUTH_USER_MODEL),
        ),
    ]
