# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0008_auto_20171214_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetreenode',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Permission/group node', 'verbose_name_plural': 'Permissions and groups tree'},
        ),
    ]
