# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0009_auto_20180204_2017'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='permissionnode',
            managers=[
            ],
        ),
    ]
