# Generated by Django 2.1.7 on 2019-03-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0010_auto_20180601_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetreenode',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='oidc.BaseTreeNode', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='externalclientgranttypeconfiguration',
            name='for_client',
            field=models.ForeignKey(help_text='OIDC client for which it is allowed to generate token with limited functionality only', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oidc_provider.Client'),
        ),
        migrations.AlterField(
            model_name='externalclientgranttypeconfiguration',
            name='source_client',
            field=models.ForeignKey(help_text='Source OIDC Client ID trying to generate token', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oidc_provider.Client'),
        ),
        migrations.AlterField(
            model_name='oidcclientextra',
            name='oidc_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extra', to='oidc_provider.Client'),
        ),
        migrations.AlterField(
            model_name='oidcclientextra',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.PROTECT, related_name='oidc_client_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialsecret',
            name='oidc_client_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_secrets', to='oidc.OidcClientExtra'),
        ),
    ]
