include "http-server"
include "persistence"
include "play"

akka {
  loglevel = INFO

  actor {
    provider = cluster

    serializers {
      circe-json = "stella.usercontext.services.StellaCirceAkkaSerializer"
    }

    serialization-bindings {
      "stella.usercontext.models.StellaCirceAkkaSerializable" = circe-json
    }
  }

  cluster {
    roles = ["userContext"]

    min-nr-of-members = 1

    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"

    sharding {
      number-of-shards = 100
      passivate-idle-entity-after = 5 minutes
    }
  }

  persistence {
    state {
      plugin = "jdbc-durable-state-store"
    }
  }
}
