include "application-base"

akka {
  remote.artery {
    canonical.hostname = 127.0.0.1
    canonical.port = 25520
  }

  cluster {
    seed-nodes = [
      "akka://UserContext@127.0.0.1:25520"
    ]
  }
}
