stella {
  user-context {
    server {
      start-akka-management-and-cluster-bootstrap = false
      start-akka-management-and-cluster-bootstrap = ${?USER_CONTEXT_START_AKKA_MANAGEMENT_AND_CLUSTER_BOOTSTRAP}

      # eventually we'll need some proper, secure way of storing this
      secret-box-hex-key = ea87def016584b3c84e5cdbea4dcc868ea87def016584b3c84e5cdbea4dcc868
      secret-box-hex-key = ${?USER_CONTEXT_SECRET_BOX_HEX_KEY}

      test-user-id = "b080f663-ed46-4b58-8c85-810cef8358ea"
      test-user-id = ${?USER_CONTEXT_TEST_USER_ID}

      test-project-id = "2353130a-e2b3-47e9-a2cb-3ade99f81b03"
      test-project-id = ${?USER_CONTEXT_TEST_PROJECT_ID}

      jwt {
        require-jwt-auth = true
        require-jwt-auth = ${?USER_CONTEXT_REQUIRE_JWT_AUTH}
        service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
        service-discovery-endpoint-uri = ${?JWT_SERVICE_DISCOVERY_URI}
        internal-service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
        internal-service-discovery-endpoint-uri = ${?JWT_INTERNAL_SERVICE_DISCOVERY_URI}
        issuer-cache-refresh-frequency = 1 hour
        issuer-cache-refresh-frequency = ${?USER_CONTEXT_ISSUER_CACHE_REFRESH_FREQUENCY}
        jwks-cache-refresh-frequency = 10 minutes
        jwks-cache-refresh-frequency = ${?USER_CONTEXT_JWKS_CACHE_REFRESH_FREQUENCY}
      }

      open-api {
        server-url = "http://localhost:14000"
        server-url = ${?USER_CONTEXT_OPEN_API_SERVER_URL}
      }

      user-context-entity-ask-timeout = 10 seconds
      user-context-entity-ask-timeout = ${?USER_CONTEXT_ENTITY_ASK_TIMEOUT}
    }
  }
}
