akka-persistence-jdbc {
  shared-databases {
    slick {
      profile = "slick.jdbc.PostgresProfile$"
      db {
        name = "user_context"
        name = ${?USER_CONTEXT_DB_NAME}
        host = "localhost"
        host = ${?USER_CONTEXT_DB_ADDRESS}
        port = 5432
        port = ${?USER_CONTEXT_DB_PORT}
        url = "jdbc:postgresql://"${akka-persistence-jdbc.shared-databases.slick.db.host}":"${akka-persistence-jdbc.shared-databases.slick.db.port}"/"${akka-persistence-jdbc.shared-databases.slick.db.name}"?reWriteBatchedInserts=true"
        user = "user_context"
        user = ${?USER_CONTEXT_DB_USERNAME}
        password = "user_context"
        password = ${?USER_CONTEXT_DB_PASSWORD}
        driver = "org.postgresql.Driver"
        numThreads = 5
        maxConnections = 5
        minConnections = 1
      }
    }
  }
}

jdbc-durable-state-store {
  use-shared-db = "slick"
}
