stella {
  rule-configurator {
    kafka {
      bootstrap-servers = "localhost:9092"
      bootstrap-servers = ${?RULE_CONFIGURATOR_KAFKA_BOOTSTRAP_SERVERS}

      serializer {
        schema-registry-url = "http://localhost:8081"
        schema-registry-url = ${?RULE_CONFIGURATOR_KAFKA_SCHEMA_REGISTRY_URL}
      }

      event-producer {
        topic-name = "dev-waysun-compact.event-configuration"
        topic-name = ${?RULE_CONFIGURATOR_KAFKA_PLATFORM_EVENTS_TOPIC_NAME}
        acks = "1"
        client-id = "rule-configuration.event"
        client-id = ${?RULE_CONFIGURATOR_EVENT_KAFKA_CLIENT_ID}
        compression-type = "gzip"
        max-in-flight-requests-per-connection = 1
        max-in-flight-requests-per-connection = ${?RULE_CONFIGURATOR_KAFKA_MAX_REQUESTS_PER_CONNECTION}
      }

      aggregation-producer {
        topic-name = "dev-waysun-compact.aggregation-rule-configuration"
        topic-name = ${?RULE_CONFIGURATOR_KAFKA_PLATFORM_AGGREGATIONS_TOPIC_NAME}
        acks = "1"
        client-id = "rule-configuration.aggregation"
        client-id = ${?RULE_CONFIGURATOR_AGGREGATION_KAFKA_CLIENT_ID}
        compression-type = "gzip"
        max-in-flight-requests-per-connection = 1
        max-in-flight-requests-per-connection = ${?RULE_CONFIGURATOR_KAFKA_MAX_REQUESTS_PER_CONNECTION}
      }

      achievement-producer {
        topic-name = "dev-waysun-compact.achievement-configuration"
        topic-name = ${?RULE_CONFIGURATOR_KAFKA_PLATFORM_ACHIEVEMENTS_TOPIC_NAME}
        acks = "1"
        client-id = "rule-configuration.achievement"
        client-id = ${?RULE_CONFIGURATOR_ACHIEVEMENT_KAFKA_CLIENT_ID}
        compression-type = "gzip"
        max-in-flight-requests-per-connection = 1
        max-in-flight-requests-per-connection = ${?RULE_CONFIGURATOR_KAFKA_MAX_REQUESTS_PER_CONNECTION}
      }
    }
  }
}
