slick {
  dbs {
    default {
      profile="slick.jdbc.PostgresProfile$"
      db {
        driver="org.postgresql.Driver"
        host="localhost"
        host=${?RULE_CONFIGURATOR_DB_ADDRESS}
        port=5432
        port=${?RULE_CONFIGURATOR_DB_PORT}
        name="rule_configurator"
        name=${?RULE_CONFIGURATOR_DB_NAME}
        url="jdbc:postgresql://"${slick.dbs.default.db.host}":"${slick.dbs.default.db.port}"/"${slick.dbs.default.db.name}
        username="rule_configurator"
        username=${?RULE_CONFIGURATOR_DB_USERNAME}
        password="rule_configurator"
        password=${?RULE_CONFIGURATOR_DB_PASSWORD}
      }
    }
  }
}
