play {
  http {
    context = "/"
    secret {
      key = "changeme"
      key = ${?APPLICATION_SECRET}
    }
    errorHandler = "tech.argyll.gmx.predictorgame.admin.CustomErrorHandler"
  }

  modules {
    enabled += tech.argyll.gmx.predictorgame.admin.Module
    enabled += tech.argyll.gmx.predictorgame.admin.modules.DbModule
  }

  filters {
    enabled += play.filters.cors.CORSFilter

    enabled += tech.argyll.gmx.predictorgame.common.play.filter.AccessLoggingFilter

    disabled += play.filters.headers.SecurityHeadersFilter
    disabled += play.filters.hosts.AllowedHostsFilter
    disabled += play.filters.csrf.CSRFFilter

  }
  i18n {
    langs = ["en"]
  }
}

app {
  dict {
    company {
      sportnation = 9577609b-d14f-4f14-ae6d-a6de017e8254
    }
  }
}