phoenix.streamlets.package = "phoenix.oddin.streamlets"

blueprint {

  streamlets {
    oddin-ingestor = ${phoenix.streamlets.package}.OddinMessageIngestor
    fixture-console = ${phoenix.streamlets.package}.FixtureChangedEventConsoleOutput
    market-console = ${phoenix.streamlets.package}.MarketChangedEventConsoleOutput
    settled-console = ${phoenix.streamlets.package}.MarketSettledEventConsoleOutput
    cancelled-console = ${phoenix.streamlets.package}.MarketCancelledEventConsoleOutput
  }

  topics {
    oddin-market-changes {
      topic.name = "phoenix-intake.oddin-markets"
      producers = [oddin-ingestor.market-events]
      consumers = [market-console.in]
    }
    oddin-fixture-changes {
      topic.name = "phoenix-intake.oddin-fixtures"
      producers = [oddin-ingestor.fixture-events]
      consumers = [fixture-console.in]
    }
    oddin-market-settlements {
      topic.name = "phoenix-intake.oddin-market-settlements"
      producers = [oddin-ingestor.settlement-events]
      consumers = [settled-console.in]
    }
    oddin-market-cancels {
      topic.name = "phoenix-intake.oddin-market-cancels"
      producers = [oddin-ingestor.cancel-events]
      consumers = [cancelled-console.in]
    }
  }
}
