nameOverride: "dev-lotto-backend-service"
fullnameOverride: "dev-lotto-backend-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: true
  type: ClusterIP
  port: 3020

ingressClassName: nginx

ingress:
  enabled: true
  paths:
    - path: /api/v1/.*
      pathType: ImplementationSpecific
      backend:
        service:
          name: dev-lotto-backend-service
          port:
            number: 3020

  name: alb-ingress-dev-lotto-backend-service
  namespace: dev
  annotations: {}
  hosts:
    - host: lotto-backend-service.local
      paths: []
  tls: []

env:
  NODE_ENV: development
  REDIS_HOST: redis.dev.eeg.viegg.net
  REDIS_PORT: 6379
  POSTGRES_HOST: rds.dev.eeg.viegg.net
  POSTGRES_USER: lotto
  WALLET_URL: http://dev-gstech-backend-service:3005/api/v1/wallet
  BACKEND_URL: http://dev-gstech-backend-service:3001
secretEnv:
  POSTGRES_PASSWORD:
    dev-lotto-backend-service: postgres-password
