nameOverride: "prod-gstech-worker-service"
fullnameOverride: "prod-gstech-worker-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: false

env:
  NODE_ENV: production
  MINIO_HOST: s3.eu-west-1.amazonaws.com
  MINIO_PORT: 443
  MINIO_USE_SSL: "true"
  MINIO_BUCKET_NAME: bucket-backend.prod.eeg
  MINIO_REGION: eu-west-1
  REDIS_HOST: redis-backend.prod.eeg.viegg.net
  REDIS_PORT: 6379
  POSTGRES_HOST: db-1.prod.eeg.viegg.net
  POSTGRES_USER: gstech
  KAFKA_ENABLED: "true"
  KAFKA_HOST: b-3.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com,b-2.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com,b-1.luckydino-prod-kafka.pofjr3.c3.kafka.eu-west-1.amazonaws.com
  KAFKA_PORT: 9094
  KAFKA_SSL: "true"
  KAFKA_AVRO_REGISTRY_HOST: http://prod-gstech-schema-registry
  PORT: 3001
  WALLET_PORT: 3005
  AFFILIATE_SYSTEM_URL: http://prod-affmore-backend-service:3034
  GAME_SERVER_URL: http://prod-gstech-walletserver-service:3004/api/v1
  COMPLIANCE_SERVER_URL: http://prod-gstech-compliance-service:3009/api/v1
  PAYMENT_SERVER_URL: http://prod-gstech-paymentserver-service:3007/api/v1
  CAMPAIGN_SERVER_PRIVATE_URL: http://prod-gstech-campaignserver-backend-service:3014/api/v1
  notifications_LD: https://api.luckydino.com
  notifications_CJ: https://api.casinojefe.com
  notifications_KK: https://kk-api.luckydino.com
  notifications_OS: https://os-api.luckydino.com
  notifications_FK: https://fk-api.luckydino.com
  notifications_SN: https://sn-api.luckydino.com
  notifications_VB: https://vb-api.luckydino.com
  OPTIMOVE_HOST: 'rds-idefix-optimove.prod.eeg.viegg.net'
  OPTIMOVE_DATABASE: idefix_optimove
  OPTIMOVE_USER: idefix
  OPTIMOVE_PASSWORD: 'GS[6GPSTfcx2KOSBJegOvUFjcii9zD00XbMqus8agt9flQMYwMH1ougHM8Is4xJBnVp/8dLNjr61e4=]'
  CAMPAIGN_SERVER_AUTH_TOKEN: 'GS[xZ/zWD5Fzs0NLQ+Ry9W/uxO6rManr2j6zu0REYhLJhhs69FemQMPgnJYOLzPkUjo34EVy3tBtYF8VauC6oVetz+X76J00hjV8yTCwL5w9IBFGCYLGA==]'
  CONTENT_SERVER_AUTH_TOKEN: 'GS[uHZY3vWFfrH7htZK3YQ1JgIxfHGr3qIqdo4n71LGPvXShG34oI4Ea+ttRBnvEnt6rL+VqTHDlMf00xcnlf/vrzYWlo89ukHbdZYGRQ==]'
  CONTENT_SERVER_URL: http://prod-gstech-contentserver-service:3017/api/v1
secretEnv:
  POSTGRES_PASSWORD:
    prod-gstech-worker-service: postgres-password
  MINIO_ACCESS_KEY:
    prod-gstech-backend-service: minio-access-key
  MINIO_SECRET_KEY:
    prod-gstech-backend-service: minio-secret-key
  PRIVATE_KEY:
    prod-common-secrets: private-key
