livenessProbe:
  httpGet:
    path: /api/v1/status
    port: 3011
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /api/v1/status
    port: 3011
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 10

image:
  repository: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/gstech-rewardserver
  pullPolicy: Always
  tag: "latest"

command: "yarn migrate && yarn workspace gstech-rewardserver serve"

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"

nodeSelector: {}

tolerations: []

affinity: {}

# Container
containerPort: 3011

prometheus:
  enabled: true
  path: /metrics
  interval: 40s
  portname: metrics

env:
  METRICS_PORT: 4001
  LOGGER_HOST: http://loki-write.monitoring.svc.cluster.local:3100
  LOGGER_SERVICE: rewardserver
