# Generated by Django 3.1.4 on 2021-03-22 21:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredEventsModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("P", "Pending"), ("S", "Send")], default="P", max_length=1)),
                ("correlation_id", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("send_at", models.DateTimeField(db_index=True)),
                ("data", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
