FLINK_HOST=localhost:8081

SCALA_VERSION=2.12
GROUP_ID=net.flipsports.gmx.streaming.internal.customers
ARTIFACT_ID=customer-operations-jobs
JOBS=('net.flipsports.gmx.streaming.internal.customers.operation.job.v1.FemaleCustomerAccountRegistrationTagSportnationJob' 'net.flipsports.gmx.streaming.sbtech.job.v1.CasinoBetReaderSportNationsJob')
JOBS_NAMES=('Female customer account  registration events on brand 154' 'Female customer account  registration events on brand 154')
