include "auditlog"
include "backoffice"
include "bets"
include "deployment"
include "dev-routes"
include "dge-views"
include "geocomply"
include "http-cors"
include "idcomply"
include "jwt"
include "kamon"
include "keycloak"
include "markets"
include "notes"
include "notifications"
include "openapi"
include "persistence"
include "phoenix-betgenius"
include "phoenix-mockdata"
include "phoenix-oddin"
include "prediction"
include "punters"
include "pxp"
include "reports"
include "twilio"
include "wallets"
include "web-sockets"

akka {
  loglevel = INFO

  actor {
    provider = cluster

    serializers {
      circe-json = "phoenix.core.serialization.PhoenixCirceAkkaSerializer"
    }

    serialization-bindings {
      "phoenix.CirceAkkaSerializable" = circe-json
    }
  }

  cluster {
    sharding {
      number-of-shards = 100
      healthcheck.names = ["Market", "Sport", "Bet", "Punter", "Wallet"]
      least-shard-allocation-strategy.rebalance-absolute-limit = 50
    }
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"

    # Let's keep the minimum number of members to one by default, for the sake of local runs.
    min-nr-of-members = 1
    min-nr-of-members = ${?REQUIRED_CONTACT_POINT_NR}
  }

  http.server.remote-address-header = on

  management.health-checks {
    # Note that we're currently using the default configuration
    # coming from the combination of reference.confs of akka-management, akka-management-cluster and akka-cluster-sharding:
    # - /alive: no specific check, always returns 200 OK
    # - /ready: 2 checks:
    #   - cluster-membership = akka.management.cluster.scaladsl.ClusterMembershipCheck
    #       Coming from akka-management-cluster, the current (default) behavior is to check
    #       whether the Akka node is in either Up or WeaklyUp status (akka.cluster.MemberStatus).
    #   - sharding           = akka.cluster.sharding.ClusterShardingHealthCheck
    #       Coming from akka-cluster-sharding, checks if all shard regions
    #       defined under `akka.cluster.sharding.healthcheck.names` are registered.
  }
}
