kamon.instrumentation.logback {
  # Controls if and how Context data should be copied into the MDC while events are being logged.
  mdc {

    # Enables copying of Context information into the MDC.
    copy {
      enabled = yes
      tags = yes

      # Contains the names of all Context entries that should be copied into the MDC.
      entries = ["punterID", "transactionID"]
    }
  }
}