phoenix {
  markets {
    oddin-feed-enabled = true
    projections {
      all-available-sports.name = "all-available-sports"
      all-available-fixtures.name = "all-available-fixtures"
      all-available-markets.name = "all-available-markets"
    }

    # As of 2021, HOCON doesn't reasonably support passing arrays directly via env vars, so we use comma-separate strings as a workaround :/
    filters {
      # Format as a comma separated value string. Values are SportIds, eg "s:p:1, s:p:2, s:p:3, s:p:10, s:p:11, s:p:12, s:p:13, s:p:15, s:p:16"
      sports-displayed-to-punters-by-default = ""
      sports-displayed-to-punters-by-default = ${?PHOENIX_SPORTS_DISPLAYED_TO_PUNTERS_BY_DEFAULT}

      # Format as a comma separated value string. Values are MarketTypes, written in upper snake case (with underscores, all caps).
      market-types-displayed-to-punters = ""
      market-types-displayed-to-punters = ${?PHOENIX_MARKET_TYPES_DISPLAYED_TO_PUNTERS}

      tournaments-displayed-to-punters-enabled = false
      tournaments-displayed-to-punters-enabled = ${?PHOENIX_TOURNAMENTS_DISPLAYED_TO_PUNTERS_FILTER_ENABLED}
    }
    selection-odds-upper-bound-inclusive = 101
    selection-odds-upper-bound-inclusive = ${?SELECTION_ODDS_UPPER_BOUND_INCLUSIVE}
  }
}
