phoenix {
  openapi {
    docs-relative-url = "/docs"
    docs-relative-url = ${?PHOENIX_OPENAPI_DOCS_RELATIVE_URL}

    api-base-url = "http://localhost:13552"
    api-base-url = ${?PHOENIX_OPENAPI_API_BASE_URL}
  }
}
