kind: ServiceAccount
apiVersion: v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install
    # We use a smaller weight than for ecr-docker-credentials-renewer pod so that the resources are created before the pod.
    "helm.sh/hook-weight": "10"
    # We can't delete the service account (and other resources defined in this file)
    # after running the hook since it's needed for the CronJob as well.
    "helm.sh/hook-delete-policy": before-hook-creation


{{- range .Values.targetNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, update, get, delete]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-docker-credentials-renewer
subjects:
  - kind: ServiceAccount
    name: ecr-docker-credentials-renewer
    namespace: "{{ $.Release.Namespace }}"
{{- end }}
