app {
  external {
    sbtech {
      betting-api {
        url = "https://sbapi.sbtech.com/"${app.external.sbtech.betting-api.operator}"/betting/v2"
        operator = "sportnation"
      }
    }
  }
}
