nameOverride: "prod-justwow-strapi-cms"
fullnameOverride: "prod-justwow-strapi-cms"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

serviceAccount:
  create: true
  name: "justwow-strapi-cms"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::743851384875:role/luckydino-prod-justwow-strapi-cms-s3

service:
  enabled: true
  type: ClusterIP
  port: 3000

ingressClassName: nginx

ingress:
  enabled: true

  name: prod-justwow-strapi-cms
  hosts:
  - host: strapi.justwow.com
    paths:
    - path: /
      pathType: Prefix
      serviceName: prod-justwow-strapi-cms
      servicePort: 3000

  annotations: {}

  tls: []

env:
  DATABASE_CLIENT: postgres
  DATABASE_TYPE: postgres
  DATABASE_HOST: luckydino-prod-rds-justwow-strapi-cms.cloxx4gelzda.eu-west-1.rds.amazonaws.com
  DATABASE_PORT: 5432
  DATABASE_USERNAME: strapi_cms
  DATABASE_NAME: strapi_cms
  DATABASE_SSL: false
  HOST: "0.0.0.0"
  PORT: 3000
  STRAPI_TELEMETRY_DISABLED: true
  NODE_ENV: "production"
  ENABLE_S3_UPLOAD: true
  AWS_BUCKET_NAME: "prod-justwow-strapi-cms-content"
  AWS_REGION: "eu-west-1"
secretEnv:
  DATABASE_PASSWORD:
    prod-justwow-strapi-cms: postgres-password
  JWT_SECRET:
    prod-justwow-strapi-cms: jwt-secret
  ADMIN_JWT_SECRET:
    prod-justwow-strapi-cms: admin-jwt-secret
  API_TOKEN_SALT:
    prod-justwow-strapi-cms: api-token-salt
  APP_KEYS:
    prod-justwow-strapi-cms: app-keys
