import App from "next/app";
import { appWithTranslation } from "i18n";
import { Components } from "@phoenix-ui/app";
import Head from "next/head";
import { appMenuItems } from "../config/menu";
import store from "../store";
import TagManager from "react-gtm-module";
import "antd/dist/antd.css";
import "@phoenix-ui/app/pxp-theme/theme.css";
import { useEffect } from "react";

const theme = {
  baseGutter: 10,
  spinnerBackgroundColor: "#da3931",
  spinnerContainerBackgroundColor: "rgba(19, 20, 20, 0.4)",
  uiComponents: {
    buttons: {
      primary: {
        backgroundColor: "#00b75b",
        hoverBackgroundColor: "#0c7b43",
        fontColor: "#ffffff",
        hoverFontColor: "#ffffff",
        borderColor: "#00b75b",
        hoverBorderColor: "#0c7b43",
        disabledBackgroundColor: "#404040",
        disbaledFontColor: "#ffffff",
        disabledBorderColor: "#404040",
      },
      default: {
        backgroundColor: "#ffffff",
        hoverBackgroundColor: "#c9caca",
        fontColor: "#000000",
        hoverFontColor: "#000000",
        borderColor: "#ffffff",
        hoverBorderColor: "#c9caca",
        disabledBackgroundColor: "#404040",
        disbaledFontColor: "#ffffff",
        disabledBorderColor: "#404040",
      },
      danger: {
        backgroundColor: "#da3931",
        hoverBackgroundColor: "#12DB79",
        fontColor: "#ffffff",
        hoverFontColor: "#ffffff",
        borderColor: "#da3931",
        hoverBorderColor: "#12DB79",
        disabledBackgroundColor: "#404040",
        disbaledFontColor: "#ffffff",
        disabledBorderColor: "#404040",
      },
    },
    modals: {
      backgroundColor: "#1f2021",
      titleColor: "#ffffff",
      inputColor: "#ffffff",
      paragraphColor: "#8d8d8d",
      primaryButtonBackgroundColor: "#00b75b",
      primaryButtonColor: "#ffffff",
      primaryButtonHoverBackgroundColor: "#0c7b43",
      defaultButtonBackgroundColor: "#ffffff",
      defaultButtonColor: "#000000",
      defaultButtonHoverBackgroundColor: "#c9caca",
      loginModal: {
        headerBackgroundColor: "#1f2021",
        headerColor: "#ffffff",
        signUpButtonBackgroundColor: "#ffffff",
        signUpButtonColor: "#000000",
        signUpButtonHoverBackgroundColor: "#c9caca",
      },
      registerModal: {
        loginInfoColor: "#ffffff",
        backButtonButtonBackgroundColor: "#2f3031",
        backButtonButtonBackgroundHoverColor: "rgba(47, 48, 49, 0.4)",
        backButtonColor: "#ffffff",
        loginButtonBackgroundColor: "#ffffff",
        loginButtonColor: "#000000",
        loginButtonHoverBackgroundColor: "#c9caca",
        stepsDividerBackgroundColor: "#000000",
        stepsIconBackgroundColor: "#8d8d8d",
        stepsIconColor: "#ffffff",
        stepsIconActiveBorderColor: "#00b75b",
        stepsIconActiveColor: "#00b75b",
        stepsIconActiveBackgroundColor: "#1a3729",
        stepsIconFinishedBackgroundColor: "#1f2021",
        stepsIconFinishedColor: "#00b75b",
        linkColor: "#8d8d8d",
        linkHoverColor: "#da3931",
      },
      idComplyModal: {
        cancelButtonButtonBackgroundColor: "#2f3031",
        cancelButtonButtonBackgroundHoverColor: "rgba(47, 48, 49, 0.4)",
        cancelButtonColor: "#ffffff",
      },
      infoModal: {
        iconColor: "#00b75b",
        buttonBackgroundColor: "#00b75b",
        buttonHoverBackgroudnColor: "#0c7b43",
      },
      errorModal: {
        iconColor: "#da3931",
        buttonBackgroundColor: "#da3931",
        buttonHoverBackgroudnColor: "#00b75b",
      },
      warningModal: {
        iconColor: "#faad14",
        buttonBackgroundColor: "#faad14",
        buttonHoverBackgroudnColor: "#cc8d10",
      },
      geocomplyModal: {
        headerIconBackgroundColor: "#154a31",
        downloadButtonBackgroundColor: "#3d3d3d",
        downloadButtonHoverBackgroundColor: "#153124",
        downloadButtonBorderColor: "#3d3d3d",
        downloadButtonHoverBorderColor: "#00b75b",
        downloadButtonColor: "#ffffff",
        downloadButtonHoverColor: "#ffffff",
        downloadButtonDividerColor: "#4d4d4d",
        downloadButtonDividerHoverColor: "#0c6a3b",
      },
    },
    input: {
      fontColor: "rgb(255, 255, 255)",
      backgroundColor: "#3a3a3a",
      borderColor: "#000000",
      backgroundHoverColor: "#1f2623",
      borderHoverColor: "#00b75b",
      errorBackgroundColor: "#18191a",
      errorBorderColor: "#da3931",
      errorFontColor: "#da3931",
    },
    select: {
      fontColor: "#ffffff",
      backgroundColor: "#2F3031",
      hoverBackgroundColor: "#181818",
      activeBackgroundColor: "#18191A",
      activeIcon: "/images/check.svg",
    },
    checkbox: {
      color: "#8a8a8a",
      backgroundColor: "#47484d",
      tickColor: "#ffffff",
      borderColor: "#404040",
      hoverBackgroudColor: "#2a2a2a",
      checkedBackgroundColor: "#2a2a2a",
    },
  },
  menu: {
    userIcon: "/images/user.svg",
    mobileUserIcon: "/images/user.svg",
    userIconHover: "/images/user-hover.svg",
    backgroundColor: "#000000",
    mobileBackgroundColor: "#000000",
    loginButtonBorderColor: "transparent",
    loginMobileButtonBacgroundColor: "#18191a",
    loginMobileButtonColor: "#ffffff",
    loginMobileButtonBorderColor: "#ffffff",
    signUpButtonBorderColor: "transparent",
    signUpMobileButtonBacgroundColor: "#00b75b",
    signUpMobileButtonColor: "#ffffff",
    signUpMobileButtonBorderColor: "transparent",
    active: "#ffffff",
    activeBorder: "#da3931",
    activeHover: "#da3931",
    inactiveAnchor: "#8d8d8d",
    loginButtonColor: "#00ff2b",
    loginButtonBackgroundColor: "#272727",
    loginButtonHoverBorder: "#00b75b",
    loginButtonHoverBackgroundColor: "#272727",
    loginButtonHoverColor: "#00b75b",
    signUpButtonBackgroundColor: "#da3931",
    signUpButtonHoverBackgroundColor: "#00b75b",
    balanceBackgroundColor: "#00b75b",
    balanceHoverBackgroundColor: "rgba(0, 183, 91, 0.5)",
    balanceBorderColor: "#00b75b",
    iconContainerBorderLeft: "#1e1e1e",
    menuCollapseColor: "#8d8d8d",
    bellColor: "#ffffff",
    rgColor: "#ffffff",
    rgLogo: "/images/rg_logo.svg",
    languageSelector: {
      borderColor: "#2A2A2A",
      fontColor: "#FFFFFF",
      arrowColor: "#FFFFFF",
    },
  },
  statusBar: {
    messageColor: "#ffffff",
    descriptionColor: "#8d8d8d",
    selfExcludeBackgroundColor: "#922526",
    selfExcludeBorderColor: "#DA3931",
    coolOffBackgroundColor: "#705705",
    coolOffBorderColor: "#EBBF2F",
  },
  sidebar: {
    backgroundColor: "#0f0f0f",
    borderColor: "#000000",
    inactiveGameColor: "#6e6f6f",
    activeGameColor: "#ffffff",
    collapsedMenuColor: "#000000",
    selectedCollapsedMenuItemColor: "#da3931",
    collapsedMenuItemHoverColor: "#da3931",
    menuItemHoverColor: "#da3931",
    selectedCollapsedMenuShadow:
      "linear-gradient(to right, #6d0412, rgba(15, 15, 15, 0) 20%)",
    selectedCollapsedMenuItemShadow:
      "linear-gradient(to right, #343434, rgba(15, 15, 15, 0) 20%)",
    customHomeIcon: "/images/home_gray.svg",
    customInPlayLogo: "/images/clock_gray.svg",
    customUpComingLogo: "/images/calendar_gray.svg",
    badgeColor: "#18191a",
    badgeFontColor: "#ffffff",
  },
  footer: {
    paymentColor: "#FFFFFF",
    mainFooterColor: "#0f0f0f",
    lowerFooterColor: "#18191a",
    secondaryFooterfontColor: "#8d8d8d",
    mainFooterfontColor: "#8d8d8d",
    mobileDividerColor: "#000000",
    mobileFooterColor: "#0f0f0f",
    mobileFooterFontColor: "#ffffff",
    mobileFooterBorderColor: "#1e1e1e",
    mobileFooterHoverColor: "#cf001b",
    socialIconsColor: "#8d8d8d",
    socialIconsHoverColor: "#cf001b",
    linkHoverColor: "#da3931",
    shouldDisplayLogo: true,
  },
  pagination: {
    arrowColor: "#ffffff",
    numberColor: "#ffffff",
    selectedItemNumberColor: "#ffffff",
    selectedItemBackgroundColor: "#da3931",
    disabledArrowColor: "#6e6f6f",
  },
  betslip: {
    emptyBetslipMessageColor: "#ffffff",
    mobileBetslipTitleColor: "#ffffff",
    mobileBetslipHeaderBackgroundColor: "#00b75b",
    badgeFontColor: "#1e1e1e",
    backgroundColor: "#1f2021",
    activeTabBackgroundColor: "#2a2a2a",
    inactiveTabBackgroundColor: "#1f2021",
    activeTabBorderBottom: "#da3931",
    activeTabColor: "#ffffff",
    inactiveTabColor: "#8d8d8d",
    tabsDividerColor: "#000000",
    tabBadgeBackgroundColor: "#ffffff",
    tabBadgeColor: "#1e1e1e",
    secondaryTabsBackgroundColor: "#141415",
    listItemBackgroundColor: "#1f2021",
    listItemInputBorderColor: "#1f2021",
    listItemBorderBottomColor: "#000000",
    listItemSelectionNameColor: "#dddddd",
    listItemMatchWinnerTitle: "#8a8a8a",
    listItemOddsColor: "#dddddd",
    loadingSpinnerColor: "#da3931",
    boxShadowColor: "transparent",
    listItemRemoveButtonColor: "#b7b7b7",
    listItemRemoveButtonHoverColor: "#da3931",
    listItemWinnerNameColor: "#dddddd",
    listItemInputBackgroundColor: "#0a0a0a",
    listItemInputColor: "#dddddd",
    listItemToReturn: {
      titleColor: "#767676",
      valueColor: "#00b75b",
    },
    iconsColor: "#ffffff",
    summary: {
      totalStakeTitleColor: "#8a8a8a",
      totalStakeValueColor: "#ffffff",
      possibleReturnTitleColor: "#dddddd",
      possibleReturnValueColor: "#00b75b",
      currencyColor: "#ffffff",
      clearBetslipColor: "#8d8d8d",
      clearBetslipHoverColor: "#da3931",
    },
    acceptOddsChangeFontColor: "#737373",
    acceptOddsContainerBoxShadowColor: "#171717",
    cancelOddsChangeButtonBackgroundColor: "#3d3d3d",
    cancelOddsChangeButtonHoverBackgroundColor: "#434343",
    errors: {
      notEnoughMoneyErrorColor: "#EBBF2F",
    },
    listItemInputHoverButtons: {
      backgroundColor: "#47484d",
      iconColor: "#c2c2c2",
      iconHoverColor: "#00b75b",
      buttonsDividerColor: "black",
    },
  },
  content: {
    backgroundColor: "#18191a",
    mainFontColor: "#ffffff",
    secondaryFontColor: "#8d8d8d",
    fixtureList: {
      backgroundColor: "#18191a",
      hoverBackgroudColor: "#2E2E30",
      mainFontColor: "#ffffff",
      dividerColor: "#000000",
      inactiveTabColor: "#8d8d8d",
      activeTabBorderBottom: "#da3931",
      tabsContainerBackgroundColor: "transparent",
      headerBackgroundColor: "#131414",
      headerColor: "#787979",
      gameNameColor: "#ffffff",
      tournamentNameColor: "#878787",
      scoreColor: "#ffffff",
      teamNameColor: "#ffffff",
      betButtonBackgroundColor: "#252626",
      betButtonBorderColor: "#252626",
      betButtonColor: "#ffffff",
      marketCountButtonColor: "#ffffff",
      highlightedBetButtonBackgroundColor: "rgba(218, 57, 49, 0.1)",
      highlightedBetButtonBorderColor: "#da3931",
      highlightedBetButtonColor: "#ffffff",
      hoverBetButtonBackgroundColor: "#3b3b3b",
      hoverBetButtonBorderColor: "#3b3b3b",
      hoverBetButtonColor: "#ffffff",
      gradientFromColor: "#6d0412",
      gradientToColor: "rgba(15, 15, 15, 0)",
      collapseInactiveArrowColor: "#6e6f6f",
      liveBadgeGradientColor: "#ff2626",
      liveBadgeBackgroundColor: "#ff3131",
      liveBadgeColor: "#ffffff",
      loadMoreButtonColor: "#ffffff",
      loadMoreButtonHoverColor: "#ffffff",
      loadMoreButtonBackgroundColor: "#da3931",
      loadMoreButtonHoverBackgroundColor: "#D22D25",
      loadMoreButtonShadowColor: "#74201c",
      loadMoreButtonHoverShadowColor: "#74201c",
      fixtureRowBackgroundColor: "transparent",
      statuses: {
        notStartedColor: "#8d8d8d",
        endedColor: "#da3931",
        liveColor: "#da3931",
        suspendedColor: "#ffdc35",
        finishedColor: "#da3931",
        cancelledColor: "#da3931",
        abandonedColor: "#da3931",
        delayedColor: "#ffdc35",
        unknownColor: "#ffdc35",
        postponedColor: "#ffdc35",
        interruptedColor: "#da3931",
        finalizedColor: "#00b75b",
        closedColor: "#da3931",
      },
    },
    changePassword: {
      backgroundColor: "#1f2021",
    },
    account: {
      titleColor: "#ffffff",
      pageSubtitleColor: "#7b7b7c",
      noDataContainerBackgroundColor: "#1f2021",
      noDataContainerFontColor: "#8d8d8d",
      limits: {
        backgroundColor: "#1f2021",
        mainFontColor: "#6e6f6f",
        textUnderInputColor: "#00b75b",
        dividerColor: "#000000",
        limitsTitleColor: "#ffffff",
        inputBackgroundColor: "#1f2021",
        inputBorderColor: "#000000",
        breakButtonHoverBackgroundColor: "#00b75b",
        breakMessageColor: "#ffffff",
        breakTimeInfoColor: "#6e6f6f",
        breakTimeColor: "#da3931",
      },
      accountHistory: {
        secondaryTitleColor: "#7b7b7c",
        backgroundColor: "#1f2021",
        dividerColor: "#18191a",
        successBadgeBackgroundColor: "#00b75b",
        pendingBadgeBackgroundColor: "#ebbf2f",
        rejectedBadgeBackgroundColor: "#da3931",
        nameColor: "#8d8d8d",
        valueColor: "#eeeeee",
        timeColor: "#8d8d8d",
        badgeFontColor: "#ffffff",
      },

      notifications: {
        backgroundColor: "#1f2021",
        nameFont: "#7b7b7c",
        valueFont: "#ffffff",
        dividerColor: "#000000",
        buttonBackgroundColor: "#00b75b",
        buttonHoverBackgroundColor: "#0c7b43",
      },
      betHistory: {
        subtitleColor: "#7b7b7c",
        backgroundColor: "#1f2021",
        betPartBackgroundColor: "#18191a",
        detailsButtonBackgroundColor: "#0f0f0f",
        detailsButtonHoverBackgroundColor: "#313133",
        detailsButtonColor: "#ffffff",
        dividerColor: "#000000",
        listItemKeyColor: "#8d8d8d",
        listItemValueColor: "#eeeeee",
        periodNameColor: "#8d8d8d",
        betPartTitleColor: "#8d8d8d",
        marketNameColor: "#ffffff",
        selectionNameColor: "#8d8d8d",
        oddsNameColor: "#ffffff",
        legOddsColor: "#8d8d8d",
        betPartValueColor: "#ffffff",
        dateColor: "#ffffff",
        tag: {
          fontColor: "#ffffff",
          cancelledStatusColor: "#da3931",
          voidedStatusColor: "#ebbf2f",
          openStatusColor: "#4483bc",
          lostResultColor: "#7b7b7c",
          wonResultColor: "#00b75b",
        },
      },
    },
    personalData: {
      backgroundColor: "#1f2021",
      mainFontColor: "#ffffff",
      nameFont: "#7b7b7c",
      changeColor: "#8d8d8d",
      changeHoverColor: "#da3931",
      dividerColor: "#000000",
      termsDateColor: "#da3931",
      buttonBackgroundColor: "#da3931",
      buttonHoverBackgroundColor: "#00b75b",
      buttonFontColor: "#ffffff",
      buttonHoverFontColor: "#ffffff",
      deleteModalTitleColor: "#ffffff",
      deleteModalMessageColor: "#e4e4e4",
    },
    settings: {
      nameFont: "#7b7b7c",
      backgroundColor: "#1f2021",
      dividerColor: "#000000",
    },
    rgLimitsHistory: {
      containerBackgroundColor: "#1f2021",
    },
    staticPage: {
      containerBackgroundColor: "#18191a",
      titleColor: "#ffffff",
      subtitleColor: "#8d8d8d",
      h5Color: "#da3931",
      contentColor: "#8d8d8d",
      table: {
        thBorderColor: "#151616",
        thBackgroundColor: "#151616",
        thColor: "#ffffff",
        tdBackgroundColor: "#1e1f1f",
        tdColor: "#8d8d8d",
        rowsDividerColor: "#0f0f0f",
        tdSideBorders: "#0f0f0f",
        thDivider: "#0f0f0f",
        rowBottomBorderColor: "#0f0f0f",
        rowTopBorderColor: "#0f0f0f",
      },
      list: {
        liColor: "#8d8d8d",
        markerColor: "#00b75b",
      },
      paragraphColor: "#8d8d8d",
    },
    table: {
      thBackgroundColor: "#151616",
      thColor: "#ffffff",
      trNthChildBackgroundColor: "#1f2021",
      tr2NthChildBackgroundColor: "#18191a",
      cellColor: "#d4d4d4",
      tdSideBordersColor: "#151616",
    },
  },
  mobileLogo: {
    source: "/images/logo.svg",
    width: 60,
  },
  logo: {
    source: "/images/logo.svg",
    width: 60,
  },
  globalForm: {
    titleColor: "#ffffff",
    backgroundColor: "#1f2021",
    fontColor: "#7b7b7c",
    inputBackgroundColor: "#3a3a3a",
    inputBorderColor: "#000000",
    inputErrorBackgroundColor: "rgba(218, 57, 49, 0.08)",
    errorBackgroundColor: "#f8d9d8",
    alertBackgroundColor: "#f8d9d8",
    alertColor: "#da3931",
    alertLinkColor: "#21276f",
    inputErrorBorderColor: "#da3931",
    inputErrorColor: "#da3931",
    defaultInputBackgroundHoverColor: "rgba(0, 183, 91, 0.04)",
    defaultInputBorderHoverColor: "#00b75b",
    linkColor: "#8d8d8d",
    linkHoverColor: "#da3931",
    switchBackgroundColor: "#47484d",
    switchUncheckedColor: "#000000",
    switchCheckedColor: "#00b75b",
    dropdownDisabledColor: "#7b7b7c",
    radioBackgroundColor: "#2a2a2a",
    radioBorderColor: "#7b7b7c",
    radioLabelColor: "#7b7b7c",
    radioTickColor: "#8a8a8a",
    scrollbarBackgroundColor: "#363737",
    scrollbarThumbColor: "#da3931",
  },
  modal: {
    backgroundColor: "#1f2021",
    titleColor: "#ffffff",
    inputColor: "#ffffff",
    paragraphColor: "#8d8d8d",
    loginModal: {
      headerBackgroundColor: "#1f2021",
      headerColor: "#ffffff",
      signUpButtonBackgroundColor: "#ffffff",
      signUpButtonColor: "#000000",
      signUpButtonHoverBackgroundColor: "#c9caca",
    },
    registerModal: {
      loginInfoColor: "#ffffff",
      backButtonButtonBackgroundColor: "#2f3031",
      backButtonButtonBackgroundHoverColor: "rgba(47, 48, 49, 0.4)",
      backButtonColor: "#ffffff",
      stepsDividerBackgroundColor: "#000000",
      stepsIconBackgroundColor: "#8d8d8d",
      stepsIconColor: "#ffffff",
      stepsIconActiveBorderColor: "#00b75b",
      stepsIconActiveColor: "#00b75b",
      stepsIconActiveBackgroundColor: "#1a3729",
      stepsIconFinishedBackgroundColor: "#1f2021",
      stepsIconFinishedColor: "#00b75b",
      linkColor: "#8d8d8d",
      linkHoverColor: "#da3931",
    },
    idComplyModal: {
      cancelButtonButtonBackgroundColor: "#2f3031",
      cancelButtonButtonBackgroundHoverColor: "rgba(47, 48, 49, 0.4)",
      cancelButtonColor: "#ffffff",
    },
    forgotPasswordModal: {
      messageColor: "#7b7b7c",
    },
    infoModal: {
      iconColor: "#00b75b",
      buttonBackgroundColor: "#00b75b",
      buttonHoverBackgroudnColor: "#0c7b43",
    },
    errorModal: {
      iconColor: "#da3931",
      buttonBackgroundColor: "#da3931",
      buttonHoverBackgroudnColor: "#00b75b",
    },
    warningModal: {
      iconColor: "#faad14",
      buttonBackgroundColor: "#faad14",
      buttonHoverBackgroudnColor: "#cc8d10",
    },
    geocomplyModal: {
      headerIconBackgroundColor: "#154a31",
      downloadButtonBackgroundColor: "#3d3d3d",
      downloadButtonHoverBackgroundColor: "#153124",
      downloadButtonBorderColor: "#3d3d3d",
      downloadButtonHoverBorderColor: "#00b75b",
      downloadButtonColor: "#ffffff",
      downloadButtonHoverColor: "#ffffff",
      downloadButtonDividerColor: "#4d4d4d",
      downloadButtonDividerHoverColor: "#0c6a3b",
    },
  },
  popover: {
    borderColor: "#da3931",
    backgroundColor: "#0a0a0a",
    fontColor: "#ffffff",
  },
  cashier: {
    headerBackgroundColor: "#1f2021",
    headerFontColor: "#ffffff",
    dividerColor: "#000000",
    dividerTextColor: "#ffffff",
    bodyBackgroundColor: "#1f2021",
    tabsHeaderBackgroundColor: "#1f2021",
    tabActiveColor: "#ffffff",
    inactiveTabColor: "#8d8d8d",
    activeTabBorderColor: "#da3931",
    tabsContentBackgroundColor: "#1f2021",
  },
  result: {
    backgroundColor: "#1f2021",
    titleColor: "#ffffff",
    subtitleColor: "#8d8d8d",
    primaryButtonBackgroundColor: "#00b75b",
    primaryButtonHoverBackgroundColor: "#0c7b43",
    primaryButtonBorderColor: "#00b75b",
    primaryButtonHoverBorderColor: "#0c7b43",
    primaryButtonHoverColor: "#ffffff",
    secondaryButtonBackgroundColor: "#3a3a3a",
    secondaryButtonHoverBackgroundColor: "#3a3a3a",
    secondaryButtonBorderColor: "#3a3a3a",
    secondaryButtonHoverBorderColor: "#00b75b",
    secondaryButtonColor: "#ffffff",
    secondaryButtonHoverColor: "#00b75b",
    successSvgBackgroundColor: "#12472c",
    errorSvgBackgroundColor: "rgb(80, 37, 33)",
    warningSvgBackgroundColor: "#564d2e",
    infoSvgBackgroundColor: "#2c567c",
  },
  landingPage: {
    deviceWidth: {
      large: "1000px",
      medium: "768px",
      small: "425px",
    },
    colors: {
      white: "#ffffff",
      black: "#000000",
      headerBack: "#0f0f0f",
      mobileMenuBack: "rgba(0, 0, 0, 0.85)",
      buttonPrimary: "#00b75b",
      buttonPrimaryHover: "#0c7b43",
      buttonSecondary: "#272727",
      buttonSecondaryHover: "#000000",
      paraTextColor: "#f1f1f1",
      scrollUpButtonHover: "#00b75b",
    },
  },
};

function PhoenixApp(props) {
  useEffect(() => {
    TagManager.initialize({ gtmId: "GTM-PJSSBJG" });
  }, []);

  return (
    <>
      <Head>
        <script
          type="text/javascript"
          src="/js/geocomply/geocomply-client.min.js"
        ></script>
        <script
          type="text/javascript"
          src="https://cdn.geocomply.com/oobee/v2.18/oobee.js"
        ></script>
      </Head>
      <Components.App
        {...props}
        store={store}
        theme={theme}
        menuItems={appMenuItems}
      />
    </>
  );
}

PhoenixApp.getInitialProps = async (appContext) => ({
  ...(await App.getInitialProps(appContext)),
});

// export default PhoenixApp;
export default appWithTranslation(PhoenixApp);
