FLINK_HOST=10.4.73.16:8081

SCALA_VERSION=2.12
GROUP_ID=net.flipsports.gmx.streaming.internal.customers
ARTIFACT_ID=customer-operations-jobs
JOBS=('net.flipsports.gmx.streaming.internal.customers.operation.job.v1.CustomerStateChangeStreamSportnationJob')
JOBS_NAMES=('Customer state change operation events on brand sportnation')
