#!groovy

void notifyGithub(String description, String status) {
    status = status ?: 'SUCCESS'
    githubNotify(
            description: description,
            context: env.GITHUB_NOTIFICATION_CONTEXT,
            account: env.GITHUB_ACCOUNT,
            repo: env.GITHUB_REPO,
            credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
            targetUrl: env.RUN_DISPLAY_URL,
            status: status
    )
}


// build status constants: https://www.jenkins.io/doc/book/glossary/#build-status
def notifySlack(String branch, String buildStatus) {
   if (branch in ['develop', 'master']) {

    // Build status of null means success.
    buildStatus = buildStatus ?: 'SUCCESS'

    def color

    if (buildStatus == 'STARTED') {
        color = '#D4DADF'
    } else if (buildStatus == 'SUCCESS') {
        color = '#BDFFC3'
    } else if (buildStatus == 'STABLE') {
        color = '#BDFFC3'
    } else if (buildStatus == 'UNSTABLE') {
        color = '#FFFE89'
    } else { // FAILED or ABORTED
        color = '#FF9FA1'
    }

    def message = "${buildStatus}: <${env.RUN_DISPLAY_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>"

    slackSend(color: color, message: message, channel: env.SLACK_NOTIFICATION_CHANNEL)
   }
}

void withGithubStatusUpdates(Closure<Void> block) {
    gitStatusWrapper(
            description: env.STAGE_NAME,
            gitHubContext: env.GITHUB_NOTIFICATION_CONTEXT,
            account: env.GITHUB_ACCOUNT,
            repo: env.GITHUB_REPO,
            credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
            targetUrl: env.RUN_DISPLAY_URL
    ) {
        block()
    }
}


//noinspection GroovyAssignabilityCheck
properties(
        env.BRANCH_NAME == 'develop'
                ? [disableConcurrentBuilds()]
                : []
)

pipeline {
    agent {
        label 'ecs-ec2-java'
    }


    environment {
        // github status notifications
        GITHUB_ACCOUNT = 'flipadmin'
        GITHUB_REPO = 'gmx-streaming-data-customer'
        GITHUB_API_TOKEN_CREDENTIALS_ID = 'CICD-GitHub-API-token'
        GITHUB_NOTIFICATION_CONTEXT = 'Jenkins Build'

        SLACK_NOTIFICATION_CHANNEL = '#ci-gmx-deployment'

        // build
        SBT_HOME = tool name: 'sbt', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'
        PATH = "${env.SBT_HOME}/bin:${env.HOME}/.local/bin:${env.PATH}"

        // github tags
        COMMIT_HASH = shOutput("git rev-parse HEAD")
        GITHUB_API_URL = "https://api.github.com/repos/${env.GITHUB_ACCOUNT}/${env.GITHUB_REPO}"
        GITHUB_API_REFS_URL = "${env.GITHUB_API_URL}/git/refs"

    }

    stages {

        stage('Notify GitHub') {
            steps {
                notifyGithub('Starting', 'PENDING')
            }
        }

        stage('Checkout') {
            steps {
                notifySlack(env.BRANCH_NAME, 'STARTED')

                withGithubStatusUpdates {
                    script {
                        currentBuild.displayName = "#${env.BUILD_NUMBER} for ${env.BRANCH_NAME}"
                    }
                    checkout([
                            $class                           : 'GitSCM',
                            branches                         : scm.branches,
                            doGenerateSubmoduleConfigurations: scm.doGenerateSubmoduleConfigurations,
                            extensions                       : [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0, reference: '']],
                            userRemoteConfigs                : scm.userRemoteConfigs,
                    ])
                }
            }
        }

        stage('Update dependencies') {
            steps {
                withGithubStatusUpdates {
                    // -batch to prevent sbt from waiting on user input in case the project model is invalid
                    sh 'sbt -batch update'
                }
            }
        }

        stage('Compile production code') {
            steps {
                withGithubStatusUpdates {
                    sh 'sbt compile'
                }
            }
        }

        stage('Compile test code') {
            steps {
                withGithubStatusUpdates {
                    sh 'sbt test:compile'
                }
            }
        }


        stage('Check scalafix rules') {
            steps {
                withGithubStatusUpdates {
                    sh 'sbt "scalafixAll --check"'
                }
            }
        }

        stage('Run unit & integration tests') {
            steps {
                withGithubStatusUpdates {
                    sh 'sbt test:test'
                }
            }
        }

        stage('Adding build tag to git') {
            when {
                anyOf {
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                withGithubStatusUpdates {
                    withCredentials([
                            usernamePassword(
                                    credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
                                    usernameVariable: 'GITHUB_USERNAME',
                                    passwordVariable: 'GITHUB_PASSWORD'
                            )
                    ]) {
                        sh "curl -f -X POST -d '{\"ref\": \"refs/tags/${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}\", \"sha\":\"${env.COMMIT_ID}\"}' -H \"Accept: application/vnd.github.v3+json\" -u \"username:${GITHUB_PASSWORD}\" ${env.GITHUB_API_REFS_URL}"
                    }
                }
            }
        }

        stage('Publish to Nexus') {
            when {
                branch 'master'
            }
            steps {
                withGithubStatusUpdates {
                    sh './ci/prepare-release-version ' + params.releaseVersionSegmentToUpdate
                    script {
                        RELEASE_VERSION = shOutput('git describe --exact-match --abbrev=0 --tags')
                    }
                    echo "About to release version: ${RELEASE_VERSION}"
                    withCredentials([usernamePassword(
                            credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
                            usernameVariable: 'GITHUB_USERNAME',
                            passwordVariable: 'GITHUB_PASSWORD')
                    ]) {
                        sh "curl -f -X POST -d '{\"ref\": \"refs/tags/${RELEASE_VERSION}\", \"sha\":\"${env.COMMIT_HASH}\"}' -H \"Accept: application/vnd.github.v3+json\" -u \"username:${GITHUB_PASSWORD}\" ${env.GITHUB_API_REFS_URL}"
                    }
                    sh 'sbt "+ publish"'
                }
            }
        }
    }

    post {
        success {
            // This is to ensure that the name of the last executed stage
            // doesn't linger in GitHub's CI status once the pipeline is complete.
            notifyGithub('Complete', 'SUCCESS')
        }

        always {
            notifySlack(env.BRANCH_NAME, currentBuild.result)
        }
    }
}
