# Generated by Django 2.1.3 on 2018-12-19 19:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePartnerConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("is_active", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("PROCESSING", "Processing"), ("ERROR", "Error"), ("DONE", "Done")],
                        db_index=True,
                        default="NEW",
                        max_length=11,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("wallet_operation_id", models.CharField(blank=True, max_length=60)),
                ("process_id", models.CharField(blank=True, max_length=40)),
                ("checkout_amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                (
                    "user",
                    models.ForeignKey(null=True, on_delete=True, related_name="orders", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLines",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subtype_validation",
                    models.CharField(
                        choices=[("INT", "integer field"), ("DECIMAL", "decimal field"), ("CHAR", "char field")],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "baseproduct_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="virtual_shop.BaseProduct",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("virtual_shop.baseproduct",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "baseproduct_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="virtual_shop.BaseProduct",
                    ),
                ),
                ("subtype_raw", models.CharField(max_length=60)),
            ],
            options={
                "abstract": False,
            },
            bases=("virtual_shop.baseproduct",),
        ),
        migrations.CreateModel(
            name="SbTechPartnerConfiguration",
            fields=[
                (
                    "basepartnerconfiguration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="virtual_shop.BasePartnerConfiguration",
                    ),
                ),
                ("token_url", models.URLField()),
                ("http_user", models.CharField(blank=True, max_length=120)),
                ("http_password", models.CharField(blank=True, max_length=120)),
                ("token_prefix", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("virtual_shop.basepartnerconfiguration",),
        ),
        migrations.AddField(
            model_name="producttype",
            name="partner_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_types",
                to="virtual_shop.BasePartnerConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="virtual_shop.BaseProduct"
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="order_lines", to="virtual_shop.Order"
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_virtual_shop.baseproduct_set+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="basepartnerconfiguration",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_virtual_shop.basepartnerconfiguration_set+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="products", to="virtual_shop.ProductType"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="virtual_shop.Product"
            ),
        ),
    ]
