# Generated by Django 2.1.3 on 2018-12-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="products",
            new_name="package_product",
        ),
    ]
