# Generated by Django 2.1.3 on 2018-12-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0002_auto_20181219_2024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="base_product", to="virtual_shop.BaseProduct"
            ),
        ),
    ]
