# Generated by Django 2.1.3 on 2018-12-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0004_auto_20181220_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kurwa_dupa",
                related_query_name="kurwa_dupa",
                to="virtual_shop.BaseProduct",
            ),
        ),
    ]
