# Generated by Django 2.1.3 on 2018-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0006_auto_20181220_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_token",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
