# Generated by Django 2.1.3 on 2018-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0007_order_status_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
