# Generated by Django 2.1.3 on 2018-12-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0008_auto_20181220_1626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status_token",
        ),
    ]
