# Generated by Django 2.1.3 on 2018-12-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0009_remove_order_status_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("NEW", "New"), ("PROCESSING", "Processing"), ("ERROR", "Error"), ("SUCCESS", "Success")],
                db_index=True,
                default="NEW",
                max_length=11,
            ),
        ),
    ]
