# Generated by Django 2.1.3 on 2019-01-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0010_auto_20181220_2336"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="wallet_operation_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="process_id",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
