# Generated by Django 2.1.3 on 2019-01-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0012_orderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="order_history_set", to="virtual_shop.Order"
            ),
        ),
    ]
