# Generated by Django 2.1.3 on 2019-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0013_auto_20190103_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbtechpartnerconfiguration",
            name="pc_endpoint",
            field=models.CharField(default="abc", max_length=24),
            preserve_default=False,
        ),
    ]
