# Generated by Django 2.1.3 on 2019-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0014_sbtechpartnerconfiguration_pc_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sbtechpartnerconfiguration",
            name="pc_endpoint",
            field=models.CharField(max_length=255),
        ),
    ]
