# Generated by Django 2.1.3 on 2019-01-09 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0016_purchasedproductsmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedproductsmodel",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=True, related_name="user_purchased_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
