# Generated by Django 2.1.3 on 2019-01-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0017_auto_20190109_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasedproductsmodel",
            options={"verbose_name": "Purchased product", "verbose_name_plural": "Purchased products"},
        ),
        migrations.AlterModelOptions(
            name="sbtechpartnerconfiguration",
            options={
                "verbose_name": "SbTech partner configuration",
                "verbose_name_plural": "SbTech partner configuration",
            },
        ),
    ]
