# Generated by Django 2.1.3 on 2019-01-14 17:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0017_auto_20190109_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasedproductsmodel",
            options={"verbose_name": "Purchased product", "verbose_name_plural": "Purchased products"},
        ),
        migrations.AlterModelOptions(
            name="sbtechpartnerconfiguration",
            options={
                "verbose_name": "SbTech partner configuration",
                "verbose_name_plural": "SbTech partner configuration",
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="name",
            field=models.CharField(default=lambda: str(uuid.uuid4().hex)[:20], max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producttype",
            name="subtype_validation",
            field=models.CharField(
                choices=[("INT", "integer field"), ("DECIMAL", "decimal field"), ("CHAR", "char field")], max_length=20
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producttype",
            unique_together={("partner_configuration", "name")},
        ),
    ]
