# Generated by Django 2.1.3 on 2019-01-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0018_auto_20190110_1649"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sbtechpartnerconfiguration",
            name="http_password",
        ),
        migrations.RemoveField(
            model_name="sbtechpartnerconfiguration",
            name="http_user",
        ),
        migrations.RemoveField(
            model_name="sbtechpartnerconfiguration",
            name="token_url",
        ),
    ]
