# Generated by Django 2.1.3 on 2019-01-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0018_auto_20190114_1720"),
        ("virtual_shop", "0019_auto_20190110_1649"),
    ]

    operations = []
