# Generated by Django 2.1.7 on 2019-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0020_merge_20190123_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="bonus_id",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
