# Generated by Django 2.1.9 on 2019-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0021_baseproduct_bonus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="bonus_type",
            field=models.CharField(
                choices=[(None, "None"), ("WEB_HOOK", "Web Hook"), ("SB_TECH_BONUS_API", "Sb Tech Bonus Api")],
                default=None,
                max_length=17,
                null=True,
            ),
        ),
    ]
