# Generated by Django 2.1.9 on 2019-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0022_baseproduct_bonus_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_user_id",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="bonus_type",
            field=models.CharField(
                choices=[("NONE", "None"), ("WEB_HOOK", "Web Hook"), ("SB_TECH_BONUS_API", "Sb Tech Bonus Api")],
                default="NONE",
                max_length=17,
                null=True,
            ),
        ),
    ]
