# Generated by Django 2.1.9 on 2019-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0023_auto_20190709_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseproduct",
            name="bonus_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="bonus_type",
            field=models.CharField(
                choices=[("NONE", "None"), ("WEB_HOOK", "Web Hook"), ("SB_TECH_BONUS_API", "Sb Tech Bonus Api")],
                default="NONE",
                max_length=17,
            ),
        ),
    ]
