# Generated by Django 2.1.9 on 2019-07-23 15:45

from django.db import migrations, models

import virtual_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0024_auto_20190709_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="photo_large",
            field=models.FileField(blank=True, null=True, upload_to=virtual_shop.models.get_member_upload_to),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="photo_medium",
            field=models.FileField(blank=True, null=True, upload_to=virtual_shop.models.get_member_upload_to),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="photo_small",
            field=models.FileField(blank=True, null=True, upload_to=virtual_shop.models.get_member_upload_to),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="photo_thumbnail",
            field=models.FileField(blank=True, null=True, upload_to=virtual_shop.models.get_member_upload_to),
        ),
    ]
