# Generated by Django 2.1.9 on 2019-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0025_auto_20190723_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSING", "Processing"),
                    ("ERROR", "Error"),
                    ("SUCCESS", "Success"),
                    ("RESOLVED", "Resolved"),
                ],
                db_index=True,
                default="NEW",
                max_length=11,
            ),
        ),
    ]
