# Generated by Django 2.1.9 on 2019-08-29 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0026_auto_20190820_0901"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlines",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="resolved_lines_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="orderlines",
            name="resolved_lines_str_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10), blank=True, null=True, size=None
            ),
        ),
    ]
