# Generated by Django 2.1.9 on 2019-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0027_auto_20190829_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="active_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="active_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="is_one_timer",
            field=models.BooleanField(default=False),
        ),
    ]
