# Generated by Django 2.1.9 on 2019-10-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0028_auto_20190930_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_product_order_line",
                to="virtual_shop.BaseProduct",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedproductsmodel",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_product_purchased",
                to="virtual_shop.BaseProduct",
            ),
        ),
        migrations.AlterIndexTogether(
            name="baseproduct",
            index_together={("active_from", "active_to", "is_one_timer")},
        ),
        migrations.AlterIndexTogether(
            name="orderlines",
            index_together={("id", "resolved")},
        ),
    ]
