# Generated by Django 2.1.9 on 2019-10-18 08:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0029_auto_20191003_1416"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseproduct",
            options={"base_manager_name": "all_objects", "default_manager_name": "all_objects"},
        ),
        migrations.AlterModelManagers(
            name="baseproduct",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="package",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
