# Generated by Django 2.1.13 on 2019-11-29 10:41

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_shop", "0030_auto_20191018_0838"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("sbtech_bonus_id", models.CharField(max_length=40)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BonusGroupConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserBonusGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sbtech_bonus_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, null=True, size=None
                    ),
                ),
                ("user", models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
                (
                    "user_bonus_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_group",
                        to="virtual_shop.BonusGroupConfiguration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="bonus_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="bonusconfiguration",
            name="bonus_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bonuses",
                to="virtual_shop.BonusGroupConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="bonus_multiple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_bonus_group",
                to="virtual_shop.BonusGroupConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="bonus_single",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_bonus",
                to="virtual_shop.BonusConfiguration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbonusgroup",
            unique_together={("user", "user_bonus_group")},
        ),
    ]
