# Generated by Django 2.1.13 on 2019-12-03 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0031_auto_20191129_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbonusgroup",
            name="sbtech_bonus_ids_send",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="bonusconfiguration",
            name="sbtech_bonus_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
