# Generated by Django 2.1.13 on 2019-12-03 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0032_auto_20191203_0913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbonusgroup",
            name="sbtech_bonus_ids_send",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
