# Generated by Django 2.1.13 on 2019-12-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0033_auto_20191203_1120"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userbonusgroup",
            unique_together=set(),
        ),
    ]
