# Generated by Django 2.1.15 on 2020-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0034_auto_20191204_0856"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseproduct",
            old_name="is_one_timer",
            new_name="once_per_lifetime",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="once_per_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name="baseproduct",
            index_together={("active_from", "active_to", "once_per_lifetime")},
        ),
    ]
