# Generated by Django 2.1.15 on 2020-01-22 13:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0035_auto_20200109_1119"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseProductAvailableFor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[("EXCLUDE", "Exclude"), ("INCLUDE", "Include")],
                        db_index=True,
                        default="INCLUDE",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseProductTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("partner_sku", models.CharField(blank=True, max_length=128)),
                ("num_in_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("low_stock_threshold", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Stock record",
                "verbose_name_plural": "Stock records",
            },
        ),
        migrations.CreateModel(
            name="UserPurchasedCount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="max_quantity_per_user",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="track_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name="baseproduct",
            index_together={("active_from", "active_to", "max_quantity_per_user")},
        ),
        migrations.AddField(
            model_name="userpurchasedcount",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_product_purchased_count",
                to="virtual_shop.BaseProduct",
            ),
        ),
        migrations.AddField(
            model_name="userpurchasedcount",
            name="user",
            field=models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_product_stockrecords",
                to="virtual_shop.BaseProduct",
            ),
        ),
    ]
