# Generated by Django 2.1.15 on 2020-01-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0036_auto_20200122_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproductavailablefor",
            name="products_members",
            field=models.ManyToManyField(related_name="produtcs_available_for", to="virtual_shop.BaseProduct"),
        ),
        migrations.AddField(
            model_name="baseproductavailablefor",
            name="tag_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_available_for",
                to="virtual_shop.BaseProductTag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="baseproductavailablefor",
            unique_together={("tag_member", "mode")},
        ),
    ]
