# Generated by Django 2.1.15 on 2020-03-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0037_auto_20200122_1319"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="once_per_lifetime",
        ),
    ]
