# Generated by Django 2.1.15 on 2020-05-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0038_remove_baseproduct_once_per_lifetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="bonus_id",
        ),
    ]
