# Generated by Django 2.1.15 on 2020-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0039_remove_baseproduct_bonus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="credit_all_points",
            field=models.BooleanField(default=False),
        ),
    ]
