# Generated by Django 2.1.15 on 2021-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_shop", "0040_baseproduct_credit_all_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="notification_type",
            field=models.CharField(
                choices=[("NONE", "None"), ("SLACK", "Slack"), ("EMAIL", "Email")], default="NONE", max_length=5
            ),
        ),
    ]
