#!groovy
void notifyGithub(String description, String status) {
  status = status ?: 'SUCCESS'
  githubNotify(
    description: description,
    context: env.GITHUB_NOTIFICATION_CONTEXT,
    account: env.GITHUB_ACCOUNT,
    repo: env.GITHUB_REPO,
    credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
    targetUrl: env.RUN_DISPLAY_URL,
    status: status
  )
}

void withAlibabaFrankfurtEcrDockerRegistry(Closure<Void> block) {
  docker.withRegistry("https://${env.ALIBABA_ECR_FRA_HOST}", env.ALIBABA_ECR_CREDENTIALS_ID) {
    block()
  }
}

void withAlibabaChinaEcrDockerRegistry(Closure<Void> block) {
  docker.withRegistry("https://${env.ALIBABA_ECR_CN_HOST}", env.ALIBABA_ECR_CREDENTIALS_ID) {
    block()
  }
}
void withAwsEcrDockerRegistry(Closure<Void> block) {
  docker.withRegistry("https://${env.AWS_ECR_HOST}", env.AWS_ECR_CREDS_ID) {
    block()
  }
}



// build status constants: https://www.jenkins.io/doc/book/glossary/#build-status
def notifySlack(String branch, String buildStatus) {
//   if (branch in ['develop', 'master']) {

    // Build status of null means success.
    buildStatus = buildStatus ?: 'SUCCESS'

    def color

    if (buildStatus == 'STARTED') {
      color = '#D4DADF'
    } else if (buildStatus == 'SUCCESS') {
      color = '#BDFFC3'
    } else if (buildStatus == 'STABLE') {
      color = '#BDFFC3'
    } else if (buildStatus == 'UNSTABLE') {
      color = '#FFFE89'
    } else { // FAILED or ABORTED
      color = '#FF9FA1'
    }

    def message = "${buildStatus}: <${env.RUN_DISPLAY_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>"

    slackSend(color: color, message: message, channel: env.SLACK_NOTIFICATION_CHANNEL)
//   }
}

String shOutput(String cmd) {
  return sh(script: cmd, returnStdout: true).trim()
}

void withGithubStatusUpdates(Closure<Void> block) {
  gitStatusWrapper(
    description: env.STAGE_NAME,
    gitHubContext: env.GITHUB_NOTIFICATION_CONTEXT,
    account: env.GITHUB_ACCOUNT,
    repo: env.GITHUB_REPO,
    credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
    targetUrl: env.RUN_DISPLAY_URL
  ) {
    block()
  }
}

properties(
  env.BRANCH_NAME == 'develop'
    ? [disableConcurrentBuilds()]
    : []
)

pipeline {
  agent {
    label 'ecs-ec2-agent-python3.8.8'
  }

  parameters {
    booleanParam(name: 'SKIP_SAFETY', defaultValue: false, description: 'Force skip SAFETY')
  }

  environment {
    COMMIT_ID = shOutput("git rev-parse HEAD")

    WAYSUN_GIT_CREDENTIALS = 'waysun-git-credentials'
    WAYSUN_GIT_URL = 'github.com/waysuninc/gmx-waysun-oidc.git'

    // github status notifications
    GITHUB_ACCOUNT = 'flipadmin'
    GITHUB_REPO = 'gmx-waysun-oidc'
    GITHUB_API_TOKEN_CREDENTIALS_ID = 'CICD-GitHub-API-token'
    GITHUB_NOTIFICATION_CONTEXT = 'Jenkins Build'
    GITHUB_API_URL = "https://api.github.com/repos/${env.GITHUB_ACCOUNT}/${env.GITHUB_REPO}"
    GITHUB_API_REFS_URL = "${env.GITHUB_API_URL}/git/refs"
    GITHUB_API_TAGS_URL = "${env.GITHUB_API_URL}/git/tags"

    SLACK_NOTIFICATION_CHANNEL = '#gmx-waysun-platform-deployment'

    // ALIBABA ECR
    ALIBABA_ECR_FRA_ACCOUNT_ID = 'waysun-stage-namespace'
    ALIBABA_ECR_FRA_NAME = 'gmx-waysun-oidc'
    ALIBABA_ECR_FRA_REGION = 'eu-central-1'
    ALIBABA_ECR_FRA_HOST = "registry.${env.ALIBABA_ECR_FRA_REGION}.aliyuncs.com"

    ALIBABA_ECR_CN_ACCOUNT_ID = 'waysun-prod-namespace'
    ALIBABA_ECR_CN_NAME = 'waysun-prod-oidc-repo'
    ALIBABA_ECR_CN_REGION = 'cn-beijing'
    ALIBABA_ECR_CN_HOST = "registry.${env.ALIBABA_ECR_CN_REGION}.aliyuncs.com"

    ALIBABA_ECR_IMAGE_TAG_PREFIX = shOutput('date +%Y%m%d_%H%M')
    ALIBABA_ECR_CREDENTIALS_ID = 'ecr-eu-central-1-aliyun-ecr-user'

    // AWS ECR
    AWS_ECR_ACCOUNT_ID = '259420793117'
    AWS_ECR_REGION = 'eu-west-1'
    AWS_ECR_HOST = "${env.AWS_ECR_ACCOUNT_ID}.dkr.ecr.${env.AWS_ECR_REGION}.amazonaws.com"
    AWS_ECR_CREDS_ID = "ecr:${env.AWS_ECR_REGION}:ecr-fs-mgmt"
    AWS_ECR_NAME = "gmx-waysun/oidc"
  }

  stages {

    stage('Notify GitHub') {
      steps {
        notifyGithub('Starting', 'PENDING')
      }
    }

    stage('Checkout') {
      steps {
        notifySlack(env.BRANCH_NAME, 'STARTED')

        withGithubStatusUpdates {
          script {
            currentBuild.displayName = "#${env.BUILD_NUMBER} for ${env.BRANCH_NAME}"
          }
          checkout([
            $class                           : 'GitSCM',
            branches                         : scm.branches,
            doGenerateSubmoduleConfigurations: scm.doGenerateSubmoduleConfigurations,
            extensions                       : [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0, reference: '']],
            userRemoteConfigs                : scm.userRemoteConfigs,
          ])
        }
      }
    }

    stage('Installing deps') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv install --ignore-pipfile --dev --pre'
        }
      }
    }

    stage('CQ: Autoflake') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv run ./ci/010_autoflake.sh check'
        }
      }
    }

    stage('CQ: Vulture') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv run ./ci/020_vulture.sh check'
        }
      }
    }

    stage('CQ: Black') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv run ./ci/030_black.sh check'
        }
      }
    }
    stage('CQ: iSort') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv run ./ci/040_isort.sh check'
        }
      }
    }
    stage('CQ: Bandit') {
      steps {
        withGithubStatusUpdates {
          sh 'pipenv run ./ci/050_bandit.sh check'
        }
      }
    }
    stage('CQ: Safety') {
      when {
        not {
          expression { return params.SKIP_SAFETY }
        }
      }
      steps {
        script {
          try {
            sh 'pipenv run ./ci/060_safety.sh check'
          } catch (err) {
            currentBuild.result = 'UNSTABLE'
            notifyGithub("Found unsafe packages! ${err}", 'FAILURE')
            notifySlack("Found unsafe packages! ${err}", currentBuild.result)
          }
        }
      }
    }

    stage('Build & Push image - FS AWS') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        withGithubStatusUpdates {
          withAwsEcrDockerRegistry {
            script{
              docker.build(
                "${env.AWS_ECR_NAME}:${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
              ).push(
                "${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
              )
            }
          }
        }
      }
    }

    stage('Adding build tag to git') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        withGithubStatusUpdates {
          withCredentials([
            usernamePassword(
              credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
              usernameVariable: 'GITHUB_USERNAME',
              passwordVariable: 'GITHUB_PASSWORD'
            )
          ]) {
            sh "curl -f -X POST -d '{\"ref\": \"refs/tags/${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}\", \"sha\":\"${env.COMMIT_ID}\"}' -H \"Accept: application/vnd.github.v3+json\" -u \"username:${GITHUB_PASSWORD}\" ${env.GITHUB_API_REFS_URL}"
          }
        }
      }
    }

    stage('Build & Push image - Aliyun FRA') {
      when {
        branch 'develop'
      }
      steps {
        withGithubStatusUpdates {
          withAwsEcrDockerRegistry {
            withAlibabaFrankfurtEcrDockerRegistry {
              script{
                docker.build(
                  "${env.ALIBABA_ECR_FRA_ACCOUNT_ID}/${ALIBABA_ECR_FRA_NAME}:${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
                ).push(
                  "${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
                )
              }
            }
          }
        }
      }
    }

    stage('Build & Push image - Aliyun CN') {
      when {
        branch 'master'
      }
      steps {
        withGithubStatusUpdates {
          withAwsEcrDockerRegistry {
            withAlibabaChinaEcrDockerRegistry {
              script{
                docker.build(
                  "${env.ALIBABA_ECR_CN_ACCOUNT_ID}/${ALIBABA_ECR_CN_NAME}:${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
                ).push(
                  "${env.ALIBABA_ECR_IMAGE_TAG_PREFIX}"
                )
              }
            }
          }
        }
      }
    }
    stage('Updating Waysun GitRepo') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        withGithubStatusUpdates {
          withCredentials([
            usernamePassword(
              credentialsId: env.WAYSUN_GIT_CREDENTIALS,
              usernameVariable: 'GITHUB_USERNAME',
              passwordVariable: 'GITHUB_PASSWORD'
            )
          ]) {
            sh 'git config --global user.email "waysun-jenkins@waysuninc.com"'
            sh 'git config --global user.name "waysun-jenkins"'
            withCredentials([sshUserPrivateKey(credentialsId: 'github', keyFileVariable: 'SSH_KEY')]) {
              sh 'GIT_SSH_COMMAND="ssh -i $SSH_KEY" git checkout ' + env.BRANCH_NAME
              sh 'GIT_SSH_COMMAND="ssh -i $SSH_KEY" git pull origin ' + env.BRANCH_NAME
            }
            sh 'git remote add waysun https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@' + env.WAYSUN_GIT_URL
            sh "git push -u waysun ${env.BRANCH_NAME}:${env.BRANCH_NAME}"
          }
        }
      }
    }
  }

  post {
    success {
      // This is to ensure that the name of the last executed stage
      // doesn't linger in GitHub's CI status once the pipeline is complete.
      notifyGithub('Complete', 'SUCCESS')
    }

    always {
      notifySlack(env.BRANCH_NAME, currentBuild.result)
    }
  }
}
