nameOverride: "prod-hipspin-client-service"
fullnameOverride: "prod-hipspin-client-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: true
  port: 3000

ingress:
  enabled: false

env:
  SITE_NAME: fiksu
  NODE_ENV: production
  PORT: 3000
  API: http://prod-hipspin-backend-service:3000
  CAPTCHA_KEY: "6LdITlclAAAAANdcG0B3IntvGO7peyha0_U8TbsP"
