cloudflow {
  streamlets {
    betgenius-http-ingestor.kubernetes.pods.pod.containers.container {
      env = [
        { name = "PHOENIX_LOGGING_JSON_FORMAT_ENABLED", value = "true" }
      ]
    }
    betgenius-console.kubernetes.pods.pod.containers.container {
      env = [
        { name = "PHOENIX_LOGGING_JSON_FORMAT_ENABLED", value = "true" }
      ]
    }
  }
}
