# Infrastructure

argocd:
  awaitRolloutComplete: false
  rollouts:
    enabled: true
    autoPromotionEnabled: false
    autoPromotionSeconds: 30

externalSecrets:
  remoteRefPathPrefix: stg/phoenix
  secretStore: main

flyway:
  outOfOrder: false

imagePullSecrets: [ecr-docker-credentials]

ingress:
  baseDNS: stg.phoenix.darkstormlabs.net
  exposeDevApi: true

  alb:
    # We're combining the APIs into a single ALB.
    group: phoenix-apis

    customerOwnedIP:
      enabled: true
      ipv4poolCoip: ipv4pool-coip-01cdf968d7c5e4718
      outpostPublicSubnetID: subnet-081324184b4896954

  whitelistedIps:
    main: []
    betgenius: []
    pxp: []

keycloak:
  namespace: keycloak
  realm: phoenix

podDisruptionBudget:
  enabled: true

postgresOperator:
  dbName: phoenix
  dbHost: phoenix-cluster.postgres-operator.svc.cluster.local
  dbWriterSecretName: phoenix-writer-user.phoenix-cluster.credentials.postgresql
  dbOwnerSecretName: phoenix-owner-user.phoenix-cluster.credentials.postgresql

prometheusRules:
  cluster: phoenix-stg-cluster
  env: stg

replicaCount: 3

resources:
  memory: "3Gi"


# Application

akka:
  persistence:
    jdbcPoolSize: 30
    recoveryTimeout: 600s

corsAllowedOrigins:
  - https://dev-api.stg.phoenix.darkstormlabs.net  # Swagger
  - https://app.stg.phoenix.darkstormlabs.net
  - https://office.stg.phoenix.darkstormlabs.net

db:
  maxConnections: 30
  minConnections: 30
  slickThreadsNum: 30

markets:
  selectionOddsUpperBoundInclusive: 101
  marketTypesDisplayedToPunters: "MATCH_WINNER, MAP_WINNER"
  sportsDisplayedToPuntersByDefault: "s:p:1, s:p:2, s:p:3, s:p:10, s:p:11, s:p:12, s:p:13, s:p:15, s:p:16"
  tournamentsDisplayedToPuntersFilterEnabled: true

notifications:
  baseUrl: "https://app.stg.phoenix.darkstormlabs.net"
  customerSupportEmailAddress: "diana.georgieva@darkstormlabs.tech"
  email:
    enabled: true
    fromAddress: "outpost-stg@darkstormlabs.net"

openapi:
  docsRelativeUrl: "/docs"
  apiBaseUrl: "https://api.stg.phoenix.darkstormlabs.net"

punters:
  maximumAmountOfPunters: 100000
  mfa:
    enabledByDefault: true
    changeAllowed: false
    mandatoryForRegistration: true

reports:
  dge:
    dailyReportsSchedule: >-
      mode=daily,start-time=\"01:00\"
  aml:
    reportsRecipientEmailAddress: "diana.georgieva@darkstormlabs.tech"
    dailyReportsSchedule: >-
      mode=daily,start-time=\"06:00\"
    weeklyReportsSchedule: >-
      mode=weekly,day-of-week=MONDAY,start-time=\"06:00\"
    monthlyReportsSchedule: >-
      mode=monthly,day-of-month=1,start-time=\"06:00\"
    deceasedReportsSchedule: >-
      mode=weekly,day-of-week=WEDNESDAY,start-time=\"06:00\"
    manuallyUnsuspendedReportsSchedule: >-
      mode=weekly,day-of-week=TUESDAY,start-time=\"09:00\"
    multiDeviceActivityReportsSchedule: >-
      mode=daily,start-time=\"06:00\"

talon:
  talonAppBaseUrl: "https://office.stg.phoenix.darkstormlabs.net"


# 3rd party integrations

betgenius:
  dataIngestionEnabled: "no"
  apiEnvironment: "PRODPRM"

dge:
  sftp:
    host: sftp-2a1n.stg.phoenix.darkstormlabs.net.internal
    port: 22
    rootDirectory: /phoenix
  exclusion:
    ingestion:
      schedule: >-
        mode=daily,start-time=\"12:00\"
      timeRestriction: 5.minutes
      maxRetries: 0

geoComply:
  licenseService:
    baseUrl: "https://auth.geocomply.com"

idComply:
  baseUrl: "https://api.idcomply.com/v1"
  photoVerificationBaseUrl: "https://verifyid.idcomply.com/"
  frontEndRedirectionEndpoint: "https://app.stg.phoenix.darkstormlabs.net/esports-bets/idpv-result"
  idPhotoVerificationEndpoint: "kyc-esports-nj-ocr"
  endpointPaths:
    knowYourCustomer: "/kyc-esports-nj"
    knowledgeBasedAuthentication: "/kyc-esports-nj-kba"

oddin:
  dataIngestionEnabled: "yes"
  useCommonDataApiModel: "yes"
  environment: PRODUCTION
  restBaseUrl: "https://api-mq.oddin.gg"
  nodeId: "3"
  kafka:
    enabled: "no"
    consumer:
      bootstrapServers: "phoenix-strimzi-kafka-bootstrap.cloudflow:9092"

payments:
  baseUrl: "https://api.test.kalixa.com"

twilio:
  verifyApiBaseUrl: "https://verify.twilio.com"
