ebean.ddl.generate=true  
ebean.ddl.run=true
      
ebean.debug.sql=true  
ebean.debug.lazyload=false  

# -------------------------------------------------------------  
# DataSources (If using default Ebean DataSourceFactory)  
# -------------------------------------------------------------   
# You can specify many DataSources (one per EbeanServer)  and   
# one of them is defined as the default/primary DataSource  

datasource.default=sbtech

ebean.migration.run=true

datasource.sbtech.username=sbtech
datasource.sbtech.password=sbtech
datasource.sbtech.databaseUrl=jdbc:postgresql://127.0.0.1:15432/sbtech
datasource.sbtech.databaseDriver=org.postgresql.Driver

#ebean.search.jars=flip-domain-models-2.0.0-SNAPSHOT.jar
ebean.search.packages=tech.argyll.prices.models