stella.event-ingestor.event-publication-mode = storeInRedisAndStartKafkaPublicationService
stella.event-ingestor.http-server.jwt.require-jwt-auth = false
stella.event-ingestor.test-project-id = "2353130a-e2b3-47e9-a2cb-3ade99f81b04"
