# Pipeline Kafka
app.pipeline.kafka.topic=collector.pa.horse-racing.xml
app.pipeline.kafka.max-request-size=10485760

app.pipeline.kafka.endpoint.uri=kafka:${app.pipeline.kafka.topic}\
  ?brokers=${app.pipeline.kafka.brokers}\
  &maxRequestSize=${app.pipeline.kafka.max-request-size}
