CREATE TABLE "vNJDGE02PATRONSSESSIONS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "SESSION_ID" VARCHAR NOT NULL,
    "GEOLOCATION_TRANSACTION_ID" VARCHAR,
    "LOGINTIME_SYSTEM" VARCHAR NOT NULL,
    "LOGOUTTIME_SYSTEM" VARCHAR,
    "LOGINTIME_EASTERN" VARCHAR NOT NULL,
    "LOGOUTTIME_EASTERN" VARCHAR,
    "SESSION_IPV4" VARCHAR NOT NULL,
    "SESSION_IPV6" VARCHAR,
    "SESSION_LATITUDE" VARCHAR,
    "SESSION_LONGITUDE" VARCHAR,
    PRIMARY KEY("SESSION_ID")
);