CREATE TABLE "vNJDGE09PATRONSTATUS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "PATRON_REPORTING_DATE" VARCHAR NOT NULL,
    "ACCOUNT_TYPE" VARCHAR NOT NULL,
    "ACCOUNT_STATUS" VARCHAR NOT NULL,
    "EXCLUSION_FLAG" VARCHAR NOT NULL,
    "EXCLUSION_DESCRIPTION" VARCHAR,
    "WALLET_CASH_BALANCE" NUMERIC NOT NULL,
    "WALLET_NON_CASH_BALANCE" NUMERIC NOT NULL,
    "BLOCKED_FUNDS" NUMERIC,
    "FUNDS_ON_GAME" NUMERIC,
    "CASH_ADJUSTMENT" NUMERIC,
    "CASH_ADJUSTMENT_REASON" VARCHAR,
    "NON_CASH_ADJUSTMENT" NUMERIC,
    "NON_CASH_ADJUSTMENT_REASON" VARCHAR,
    PRIMARY KEY("PATRON_ACCOUNT_ID", "PATRON_REPORTING_DATE")
);
