CREATE TABLE "vNJDGE08PATRONSGAMELIMS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "LIMIT_TRANSACTTIME_SYSTEM" VARCHAR NOT NULL,
    "LIMIT_TRANSACTTIME_EASTERN" VARCHAR NOT NULL,
    "LIMIT_TRANSACT_STIME_SYSTEM" VARCHAR NOT NULL,
    "LIMIT_TRANSACT_ETIME_SYSTEM" VARCHAR NOT NULL,
    "LIMIT_TRANSACT_STIME_EASTERN" VARCHAR NOT NULL,
    "LIMIT_TRANSACT_ETIME_EASTERN" VARCHAR NOT NULL,
    "LIMIT_TYPE" VARCHAR NOT NULL,
    "LIMIT_PERIOD" VARCHAR,
    "LIMIT_AMOUNT" NUMERIC,
    PRIMARY KEY("LIMIT_TRANSACTTIME_EASTERN", "PATRON_ACCOUNT_ID")
);
