CREATE TABLE "vNJDGE04CASINOGAMEWAGERS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "SESSION_ID" VARCHAR NOT NULL,
    "CASINO_GAME_TRANSACTION_ID" VARCHAR NOT NULL,
    "CASINO_GAME_TRANS_FAILURE_FLAG" VARCHAR,
    "CASINO_GAME_STARTTIME_SYSTEM" VARCHAR NOT NULL,
    "CASINO_GAME_ENDTIME_SYSTEM" VARCHAR,
    "CASINO_GAME_STARTTIME_EASTERN" VARCHAR NOT NULL,
    "CASINO_GAME_ENDTIME_EASTERN" VARCHAR,
    "CASINO_GAME_NAME" VARCHAR NOT NULL,
    "CASINO_GAME_VERSION" VARCHAR NOT NULL,
    "RGS_NAME" VARCHAR NOT NULL,
    "CASINO_GAME_COIN_IN" NUMERIC NOT NULL,
    "CASINO_GAME_COIN_OUT" NUMERIC NOT NULL,
    "CASINO_FEE" NUMERIC NOT NULL,
    "CASINO_GAME_WINLOSS" NUMERIC NOT NULL,
    "CASINO_GAME_IMO" VARCHAR
);