play {
  http {
    context = "/"
    secret {
      key = "changeme"
      key = ${?APPLICATION_SECRET}
    }
    errorHandler = "tech.argyll.gmx.predictorgame.CustomErrorHandler"
  }

  modules {
    enabled += tech.argyll.gmx.predictorgame.Module
    enabled += tech.argyll.gmx.predictorgame.modules.DbModule
    enabled += tech.argyll.gmx.predictorgame.modules.ProdAuthModule
// UNCOMMENT FOR LOCAL DEV W/O RMX
//    enabled += tech.argyll.gmx.predictorgame.modules.DevAuthModule
// UNCOMMENT FOR CONFIGURATION ISSUES DEBUGGING
//    enabled += tech.argyll.gmx.predictorgame.modules.LogConfigModule
  }

  filters {
    enabled += play.filters.cors.CORSFilter

    enabled += tech.argyll.gmx.predictorgame.common.play.filter.AccessLoggingFilter

    disabled += play.filters.headers.SecurityHeadersFilter
    disabled += play.filters.hosts.AllowedHostsFilter
    disabled += play.filters.csrf.CSRFFilter

  }
  i18n {
    langs = ["en"]
  }
}