blueprint {

  streamlets {
    deposit-limit-increase-alert-generator = gmx.service.responsiblegambling.generators.DepositLimitIncreaseFrequencyAlertGenerator
    timeout-frequency-alert-generator = gmx.service.responsiblegambling.generators.TimeoutFrequencyAlertGenerator
    play-session-duration-alert-generator = gmx.service.responsiblegambling.generators.PlaySessionDurationAlertGenerator
    sports-bet-liability-alert-generator = gmx.service.responsiblegambling.generators.SportsBetAverageLiabilityAlertGenerator
    trunarrative-alert-handler = gmx.service.responsiblegambling.handlers.TruNarrativeAlertHandler
    daily-avg-bet-liability-calculator = gmx.service.responsiblegambling.calculators.AverageSportsBetLiabilityCalculator
  }

  topics {

    // EXTERNAL (UNMANAGED) TOPICS

    deposit-limit-increases = ${unmanaged-kafka} {
      topic.name = "customer-deposit-limits"
      consumers = [deposit-limit-increase-alert-generator.in]
    }

    timeouts-set = ${unmanaged-kafka} {
      topic.name = "customer-timeouts"
      consumers = [timeout-frequency-alert-generator.in]
    }

    sports-bets-placed = ${unmanaged-kafka} {
      topic.name = "customer-sports-bets"
      consumers = [play-session-duration-alert-generator.sports-bets, sports-bet-liability-alert-generator.sports-bets, daily-avg-bet-liability-calculator.in]
    }

    casino-bets-placed = ${unmanaged-kafka} {
      topic.name = "customer-casino-bets"
      consumers = [play-session-duration-alert-generator.casino-bets]
    }

    customer-logouts = ${unmanaged-kafka} {
      topic.name = "customer-logouts"
      consumers = [play-session-duration-alert-generator.logouts]
    }

    // INTERNAL (MANAGED) TOPICS

    deposit-limit-increase-alerts {
      producers = [deposit-limit-increase-alert-generator.out]
      consumers = [trunarrative-alert-handler.deposit-limit-increase-alerts]
    }

    timeout-frequency-alerts {
      producers = [timeout-frequency-alert-generator.out]
      consumers = [trunarrative-alert-handler.timeout-frequency-alerts]
    }

    play-session-duration-alerts {
      producers = [play-session-duration-alert-generator.out]
      consumers = [trunarrative-alert-handler.play-session-alerts]
    }

    sports-bet-liability-alerts {
      producers = [sports-bet-liability-alert-generator.out]
      consumers = [trunarrative-alert-handler.in4]
    }

    daily-avg-bet-liability {
      producers = [daily-avg-bet-liability-calculator.out]
      consumers = [sports-bet-liability-alert-generator.average-liability]
    }
  }
}

unmanaged-kafka {
  managed = no
  producer-config = ${kafka-connection-config} {
    # more config can be added here from Kafka ProducerConfig (see org.apache.kafka.clients.producer.ProducerConfig)
  }
  consumer-config = ${kafka-connection-config} {
    # more config can be added here from Kafka ConsumerConfig (see org.apache.kafka.clients.consumer.ConsumerConfig)
  }
}

kafka-connection-config {
  bootstrap.servers = "localhost:9092"
}