akka {
  loglevel = "DEBUG"
  //  log-config-on-start = on
  actor {
    debug {
      receive = on
      autoreceive = on
      lifecycle = on
      unhandled = on
    }
  }

  kafka.consumer {
    kafka-clients {
      enable.auto.commit = true
      auto.commit.interval.ms = 100
      max.poll.records = 100
      max.poll.interval.ms = 3000
      auto.offset.reset = earliest
      auto.offset.reset = ${?GMX_KAFKA_EVENTS_OFFSET}
      bootstrap.servers = "localhost:9092"
      bootstrap.servers = ${?GMX_KAFKA_BOOTSTRAP}
    }
  }
}

app {
  partner-type = "sportnation"
  partner-type = ${?GMX_PARTNER_TYPE}

  sport-events {
    kafka-source {
      dump-records = false

      enabled = true
      enabled = ${?KAFKA_ENABLED}

      topic = "gmx-messaging."${app.partner-type}"-site-extensions-sportevents"
      topic = ${?GMX_KAFKA_EVENTS_TOPIC}

      group-id = "gmx-messaging."${app.partner-type}"-site-extensions-sportevents"
      group-id = ${?GMX_KAFKA_EVENTS_GROUP_ID}

      schema-registry = "http://localhost:8081"
      schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY}

      consumer-config: ${akka.kafka.consumer}
    }
    persistence { // used only if kafka-source is enabled
      first-retry-delay = 30 seconds
      first-retry-delay = ${?GMX_EVENTS_PERSISTENCE_RETRY_DELAY}

      next-retries-delay-multiplier = 2
      next-retries-delay-multiplier = ${?GMX_EVENTS_PERSISTENCE_RETRY_DELAY_MULTIPLIER}

      max-retries = 12
      max-retries = ${?GMX_EVENTS_PERSISTENCE_MAX_RETRIES}

      start-retry-job = true
      start-retry-job = ${?GMX_EVENTS_PERSISTENCE_START_RETRY_JOB}

      retry-job-frequency-seconds = 10
      retry-job-frequency-seconds = ${?GMX_EVENTS_PERSISTENCE_RETRY_JOB_FREQUENCY_SECONDS}

      retry-events-batch-size = 500
      retry-events-batch-size = ${?GMX_EVENTS_PERSISTENCE_RETRY_EVENTS_BATCH_SIZE}

      start-cleanup-job = true
      start-cleanup-job = ${?GMX_EVENTS_PERSISTENCE_START_CLEANUP_JOB}

      cleanup-job-cron-trigger = "0 0 3 * * ?"
      cleanup-job-cron-trigger = ${?GMX_EVENTS_PERSISTENCE_CLEANUP_JOB_CRON_TRIGGER}

      cleanup-job-time-zone = "UTC"
      cleanup-job-time-zone = ${?GMX_EVENTS_PERSISTENCE_CLEANUP_JOB_TIME_ZONE}

      delete-messages-retried-earlier-than = 7 days
      delete-messages-retried-earlier-than = ${?GMX_EVENTS_PERSISTENCE_CLEANUP_EARLIER_THAN}
    }
  }
}
