app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    wallet-transactions = "gmx-messaging.%s-ds-wallettransactions"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }
  target-topics {
    compliance-validation = "gmx-messaging.%s-compliance-validation"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }
}

include "dev.conf"