"""empty message

Revision ID: b524990945bf
Revises: 
Create Date: 2021-01-20 15:00:06.225079

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b524990945bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sub", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub"),
    )
    op.create_index(op.f("ix_partner_created_at"), "partner", ["created_at"], unique=False)
    op.create_index(op.f("ix_partner_deleted_at"), "partner", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_partner_id"), "partner", ["id"], unique=True)
    op.create_index(op.f("ix_partner_is_deleted"), "partner", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_partner_updated_at"), "partner", ["updated_at"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sub", sa.Unicode(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_deleted_at"), "user", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_user_sub"), "user", ["sub"], unique=True)
    op.create_index(op.f("ix_user_updated_at"), "user", ["updated_at"], unique=False)
    op.create_table(
        "user_context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["partner_id"], ["partner.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("context_id"),
    )
    op.create_index(op.f("ix_user_context_created_at"), "user_context", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_context_deleted_at"), "user_context", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_context_id"), "user_context", ["id"], unique=True)
    op.create_index(op.f("ix_user_context_is_deleted"), "user_context", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_user_context_partner_id"), "user_context", ["partner_id"], unique=False)
    op.create_index(op.f("ix_user_context_updated_at"), "user_context", ["updated_at"], unique=False)
    op.create_index(op.f("ix_user_context_user_id"), "user_context", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_context_user_id"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_updated_at"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_partner_id"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_is_deleted"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_id"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_deleted_at"), table_name="user_context")
    op.drop_index(op.f("ix_user_context_created_at"), table_name="user_context")
    op.drop_table("user_context")
    op.drop_index(op.f("ix_user_updated_at"), table_name="user")
    op.drop_index(op.f("ix_user_sub"), table_name="user")
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_deleted_at"), table_name="user")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_partner_updated_at"), table_name="partner")
    op.drop_index(op.f("ix_partner_is_deleted"), table_name="partner")
    op.drop_index(op.f("ix_partner_id"), table_name="partner")
    op.drop_index(op.f("ix_partner_deleted_at"), table_name="partner")
    op.drop_index(op.f("ix_partner_created_at"), table_name="partner")
    op.drop_table("partner")
    # ### end Alembic commands ###
