nameOverride: lenses
secrets:
  license:
  login:
    username:
    password:
  database:
    username:
    password:

ingress:
  qcloud_cert_id:
  clb_id:
  domain:




lenses:
  image:
    repository: lensesio/lenses
    pullPolicy: Always
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: nodes-type
                operator: In
                values:
                  - tools-nodes
          weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodes-type
                operator: In
                values:
                  - tools-nodes

  # Monitoring
  monitoring:
    pipeline: lenses
    enabled: true
    port: 9102
    path: "/metrics"

  # Resource management
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi

  rbacEnable: true
  restPort: 3030
  servicePort: 80
  servicePortName: lenses
  serviceAccount: default
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: "cbs"

  additionalVolumes:
  additionalVolumeMounts:
  service:
    enabled: true
    type: NodePort
    annotations: { }
    externalTrafficPolicy:

  ingress:
    enabled: false

  lenses:
    kafka:
      ssl:
        enabled: false
      sasl:
        enabled: false
      metrics:
        enabled: true
        type: "JMX"
        port: 5555

      bootstrapServers:
        - name:
          port: 9092
          sslPort: 9093
          saslSslPort: 9094
          saslPlainTextPort: 9095

    zookeepers:
      enabled: true
      chroot:
      hosts:
        - host:
          port: 2181
          metrics:
            url:
            type: "JMX"
    schemaRegistries:
      enabled: true
      topic:
      hosts:
        - host:
          protocol: http
          port: 8081
          path:
          metrics:
            url:
      security:
        enabled: false

    connectClusters:
      enabled: true
      external: false
      clusters:
        - name: cp-kafka-connect
          port: 8083
          jmxPort: 5555
          protocol: http
          offsetsTopic: connect-offsets
          statusTopic: connect-status
          configTopic: connect-configs
          hosts:
            - url:
              metrics:
                url:

    storage:
      postgres:
        enabled: true
        host:
        port: 5432             # optional, defaults to 5432
        username: external         # use "external" to manage it using secrets
        password: external         # use "external" to manage it using secrets
        database: lenses
        schema:             # optional, defaults to public schema

    # Data Application Deployment Framework
    deployments:
      eventsBufferSize: 10000
      errorsBufferSize: 1000

      connect:
        statusInterval: 30 second
        actionsBufferSize: 1000

    # sql
    sql:
      mode: IN_PROC
      heap: 1024M
      minHeap: 128M
      memLimit: 1152M
      memRequest: 128M
      livenessInitialDelay: 60 seconds

    # alerts
    alerts:
      enabled: true
      consumersLagThreshold: 50000
      plugins:
    grafanaUrl:
    topics:
      suffix:
    security:
      defaultUser:
        username: external
        password: external
      kerberos:
        enabled: false
      ldap:
        enabled: false
      saml:
        enabled: false
    license: external
    additionalEnv:
      - name: LICENSE
        valueFrom:
          secretKeyRef:
            name: lenses-license
            key: license.json

      - name: LENSES_STORAGE_POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: lenses-database
            key: LENSES_STORAGE_POSTGRES_USERNAME

      - name: LENSES_STORAGE_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: lenses-database
            key: LENSES_STORAGE_POSTGRES_PASSWORD

      - name: LENSES_SECURITY_USER
        valueFrom:
          secretKeyRef:
            name: lenses-master-user
            key: LENSES_SECURITY_USER

      - name: LENSES_SECURITY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: lenses-master-user
            key: LENSES_SECURITY_PASSWORD

    configOverrides: { }
    livenessProbe:
      enabled: true
    pauseExec:
      enabled: false

  sidecarContainers: { }

