// flow-typed signature: 94087b3004b7c66dab33a11356f6320d
// flow-typed version: <<STUB>>/@slack/webhook_v^6.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slack/webhook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slack/webhook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slack/webhook/dist/errors' {
  declare module.exports: any;
}

declare module '@slack/webhook/dist/IncomingWebhook' {
  declare module.exports: any;
}

declare module '@slack/webhook/dist' {
  declare module.exports: any;
}

declare module '@slack/webhook/dist/instrument' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slack/webhook/dist/errors.js' {
  declare module.exports: $Exports<'@slack/webhook/dist/errors'>;
}
declare module '@slack/webhook/dist/IncomingWebhook.js' {
  declare module.exports: $Exports<'@slack/webhook/dist/IncomingWebhook'>;
}
declare module '@slack/webhook/dist/index' {
  declare module.exports: $Exports<'@slack/webhook/dist'>;
}
declare module '@slack/webhook/dist/index.js' {
  declare module.exports: $Exports<'@slack/webhook/dist'>;
}
declare module '@slack/webhook/dist/instrument.js' {
  declare module.exports: $Exports<'@slack/webhook/dist/instrument'>;
}
