# {{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  labels:
    "app.kubernetes.io/name": '{{ template "campaignserver-client-app.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.ingress.componentName }}"
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "campaignserver-client-app.fullname" . }}
spec:
{{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName | quote }}
{{- end }}
  rules:
  - http:
      paths:
 {{- if empty (.Values.ingress.paths) }}
      - pathType:
        backend:
          service:
            name: {{ template "campaignserver-client-app.fullname" . }}
            port:
              number: {{ .Values.ingress.servicePort }}
{{- if .Values.ingress.path }}
        path: {{ .Values.ingress.path }}
{{- end -}}
{{- else }}
{{ tpl (toYaml .Values.ingress.paths | indent 6) . }}
{{- end -}}
{{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
{{- end }}
{{- if .Values.ingress.resourceRootUrl }}
  - http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: {{ template "campaignserver-client-app.fullname" . }}
            port:
              number: {{ .Values.ingress.servicePort }}
    host: {{ .Values.ingress.resourceRootUrl | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
