{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "campaignserver-client-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "campaignserver-client-app.name" . }}
    chart: {{ include "campaignserver-client-app.chart" . }}
    release: prometheus-operator
    heritage: {{ .Release.Service }}
spec:
  endpoints:
  - interval: {{ .Values.prometheus.interval }}
    path: {{ .Values.prometheus.path }}
    port: {{ .Values.prometheus.portname }}
{{- if .Values.prometheus.relabelings }}
    relabelings:
{{ toYaml .Values.prometheus.relabelings | indent 6 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "campaignserver-client-app.labels" . | nindent 6 }}
{{- end }}
