stella {
  leaderboard {
    # eventually we'll need some proper, secure way of storing this
    secret-box-hex-key = ea87def016584b3c84e5cdbea4dcc868ea87def016584b3c84e5cdbea4dcc868
    secret-box-hex-key = ${?LEADERBOARD_SECRET_BOX_HEX_KEY}

    test-user-id = "b080f663-ed46-4b58-8c85-810cef8358ea"
    test-user-id = ${?LEADERBOARD_TEST_USER_ID}

    test-project-id = "2353130a-e2b3-47e9-a2cb-3ade99f81b03"
    test-project-id = ${?LEADERBOARD_TEST_PROJECT_ID}

    cache {
      windows-timeout = 10 seconds
      windows-timeout = ${?LEADERBOARD_WINDOWS_CACHE_TIMEOUT}
      aggregation-results-timeout = 10 seconds
      aggregation-results-timeout = ${?LEADERBOARD_AGGREGATION_RESULTS_CACHE_TIMEOUT}
      neighbors-timeout = 10 seconds
      neighbors-timeout = ${?LEADERBOARD_NEIGHBORS_CACHE_TIMEOUT}
      compare-results-timeout = 10 seconds
      compare-results-timeout = ${?LEADERBOARD_COMPARE_RESULTS_CACHE_TIMEOUT}
    }

    jwt {
      require-jwt-auth = true
      require-jwt-auth = ${?LEADERBOARD_REQUIRE_JWT_AUTH}
      service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
      service-discovery-endpoint-uri = ${?JWT_SERVICE_DISCOVERY_URI}
      internal-service-discovery-endpoint-uri = "http://localhost:8080/auth/realms"
      internal-service-discovery-endpoint-uri = ${?JWT_INTERNAL_SERVICE_DISCOVERY_URI}
      issuer-cache-refresh-frequency = 1 hour
      issuer-cache-refresh-frequency = ${?LEADERBOARD_ISSUER_CACHE_REFRESH_FREQUENCY}
      jwks-cache-refresh-frequency = 10 minutes
      jwks-cache-refresh-frequency = ${?LEADERBOARD_JWKS_CACHE_REFRESH_FREQUENCY}
    }

    open-api {
      server-url = "http://localhost:11000"
      server-url = ${?LEADERBOARD_OPEN_API_SERVER_URL}
    }
  }
}
