// flow-typed signature: 9bbed6dad14f3f632308e332e1fc8700
// flow-typed version: <<STUB>>/@kafkajs/confluent-schema-registry_v^3.0.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kafkajs/confluent-schema-registry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kafkajs/confluent-schema-registry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kafkajs/confluent-schema-registry/dist/@types' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/api' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/confluentEncoderMiddleware' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/errorMiddleware' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/userAgent' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/AvroHelper' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/cache' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/constants' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/errors' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/JsonHelper' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/JsonSchema' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/ProtoHelper' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/ProtoSchema' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/SchemaRegistry' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/schemaTypeResolver' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/utils/avdlToAVSC' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/utils' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/utils/readAVSC' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/wireDecoder' {
  declare module.exports: any;
}

declare module '@kafkajs/confluent-schema-registry/dist/wireEncoder' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kafkajs/confluent-schema-registry/dist/@types.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/@types'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/api/index' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/api'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/api/index.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/api'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/confluentEncoderMiddleware.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/api/middleware/confluentEncoderMiddleware'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/errorMiddleware.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/api/middleware/errorMiddleware'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/api/middleware/userAgent.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/api/middleware/userAgent'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/AvroHelper.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/AvroHelper'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/cache.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/cache'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/constants.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/constants'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/errors.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/errors'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/index' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/index.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/JsonHelper.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/JsonHelper'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/JsonSchema.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/JsonSchema'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/ProtoHelper.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/ProtoHelper'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/ProtoSchema.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/ProtoSchema'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/SchemaRegistry.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/SchemaRegistry'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/schemaTypeResolver.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/schemaTypeResolver'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/utils/avdlToAVSC.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/utils/avdlToAVSC'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/utils/index' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/utils'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/utils/index.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/utils'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/utils/readAVSC.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/utils/readAVSC'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/wireDecoder.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/wireDecoder'>;
}
declare module '@kafkajs/confluent-schema-registry/dist/wireEncoder.js' {
  declare module.exports: $Exports<'@kafkajs/confluent-schema-registry/dist/wireEncoder'>;
}
