# Used for the manifest handling.
app.storage.headers.key=CamelAwsS3Key


# Intake storage
app.storage.intake.s3.bucket=gmx-data-collector
app.storage.intake.s3.region=eu-west-1
app.storage.intake.endpoint.uri=aws-s3:${app.storage.intake.s3.bucket}?region=${app.storage.intake.s3.region}&${app.storage.s3.authentication}

# Silks storage
app.storage.silks.s3.bucket=assets.vidi.argyll.tech
app.storage.silks.s3.region=eu-west-1
app.storage.silks.endpoint.uri=aws-s3:${app.storage.silks.s3.bucket}?region=${app.storage.silks.s3.region}&${app.storage.s3.authentication}