#!/usr/bin/env bash

# This needs to be symlinked from .git/hooks/prepare-commit-msg in the repo.
# Make sure the file is executable.

set -u

commit_message_file=$1
source_of_commit=${2-}

case $source_of_commit in
  ""|commit|message) true ;;  # $source_of_commit will be empty e.g. when pure "git commit" without any parameters is called.
  *) exit 0 ;;  # Don't handle the "merge", "squash" and "template" cases.
esac

# Check if we're on any branch.
git symbolic-ref --quiet HEAD &>/dev/null || exit 0

ticket_id_regex='[a-zA-Z0-9]+-[0-9]+'
ticket_id=$(git symbolic-ref --short HEAD | grep -Eo "^(.*/)?${ticket_id_regex}" | sed 's!^.*/!!' | tr '[:lower:]' '[:upper:]')

if [[ $ticket_id ]]; then
  message=$(<$commit_message_file)
  # Don't prepend ticket id in case it's already at the beginning of the message.
  if [[ $message != "[$ticket_id]"* ]]; then
    echo "[$ticket_id] $message" > "$1"
  fi
fi
