CREATE TABLE "vNJDGE05POKERGAMEWAGERS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "SESSION_ID" VARCHAR NOT NULL,
    "POKER_TABLE_ID" VARCHAR NOT NULL,
    "POKER_HAND_ID" VARCHAR NOT NULL,
    "POKER_TRANS_FAILURE_FLAG" VARCHAR,
    "POKER_HAND_STARTTIME_SYSTEM" VARCHAR NOT NULL,
    "POKER_HAND_ENDTIME_SYSTEM" VARCHAR,
    "POKER_HAND_STARTTIME_EASTERN" VARCHAR NOT NULL,
    "POKER_HAND_ENDTIME_EASTERN" VARCHAR,
    "POKER_NAME" VARCHAR NOT NULL,
    "POKER_VERSION" VARCHAR NOT NULL,
    "RGS_NAME" VARCHAR NOT NULL,
    "POKER_COIN_IN" NUMERIC NOT NULL,
    "POKER_COIN_OUT" NUMERIC NOT NULL,
    "POKER_WINLOSS" NUMERIC NOT NULL,
    "POKER_RAKE_FEE" NUMERIC NOT NULL
);
