CREATE TABLE "vNDGE07CASHTRANS"
(
    "SKIN_NAME" VARCHAR NOT NULL,
    "PATRON_ACCOUNT_ID" VARCHAR NOT NULL,
    "CASH_TRANSACTION_ID" VARCHAR NOT NULL,
    "CASH_TRANSACTIONTIME_SYSTEM" VARCHAR NOT NULL,
    "CASH_TRANSACTIONTIME_EASTERN" VARCHAR NOT NULL,
    "CASH_TRANSACTION_AMOUNT" NUMERIC NOT NULL,
    "CASH_TRANSACTION_TYPE" VARCHAR NOT NULL,
    "CASH_TRANSACTION_DESCRIPTION" VARCHAR NOT NULL,
    "CASH_TRANSACTION_SOURCE_TYPE" VARCHAR,
    "CASH_TRANSACTION_PROVIDER" VARCHAR,
    "CASH_TRANSACTION_REQAMOUNT" NUMERIC NOT NULL,
    PRIMARY KEY("CASH_TRANSACTION_ID")
);
CREATE INDEX "index_transactiontime_eastern" ON "vNDGE07CASHTRANS" ("CASH_TRANSACTIONTIME_EASTERN");
CREATE INDEX "index_transactiontime_system" ON "vNDGE07CASHTRANS" ("CASH_TRANSACTIONTIME_SYSTEM");
CREATE INDEX "index_patron_id" ON "vNDGE07CASHTRANS" ("PATRON_ACCOUNT_ID");
