cloudflow {
  streamlets {
    oddin-ingestor {
      kubernetes.pods.pod.containers.container {
        env = [
          { name = "PHOENIX_LOGGING_JSON_FORMAT_ENABLED", value = "true" }
        ]
      }
      config-parameters {
        oddin-access-token = ${?ODDIN_ACCESS_TOKEN}
        node-id = "1"
        node-id = ${?ODDIN_NODE_ID}
        oddin-rest-endpoint = "https://api-mq.integration.oddin.gg"
      }
    }
  }
}
