ALTER TABLE "vNJDGE03WALLETTRANSFERS" ADD PRIMARY KEY ("WALLET_TRANSACTION_ID");
CREATE INDEX "index_transfertime_eastern" ON "vNJDGE03WALLETTRANSFERS" ("TRANSFERTIME_EASTERN");
CREATE INDEX "index_transfertime_system" ON "vNJDGE03WALLETTRANSFERS" ("TRANSFERTIME_EASTERN");
CREATE INDEX "index_transfer_patron_id" ON "vNJDGE03WALLETTRANSFERS" ("PATRON_ACCOUNT_ID");