idefix {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    events = "TODO:%d"
    schema-registry = "http://localhost"
  }

  target-topics {
    events = "gmx-messaging.%s-ds-events"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }

}

include "dev.conf"