package phoenix.support

import java.util.Locale

import com.github.javafaker.Faker
import org.keycloak.representations.idm.UserRepresentation

import phoenix.core.validation.Validation.Validation
import phoenix.punters.KeycloakDataConverter
import phoenix.punters.KeycloakUser
import phoenix.punters.domain.Address
import phoenix.punters.domain.AddressLine
import phoenix.punters.domain.BettingPreferences
import phoenix.punters.domain.City
import phoenix.punters.domain.CommunicationPreferences
import phoenix.punters.domain.Country
import phoenix.punters.domain.DateOfBirth
import phoenix.punters.domain.Email
import phoenix.punters.domain.FirstName
import phoenix.punters.domain.LastName
import phoenix.punters.domain.MobilePhoneNumber
import phoenix.punters.domain.PersonalName
import phoenix.punters.domain.PunterPersonalDetails
import phoenix.punters.domain.SocialSecurityNumber.First5DigitsOfSSN
import phoenix.punters.domain.SocialSecurityNumber.FullSSN
import phoenix.punters.domain.SocialSecurityNumber.Last4DigitsOfSSN
import phoenix.punters.domain.State
import phoenix.punters.domain.Title
import phoenix.punters.domain.UserDetails
import phoenix.punters.domain.UserDetailsKeycloak
import phoenix.punters.domain.UserPreferences
import phoenix.punters.domain.Username
import phoenix.punters.domain.Zipcode
import phoenix.punters.exclusion.domain.NormalizedLastName
import phoenix.support.DataGenerator.randomBoolean
import phoenix.support.DataGenerator.randomGender
import phoenix.support.DataGenerator.randomOffsetDateTime
import phoenix.support.DataGenerator.randomTermsAgreement
import phoenix.support.UnsafeValueObjectExtensions._

object UserGenerator {

  val faker = new Faker()

  def generateUsername(): Username =
    Username.fromStringUnsafe(faker.name().username())

  def generatePersonalName(): PersonalName = {
    val title = Title(faker.name().title()).unsafe()
    val firstName = FirstName(faker.name().firstName()).unsafe()
    val lastName = LastName(faker.name().lastName()).unsafe()

    PersonalName(title, firstName, lastName)
  }

  def generateLastName(): NormalizedLastName =
    NormalizedLastName(generatePersonalName().lastName.value)

  def generateEmail(): Email =
    Email
      .fromString(faker.internet().emailAddress())
      .getOrElse(throw new RuntimeException("invalid email address generated by Faker"))

  def generateMobilePhoneNumber(): MobilePhoneNumber =
    MobilePhoneNumber(s"+${faker.number().digits(11)}")

  def generateZipcode(): Validation[Zipcode] =
    Zipcode(faker.address().zipCode())

  def generateAddress(): Address = {
    val addressLine = faker.address().streetAddress()
    val city = faker.address().city()
    val state = faker.address().state()
    val zipcode = generateZipcode()
    val codes: Array[String] = Locale.getISOCountries()
    val country = faker.options().nextElement(codes)

    Address(
      AddressLine(addressLine).unsafe(),
      City(city).unsafe(),
      State(state).unsafe(),
      zipcode.unsafe(),
      Country(country).unsafe())
  }

  def generateDateOfBirth(): DateOfBirth = {
    val day = faker.number().numberBetween(1, 28)
    val month = faker.number().numberBetween(1, 12)
    val year = faker.number().numberBetween(1968, 2000)

    DateOfBirth.from(day, month, year).getOrElse(throw new RuntimeException("invalid date-of-birth generated by Faker"))
  }

  def generateFullSSN(): FullSSN =
    generateRemainingFirstFive(generateSocialSecurityNumber())

  def generateSocialSecurityNumber(): Last4DigitsOfSSN =
    Last4DigitsOfSSN.fromString(faker.number().digits(4)).unsafe()

  def generateRemainingFirstFive(lastFour: Last4DigitsOfSSN): FullSSN =
    FullSSN.from(First5DigitsOfSSN.fromString(faker.number().digits(5)).unsafe(), lastFour)

  def generateUserPreferences(): UserPreferences = {
    val communicationPreferences =
      CommunicationPreferences(
        announcements = randomBoolean(),
        promotions = randomBoolean(),
        subscriptionUpdates = randomBoolean(),
        signInNotifications = randomBoolean())
    val bettingPreferences = BettingPreferences(autoAcceptBetterOdds = randomBoolean())
    UserPreferences(communicationPreferences, bettingPreferences)
  }

  def generatePersonalDetails(): PunterPersonalDetails = {
    PunterPersonalDetails(
      userName = generateUsername(),
      name = generatePersonalName(),
      email = generateEmail(),
      phoneNumber = generateMobilePhoneNumber(),
      address = generateAddress(),
      dateOfBirth = generateDateOfBirth(),
      gender = Some(randomGender()),
      isTestAccount = false,
      document = None,
      isPhoneNumberVerified = randomBoolean())
  }

  def generateUserDetails(): UserDetails = {
    val userName = generateUsername()
    val name = generatePersonalName()
    val email = generateEmail()
    val phoneNumber = generateMobilePhoneNumber()
    val address = generateAddress()
    val gender = randomGender()
    val dateOfBirth = generateDateOfBirth()
    val ssn = generateSocialSecurityNumber()
    val twoFactorAuthEnabled = true
    val userPreferences = generateUserPreferences()
    val termsAgreement = randomTermsAgreement()
    val signUpDate = randomOffsetDateTime()
    val isRegistrationVerified = randomBoolean()
    val isPhoneNumberVerified = randomBoolean()
    val isEmailVerified = randomBoolean()

    UserDetails(
      userName,
      name,
      email,
      phoneNumber,
      address,
      dateOfBirth,
      Some(gender),
      ssn,
      twoFactorAuthEnabled,
      userPreferences,
      termsAgreement,
      signUpDate,
      isRegistrationVerified,
      isPhoneNumberVerified,
      isEmailVerified)
  }

  def generateUserDetailsKeycloak(): UserDetailsKeycloak = KeycloakDataConverter.fromUserDetails(generateUserDetails())

  def generateUserRepresentation(): UserRepresentation = {
    val userDetails = generateUserDetailsKeycloak()
    KeycloakUser().withDetails(userDetails).accountVerified(true).emailVerified(true).enabled(true).value
  }
}
