# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ext_orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('W', 'Processing'), ('R', 'Rejected'), ('A', 'Aborted'), ('O', 'Accepted'), ('C', 'Completed')], db_index=True, max_length=1)),
                ('external_transaction_id', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('nonce', models.CharField(max_length=32)),
                ('total_amount', models.PositiveIntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_orders_as_partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTransactionApiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=ext_orders.models.make_public_key, editable=False, max_length=16, unique=True)),
                ('private_key', models.CharField(default=ext_orders.models.make_private_key, editable=False, max_length=128)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalorder',
            unique_together=set([('partner', 'nonce'), ('partner', 'external_transaction_id')]),
        ),
        migrations.AlterIndexTogether(
            name='externalorder',
            index_together=set([('user', 'partner'), ('user', 'status'), ('user', 'external_transaction_id'), ('user', 'created_at')]),
        ),
    ]
