apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.storageClass }}
parameters:
  type: cbs
provisioner: com.tencent.cloud.csi.cbs
reclaimPolicy: {{.Values.global.reclaimPolicy}}
volumeBindingMode: Immediate
