// flow-typed signature: c032634baa8e98359b79573a2b711f81
// flow-typed version: <<STUB>>/@json2csv/formatters_v7.0.1/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@json2csv/formatters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@json2csv/formatters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@json2csv/formatters/dist/cjs/default' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/Formatter' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/number' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/object' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/string' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/stringExcel' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/stringQuoteOnlyIfNecessary' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/cjs/symbol' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/default' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/Formatter' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/number' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/object' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/string' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/stringExcel' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/stringQuoteOnlyIfNecessary' {
  declare module.exports: any;
}

declare module '@json2csv/formatters/dist/mjs/symbol' {
  declare module.exports: any;
}

// Filename aliases
declare module '@json2csv/formatters/dist/cjs/default.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/default'>;
}
declare module '@json2csv/formatters/dist/cjs/Formatter.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/Formatter'>;
}
declare module '@json2csv/formatters/dist/cjs/index' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs'>;
}
declare module '@json2csv/formatters/dist/cjs/index.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs'>;
}
declare module '@json2csv/formatters/dist/cjs/number.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/number'>;
}
declare module '@json2csv/formatters/dist/cjs/object.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/object'>;
}
declare module '@json2csv/formatters/dist/cjs/string.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/string'>;
}
declare module '@json2csv/formatters/dist/cjs/stringExcel.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/stringExcel'>;
}
declare module '@json2csv/formatters/dist/cjs/stringQuoteOnlyIfNecessary.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/stringQuoteOnlyIfNecessary'>;
}
declare module '@json2csv/formatters/dist/cjs/symbol.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/cjs/symbol'>;
}
declare module '@json2csv/formatters/dist/mjs/default.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/default'>;
}
declare module '@json2csv/formatters/dist/mjs/Formatter.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/Formatter'>;
}
declare module '@json2csv/formatters/dist/mjs/index' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs'>;
}
declare module '@json2csv/formatters/dist/mjs/index.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs'>;
}
declare module '@json2csv/formatters/dist/mjs/number.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/number'>;
}
declare module '@json2csv/formatters/dist/mjs/object.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/object'>;
}
declare module '@json2csv/formatters/dist/mjs/string.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/string'>;
}
declare module '@json2csv/formatters/dist/mjs/stringExcel.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/stringExcel'>;
}
declare module '@json2csv/formatters/dist/mjs/stringQuoteOnlyIfNecessary.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/stringQuoteOnlyIfNecessary'>;
}
declare module '@json2csv/formatters/dist/mjs/symbol.js' {
  declare module.exports: $Exports<'@json2csv/formatters/dist/mjs/symbol'>;
}
