// flow-typed signature: a56f01237034e05162994ec9115b35bd
// flow-typed version: <<STUB>>/@json2csv/plainjs_v^6.1.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@json2csv/plainjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@json2csv/plainjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@json2csv/plainjs/dist/cjs/BaseParser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/dist/cjs' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/dist/cjs/Parser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/dist/cjs/StreamParser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/dist/cjs/utils' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/src/BaseParser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/src' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/src/Parser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/src/StreamParser' {
  declare module.exports: any;
}

declare module '@json2csv/plainjs/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@json2csv/plainjs/dist/cjs/BaseParser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs/BaseParser'>;
}
declare module '@json2csv/plainjs/dist/cjs/index' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs'>;
}
declare module '@json2csv/plainjs/dist/cjs/index.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs'>;
}
declare module '@json2csv/plainjs/dist/cjs/Parser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs/Parser'>;
}
declare module '@json2csv/plainjs/dist/cjs/StreamParser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs/StreamParser'>;
}
declare module '@json2csv/plainjs/dist/cjs/utils.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/dist/cjs/utils'>;
}
declare module '@json2csv/plainjs/src/BaseParser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/src/BaseParser'>;
}
declare module '@json2csv/plainjs/src/index' {
  declare module.exports: $Exports<'@json2csv/plainjs/src'>;
}
declare module '@json2csv/plainjs/src/index.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/src'>;
}
declare module '@json2csv/plainjs/src/Parser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/src/Parser'>;
}
declare module '@json2csv/plainjs/src/StreamParser.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/src/StreamParser'>;
}
declare module '@json2csv/plainjs/src/utils.js' {
  declare module.exports: $Exports<'@json2csv/plainjs/src/utils'>;
}
