app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?EEG_WAYSUN_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    definition = "stella-messaging.default-achievement-definition"
    aggregated = "stella-streaming.default-aggregation-aggregated"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
  target-topics {
    achievement = "stella-streaming.default-achievement-achieved"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
}
