identity-provider {
  crypt {
    libsodium-path: "string"
    secret-box-hex-key: "string"
  }
  allow-access-token-authorization: "boolean"
  event-ingestor {
    base-url: "string"
    admin-event-endpoint-path: "string"
    publisher {
      username: "string"
      realm: "string"
      client-id: "string"
      minimum-remaining-seconds-to-expire: "int"
    }
  }
}
