include "application-base"

# Cf. https://doc.akka.io/docs/akka-management/current/kubernetes-deployment/forming-a-cluster.html#configuring-cluster-bootstrap

akka {
  loglevel = DEBUG

  cluster {
    roles = ["bets", "wallets", "markets", "punters"]

    # Shutdown if cluster formation doesn’t work. This will cause Kubernetes to re-create the pod.
    shutdown-after-unsuccessful-join-seed-nodes = 600s
  }

  diagnostics.recorder.enabled = off

  # Exit the JVM on ActorSystem termination to allow Kubernetes to re-create the pod.
  coordinated-shutdown.exit-jvm = on

  management {
    cluster.bootstrap.contact-point-discovery {
      discovery-method = kubernetes-api
      # The usage of this env var is the default (see reference.conf), but let's re-state it here for clarity.
      service-name = ${AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME}
      required-contact-point-nr = ${REQUIRED_CONTACT_POINT_NR}
    }
  }

  discovery.kubernetes-api.pod-label-selector = ${AKKA_DISCOVERY_KUBERNETES_API_POD_LABEL_SELECTOR}
}

akka-http-cors {
  # Space-separated hosts with required scheme and optional wildcards are expected, e.g.
  # allowed-origins = "http://example.com http://*.example.com"
  allowed-origins = ${AKKA_HTTP_CORS_ALLOWED_ORIGINS}
}
