phoenix {
  jwt {
    require-jwt-authentication = true    # Feature flag to active/deactivate JWT authentication
    default-user-id = "SoftAlan"         # Default username to use if JWT authentication is off
  }
}