phoenix {
  betgenius {
    # Toggle on/off to enable data ingestion from betgenius. Set to 'no' to prevent data ingestion clogging the logs
    data-ingestion-enabled = no
    data-ingestion-enabled = ${?PHOENIX_BETGENIUS_DATA_INGESTION_ENABLED}
  }
}
