twilio {
  verification-service-id = VA95426cbc551229d2c6cbe87b12d11b5b
  verification-service-id = ${?TWILIO_VERIFICATION_SERVICE_ID}

  account-service-id = AC0ef9b0f1c1b3d28795fd7d787e219dd6
  account-service-id = ${?TWILIO_ACCOUNT_SERVICE_ID}

  auth-token = "TWILIO-AUTH-TOKEN-CHANGE-ME-TO-RUN-INTEGRATION-TEST"
  auth-token = ${?TWILIO_AUTH_TOKEN}

  verify-api-base-url = "I-SHOULD-BE-CHANGED"
  verify-api-base-url = ${?TWILIO_VERIFY_API_BASE_URL}
}
