phoenix {
  wallets {
    projections {
      wallet-transactions-view.name = "wallet-transactions-view"
      responsibility-check-task-scheduling.name = "responsibility-check-task-scheduling"
      bet-finalizer.name = "bet-finalizer"
      wallet-punter-status.name = "wallet-punter-status"
    }
    consume-responsibility-check-tasks {
      periodic-worker {
        name = "consume-responsibility-check-tasks-worker"
        schedule = "mode=recurring,every=5.minutes"
        time-restriction = 2.minute
        max-retries = 0
      }
    }
  }
}
