slick {
  dbs {
    default {
      profile = "slick.jdbc.PostgresProfile$"
      db {
        driver = "org.postgresql.Driver"
        url = "jdbc:postgresql://localhost:5432/predictor"
        url = ${?DB_DATABASEURL}
        user = "postgres"
        user = ${?DB_USERNAME}
        password = "postgres"
        password = ${?DB_PASSWORD}
        queueSize=5000
        numThreads=8
        connectionTimeout=3000
        maximumPoolSize=100
      }
    }
  }
}