kind: ConfigMap
apiVersion: v1
metadata:
  name: setup-realm-and-client
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "930"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  {{ (.Files.Glob "scripts/setup-realm-and-client.sh").AsConfig | nindent 2 }}
