kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: setup-keycloak-db-secret-for-postgres-operator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, create, patch]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: setup-keycloak-db-secret-for-postgres-operator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: setup-keycloak-db-secret-for-postgres-operator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
subjects:
- kind: ServiceAccount
  name: setup-keycloak-db-secret-for-postgres-operator
roleRef:
  kind: Role
  name: setup-keycloak-db-secret-for-postgres-operator
  apiGroup: rbac.authorization.k8s.io
