// flow-typed signature: e232e0590cb19e7332cbbca143301ca0
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.21.3/flow_v0.190.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
