// flow-typed signature: ada4c8b245110ff53cd4c80801bac147
// flow-typed version: <<STUB>>/@babel/plugin-transform-react-jsx_v^7.21.0/flow_v0.190.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-react-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-react-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-react-jsx/lib/create-plugin' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-react-jsx/lib/development' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-react-jsx/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-react-jsx/lib/create-plugin.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-jsx/lib/create-plugin'>;
}
declare module '@babel/plugin-transform-react-jsx/lib/development.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-jsx/lib/development'>;
}
declare module '@babel/plugin-transform-react-jsx/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-jsx/lib'>;
}
declare module '@babel/plugin-transform-react-jsx/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-jsx/lib'>;
}
