sbTech {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    casino-bets = "gmx-messaging.%s-ds-casinobets"
    customer-details = "gmx-messaging.%s-ds-customerdetails"
    sport-bets-info = "gmx-messaging.%s-ds-sportbets"
    wallet-transaction = "gmx-messaging.%s-ds-wallettransaction"
    customer-deposit = "gmx-messaging.%s-ds-customerdeposit"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }

  target-topics {
    rewards-point-topic = "gmx-messaging.%s-reward-points-topup"
    customer-upsert-topic = "gmx-messaging.%s-customer-upsert"
    bets-filtered = "gmx-tracking.%s-sbtech-bets-filtered"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }

}

include "dev.conf"