nameOverride: "dev-gstech-campaignserver-client-service"
fullnameOverride: "dev-gstech-campaignserver-client-service"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

service:
  enabled: true
  type: ClusterIP
  port: 3051

ingress:
  enabled: false

env:
  NODE_ENV: development
  ENDPOINT: http://dev-gstech-campaignserver-backend-service/api/v1

secretEnv:
  REACT_APP_GOOGLE_CLIENT_ID:
    dev-gstech-campaignserver-client-service: google-client-id
  REACT_APP_GOOGLE_CLIENT_SECRET:
    dev-gstech-campaignserver-client-service: google-client-secret
