version: '3'

services:
  gstech-campaignserver:
    build:
      context: ../../
      dockerfile: packages/gstech-campaignserver/Dockerfile
    image: gstech-campaignserver
    container_name: gstech-campaignserver
    ports:
      - "3013:3013"
    networks:
      - gstech
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: development
      REDIS_HOST: gstech-redis
      POSTGRES_HOST: gstech-postgres
      POSTGRES_DATABASE: campaignserver
      BACKEND_URL: http://gstech-backend:3001
      REWARD_SERVER_URL: http://gstech-rewardserver:3012/api/v1
      CI_DEP: ${CI_DEP:-false} # disable slack messaging when starting as a CI dependency
    healthcheck:
      test: wget http://localhost:3013/api/v1/status -q -O - > /dev/null 2>&1
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10
networks:
  gstech:
    external: true
