#!/bin/bash

set -e -o pipefail -u

if [[ $# -ne 3 ]]; then
  echo "Usage: $(basename $0) <subdirectory> <keycloak-realm> <keycloak-url>"
  echo
  echo "Example: $(basename $0) outpost-stg phoenix https://localhost:8443/auth"
  exit 1
fi

subdirectory=$1
keycloak_realm=$2
keycloak_url=$3

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null || exit; pwd -P)

function has_yq() {
  command -v yq >/dev/null 2>&1
}

function yaml_first_key() {
  local file=$1
  if has_yq; then
    yq eval '. | keys | .[0]' "$file"
  else
    ruby -ryaml -e 'data = YAML.load_file(ARGV[0]); puts data.keys.first' "$file"
  fi
}

function yaml_get() {
  local file=$1
  local path=$2
  if has_yq; then
    yq eval ".$path" "$file"
  else
    ruby -ryaml -e '
      data = YAML.load_file(ARGV[0])
      value = ARGV[1].split(".").reduce(data) { |acc, key| acc.fetch(key) }
      puts value
    ' "$file" "$path"
  fi
}

function yaml_sequence_to_json_lines() {
  local file=$1
  if has_yq; then
    yq eval -o=json --indent=0 '.[]' "$file"
  else
    ruby -ryaml -rjson -e '
      YAML.load_file(ARGV[0]).each do |item|
        puts JSON.generate(item)
      end
    ' "$file"
  fi
}

# On Jenkins, $script_dir might contain spaces... hence we need to delegate globbing to `find -name ...`
# rather than rely on shell globbing.
find "$script_dir/users/$subdirectory/" -name "users_*.yaml" | while read -r users_file; do

  vault_checked=false

  function check_vault() {
    if [[ $vault_checked != true ]]; then
      if ! op item list --vault="$onepassword_vault" >/dev/null; then
        echo 'Make sure that `op` (1Password) CLI is installed,' 1>&2
        echo "you are signed in and have write access to '${onepassword_vault}' 1Password vault, as defined in $passwords_file." 1>&2
        exit 1
      fi
      vault_checked=true
    fi
  }

  function generate_or_retrieve_password() {
    passwords_file=${users_file/\/users_/\/passwords_}
    if ! [[ -f "$passwords_file" ]]; then
      echo "$passwords_file does NOT exist, aborting" 1>&2
      exit 1
    fi

    top_level_key=$(yaml_first_key "$passwords_file")
    case $top_level_key in
      savePasswordsUnder)

        onepassword_vault=$(yaml_get "$passwords_file" "savePasswordsUnder.vault")
        check_vault

        onepassword_item_title_prefix=$(yaml_get "$passwords_file" "savePasswordsUnder.itemTitlePrefix")
        onepassword_item_title=${onepassword_item_title_prefix}${username}
        echo "Creating $onepassword_item_title item in $onepassword_vault 1Password vault..." 1>&2

        op item delete --vault="$onepassword_vault" "$onepassword_item_title" 2>/dev/null || true

        uuid=$(op item create \
          --category login \
          --vault "$onepassword_vault" \
          --title "$onepassword_item_title" \
          --url "$PHOENIX_API_ROUTE" \
          "username=$username" \
          --generate-password \
          --tags 'autogenerated' \
          | jq -r '.uuid')

        op item get --fields=password "$uuid"

        echo "NOTE: make sure that user $username has access to $onepassword_vault 1Password vault!" 1>&2
        ;;

      takePasswordFrom)

        onepassword_vault=$(yaml_get "$passwords_file" "takePasswordFrom.vault")
        check_vault

        onepassword_item_title=$(yaml_get "$passwords_file" "takePasswordFrom.itemTitle")

        echo "Retrieving $onepassword_item_title item from $onepassword_vault 1Password vault..." 1>&2

        op item get --vault=$onepassword_vault --fields=password "$onepassword_item_title"
        ;;

      fixedPassword)
        yaml_get "$passwords_file" "fixedPassword"
        ;;

      *)
        echo "Unknown top-level key in $passwords_file: '$top_level_key', aborting" 1>&2
        exit 1
    esac
  }

  # Note that the individual jsons may still contain spaces (e.g. in `lastName` field)...
  # and `for` splits tokens on all whitespace characters by default.
  # To avoid hacking around `IFS` shell variable, let's use `... | while read -r ...; do` construct instead
  # (which only takes newlines and not spaces into account).
  yaml_sequence_to_json_lines "$users_file" | while read -r user_json; do

    username=$(jq -r '.username' <<< "$user_json")
    admin=$(jq -r '.admin // false' <<< "$user_json")
    roles_csv=$(jq -r '(.roles // []) | join(",")' <<< "$user_json")
    desired_roles=()
    if [[ -n "$roles_csv" ]]; then
      while IFS= read -r role_name; do
        if [[ -n "$role_name" ]]; then
          desired_roles+=("$role_name")
        fi
      done < <(tr ',' '\n' <<< "$roles_csv")
    fi
    if [[ "$admin" == "true" ]]; then
      desired_roles+=("admin")
    fi
    if "$script_dir"/does_keycloak_user_exist.sh "$keycloak_realm" "$keycloak_url" "$username"; then
      echo "User $username already exists in Keycloak, skipping"
      if [[ ${#desired_roles[@]} -gt 0 ]]; then
        echo "Ensuring roles [$(printf '%s ' "${desired_roles[@]}" | sed 's/[[:space:]]*$//')] for existing user $username"
        "$script_dir"/grant_roles_to_keycloak_user.sh "$keycloak_realm" "$keycloak_url" "$username" "${desired_roles[@]}"
      fi
      continue
    fi

    email=$(jq -r '.email' <<< "$user_json")
    first_name=$(jq -r '.firstName' <<< "$user_json")
    last_name=$(jq -r '.lastName' <<< "$user_json")
    initial_balance=$(jq -r '.balance // 0' <<< "$user_json")
    phone_number=$(jq -r '.phoneNumber // "+447897013441"' <<< "$user_json")
    password=$(generate_or_retrieve_password)

    printf 'Trying to register user [username = %-20s email = %-45s name = %-25s initial_balance = $%-4s admin = %-5s roles = %-20s]\n' "$username" "$email" "$first_name $last_name" "$initial_balance" "$admin" "${roles_csv:-none}"
    if USER_PASSWORD="$password" "$script_dir"/sign_up_user.sh "$keycloak_realm" "$keycloak_url" "$username" "$email" "$first_name" "$last_name" "$initial_balance" "$phone_number" "$admin" "$roles_csv"; then
      echo "Registered successfully"
    else
      echo "Registration failed, aborting..."
      exit 1
    fi
  done
done
