# Generated by Django 3.1 on 2020-08-10 21:50

import uuid

import django.db.models.deletion
from django.db import migrations, models

import oidc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oidc_provider", "0026_client_multiple_response_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcClientExtra",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OidcPermissions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255, unique=True, validators=[oidc.models.ASCIIValidator()])),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SocialSecret",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("social_type", models.CharField(choices=[("wc", "WeChat")], db_index=True, max_length=2)),
                ("client_id", models.CharField(max_length=200)),
                ("client_secret", models.CharField(max_length=200)),
                (
                    "oidc_client_extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_secrets",
                        to="oidc.oidcclientextra",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="oidcclientextra",
            name="default_permissions_list",
            field=models.ManyToManyField(
                blank=True, related_name="_oidcclientextra_default_permissions_list_+", to="oidc.OidcPermissions"
            ),
        ),
        migrations.AddField(
            model_name="oidcclientextra",
            name="limited_permissions_list",
            field=models.ManyToManyField(
                blank=True, related_name="_oidcclientextra_limited_permissions_list_+", to="oidc.OidcPermissions"
            ),
        ),
        migrations.AddField(
            model_name="oidcclientextra",
            name="oidc_client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="extra", to="oidc_provider.client"
            ),
        ),
    ]
