# Generated by Django 3.1 on 2020-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0004_auto_20200811_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialsecret",
            name="social_type",
            field=models.CharField(choices=[("wc", "WECHAT"), ("cm", "CHINA_MOBILE")], db_index=True, max_length=2),
        ),
    ]
