# Generated by Django 3.1 on 2020-08-18 23:57

from django.db import migrations, models

import oidc.models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0005_auto_20200818_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialsecret",
            name="social_type",
            field=models.CharField(
                choices=[
                    (oidc.models.SocialSecret.SocialTypeChoices["WECHAT"], "WECHAT"),
                    (oidc.models.SocialSecret.SocialTypeChoices["CHINA_MOBILE"], "CHINA_MOBILE"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
    ]
