kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: luckydino-prd-deployments
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prod-gstech-metabase
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prod

  source:
    repoURL: "git@github.com:LuckyDino/gstech-argocd.git"
    path: helm/luckydino-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../metabase/common.yaml
        - ../metabase/prod.yaml

  project: prod-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
