/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class NFLDataSchedulerSuite extends FunSuite {
  test("someLibraryMethod is always true") {
    assert(true)
  }
}
