replicaCount: 1
heapOptions: >-
  -XX:MaxRAMPercentage=85.0 
  -XX:InitialRAMPercentage=85.0 
kafka:
  bootstrapServers: "PLAINTEXT://kafka.streaming.svc.cluster.local:9092"

resources:
  limits:
    cpu: 250m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 1Gi

podAnnotations: {}
nodeSelector: {}
tolerations: []
imagePullPolicy: Always
customEnv: {}
servicePort: 8081

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: nodes-type
              operator: In
              values:
                - streaming-nodes
        weight: 1
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodes-type
              operator: In
              values:
                - streaming-nodes

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

jmx:
  port: 5555
  expose: true

prometheus:
  jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    imagePullPolicy: Always
    port: 5556
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 128Mi
