# Generated by Django 3.1 on 2020-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0002_oidcclientextra_user"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="oidc_default_permissions_list",
            field=models.ManyToManyField(
                blank=True, related_name="_customuser_oidc_default_permissions_list_+", to="oidc.OidcPermissions"
            ),
        ),
    ]
