# Generated by Django 3.1 on 2020-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0004_auto_20200811_1310"),
        ("profiles", "0003_auto_20200811_1238"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="oidc_default_permissions_list",
        ),
        migrations.AddField(
            model_name="customuser",
            name="oidc_default_permissions_set",
            field=models.ManyToManyField(
                blank=True, related_name="_customuser_oidc_default_permissions_set_+", to="oidc.OidcPermissions"
            ),
        ),
    ]
