# Generated by Django 3.1 on 2020-08-13 09:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_auto_20200811_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sub",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
