# Generated by Django 3.1 on 2020-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_socialaccountdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccountdetails",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="socialaccountdetails",
            name="social_account_extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
