# Generated by Django 3.1.2 on 2020-11-23 12:29

import django.contrib.auth.validators
from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_auto_20200818_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default=profiles.utils.get_random_display_name,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
