helm:
  parameters:
  - name: image.repository
    value: 743851384875.dkr.ecr.eu-central-1.amazonaws.com/affmore-client
    forcestring: true
  - name: image.tag
    value: beta-75d3b71214614e69a998e7e0459047db7838dea3
    forcestring: true
