app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?EEG_WAYSUN_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    definition = "eeg-messaging.%s-event-definition"
    raw = "eeg-streaming.%s-event-raw"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
  target-topics {
    validated = "eeg-streaming.%s-event-validated"
    failed = "eeg-streaming.%s-event-failed"
    schema-registry = "http://schema-registry.eeg.prod.internal:8081"
    schema-registry = ${?EEG_WAYSUN_KAFKA_SCHEMA_REGISTRY_URL}
  }
}

include "dev.conf"