app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    customer-details = "ds_customerdetails_%d"
    schema-registry = "http://datastream-schema.sbtech.info"
  }
  target-topics {
    notifications = "gmx-messaging.notification-events"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
  }
}

include "dev.conf"