# Used for the manifest handling.
app.storage.headers.key=CamelFileName


# Intake storage
app.storage.intake.endpoint.uri=file:${app.env.storage.file.dir}

# Silks storage
app.storage.silks.endpoint.uri=file:${app.env.storage.file.dir}