swagger: "2.0"
info:
  description: "Gstech-backend Wallet API"
  version: "0.0.1"
  title: "Gstech-backend Wallet API"
host: "localhost:3005"
basePath: "/api/v1/wallet"
schemes:
  - "http"
  - "https"
paths:
  /session/{manufacturerId}/{sessionId}:
    get:
      description: Get player by session
      summary: Get player by session
      parameters:
        - in: path
          name: manufacturerId
          type: string
          required: true
        - in: path
          name: sessionId
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PlayerWithBalanceAndSessions'
        404:
          description: Session not active
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      description: Update
      summary: Update
      parameters:
        - in: path
          name: manufacturerId
          type: string
          required: true
        - in: path
          name: sessionId
          type: string
          required: true
      responses:
        200:
          description: OK
    delete:
      description: Delete
      summary: Delete
      parameters:
        - in: path
          name: manufacturerId
          type: string
          required: true
        - in: path
          name: sessionId
          type: string
          required: true
      responses:
        200:
          description: OK
  /session/{manufacturerId}/{sessionId}/{type}:
    post:
      description: Create new manufacturer session
      summary: Create new manufacturer session
      parameters:
        - in: path
          name: manufacturerId
          type: string
          required: true
        - in: path
          name: sessionId
          type: string
          required: true
        - in: path
          name: "type"
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CreateSessionBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PlayerWithBalanceAndSessions'
  /session/{manufacturerId}/{type}:
    post:
      description: Create manufacturer session
      summary: Create manufacturer session
      parameters:
        - in: path
          name: manufacturerId
          type: string
          required: true
        - in: path
          name: "type"
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CreateSessionBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PlayerWithBalanceAndSessions'
  /player/id/{brandId}/{username}:
    get:
      description: Get player by username
      summary: Get player by username
      parameters:
        - in: path
          name: brandId
          type: string
          required: true
        - in: path
          name: username
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Player'
        404:
          description: Player not found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /player/{playerId}:
    get:
      description: Get player details
      summary: Get player details
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PlayerWithBalance'
  /player/{playerId}/bet:
    post:
      description: Place bet
      summary: Place bet
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PlaceBetBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PlaceBetResponse'
        400:
          description: Processing bet failed
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: Game not found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /player/{playerId}/win:
    post:
      description: Process win
      summary: Process win
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/ProcessWinBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/BetResponse'
        400:
          description: Processing win failed
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: Game not found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /player/{playerId}/close:
    post:
      description: Close round
      summary: Close round
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CloseRoundBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CloseRoundResponse'
        400:
          description: Closing round failed
          schema:
            $ref: '#/definitions/ErrorResponse'
  /player/{playerId}/transactions:
    get:
      description: Get transactions
      summary: Get transactions
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: query
          name: brandId
          type: string
          required: true
        - in: query
          name: manufacturer
          type: string
          required: true
        - in: query
          name: transactionId
          type: string
          required: true
        - in: query
          name: gameRoundId
          type: string
          required: false
        - in: query
          name: timestamp
          type: string
          required: false
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Transactions'
    delete:
      description: Cancel transaction
      summary: Cancel transaction
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CancelTransactionBody'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CancelTransactionResponse'
        400:
          description: Cancelling transaction failed
          schema:
            $ref: '#/definitions/ErrorResponse'
  /player/{playerId}/round:
    get:
      description: Get round transactions
      summary: Get round transactions
      parameters:
        - in: path
          name: playerId
          type: number
          required: true
        - in: query
          name: manufacturer
          type: string
          required: true
        - in: query
          name: gameRoundId
          type: string
          required: true
        - in: query
          name: timestamp
          type: string
          required: false
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Transactions'
definitions:
  CreateSessionBody:
    type: object
    required:
      - id
      - sessionId
      - playerId
    properties:
      id:
        type: string
      parameters:
        type: object
      sessionId:
        type: number
      playerId:
        type: number
  Balance:
    type: object
    properties:
      balance:
        type: number
      bonusBalance:
        type: number
      numDeposits:
        type: number
      currencyId:
        type: string
      brandId:
        type: string
  Player:
    type: object
    properties:
      id:
        type: number
      username:
        type: string
      brandId:
        type: string
      createdAt:
        type: string
        format: date-time
      testPlayer:
        type: boolean
      verified:
        type: boolean
      nationalId:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      address:
        type: string
      postCode:
        type: string
      city:
        type: string
      mobilePhone:
        type: string
      countryId:
        type: string
      dateOfBirth:
        type: string
      languageId:
        type: string
      currencyId:
        type: string
      tcVersion:
        type: number
      activated:
        type: boolean
      placeOfBirth:
        type: string
      nationality:
        type: string
      additionalFields:
        type: object
  PlayerWithBalance:
    allOf:
      - $ref: '#/definitions/Player'
      - $ref: '#/definitions/Balance'
  PlayerWithBalanceAndSessions:
    type: object
    properties:
      player:
        $ref: '#/definitions/PlayerWithBalance'
      sessions:
        type: array
        items:
          $ref: '#/definitions/Session'
  Session:
    type: object
    properties:
      manufacturerId:
        type: string
      sessionId:
        type: string
      "type":
        type: string
      parameters:
        type: object
  WinsArray:
    type: array
    items:
      type: object
      properties:
        "type":
          type: string
          enum: [ 'win', 'freespins', 'pooled_jackpot', 'jackpot' ]
        amount:
          type: number
        transactionId:
          type: string
  PlaceBetBody:
    type: object
    required:
      - brandId
      - manufacturer
      - game
      - closeRound
      - amount
      - gameRoundId
      - transactionId
    properties:
      brandId:
        type: string
      manufacturer:
        type: string
      game:
        type: string
      useGameId:
        type: boolean
      sessionId:
        type: string
      amount:
        type: number
      wins:
        $ref: '#/definitions/WinsArray'
      gameRoundId:
        type: string
      transactionId:
        type: string
      currencyId:
        type: string
      timestamp:
        type: string
        format: date-time
  PlaceBetResponse:
    allOf:
      - $ref: '#/definitions/BetResponse'
      - properties:
          bonusBalanceUsed:
            type: number
          ops:
            type: array
            items:
              type: object
              properties:
                transactionId:
                  type: string
                amount:
                  type: number
                balance:
                  type: number
                realBalance:
                  type: number
                bonusBalance:
                  type: number
                "type":
                  type: string
  ProcessWinBody:
    type: object
    required:
      - brandId
      - manufacturer
      - game
      - closeRound
      - wins
      - gameRoundId
      - transactionId
    properties:
      brandId:
        type: string
      manufacturer:
        type: string
      game:
        type: string
      useGameId:
        type: boolean
      closeRound:
        type: boolean
      sessionId:
        type: string
      wins:
        $ref: '#/definitions/WinsArray'
      gameRoundId:
        type: string
      transactionId:
        type: string
      currencyId:
        type: string
      timestamp:
        type: string
        format: date-time
      createGameRound:
        type: boolean
  BetResponse:
    allOf:
      - $ref: '#/definitions/CloseRoundResponse'
      - properties:
          transactionId:
            type: string
          existingTransaction:
            type: boolean
  CloseRoundBody:
    type: object
    required:
      - brandId
      - manufacturer
      - gameRoundId
    properties:
      brandId:
        type: string
      manufacturer:
        type: string
      gameRoundId:
        type: string
      timestamp:
        type: string
        format: date-time
  CloseRoundResponse:
    type: object
    properties:
      gameRoundId:
        type: number
      currencyId:
        type: string
      balance:
        type: number
      realBalance:
        type: number
      bonusBalance:
        type: number
  Transactions:
    type: array
    items:
      type: object
      properties:
        amount:
          type: number
        bonusAmount:
          type: number
        gameRoundId:
          type: number
        transactionId:
          type: number
        "type":
          type: string
        balance:
          type: number
        bonusBalance:
          type: number
        currencyId:
          type: string
        bonusBalanceUsed:
          type: boolean
  CancelTransactionBody:
    type: object
    required:
      - brandId
      - manufacturer
      - transactionId
    properties:
      brandId:
        type: string
      manufacturer:
        type: string
      transactionId:
        type: string
      cancelTransactionId:
        type: string
      gameRoundId:
        type: string
      amount:
        type: number
      timestamp:
        type: string
        format: date-time
      currencyId:
        type: string
  CancelTransactionResponse:
    type: object
    properties:
      transactionIds:
        type: array
        items:
          type: string
      transactionFound:
        type: boolean
      alreadyCancelled:
        type: boolean
      invalidTransaction:
        type: boolean
  ErrorResponse:
    type: object
    properties:
      code:
        type: number
      message:
        type: string
