replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  iam.amazonaws.com/role: "iam-role-goes-here"

podSecurityContext: {}

securityContext: {}

service:
  enabled: false
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

verticalAutoscaler:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

minAvailable: 1

nodeSelector: {}

tolerations: []

rbac:
  create: false

podSecurityPolicy:
  create: false

livenessProbe:
  path: /healthz
  port: 5000
  initialDelaySeconds: 40
  periodSeconds: 20
  timeoutSeconds: 20

readinessProbe:
  path: /healthz
  port: 5000
  initialDelaySeconds: 40
  periodSeconds: 20
  timeoutSeconds: 20
