apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-headless
spec:
  clusterIP: None
  ports:
  - name: 6123-6123-tcp
    port: 6123
    protocol: TCP
    targetPort: 6123
  - name: 6124-6124-tcp
    port: 6124
    protocol: TCP
    targetPort: 6124
  - name: 6125-6125-tcp
    port: 6125
    protocol: TCP
    targetPort: 6125
  - name: 6122-6122-tcp
    port: 6122
    protocol: TCP
    targetPort: 6122
  selector:
    app: flink-jobmanager
    k8s-app: flink-jobmanager
    qcloud-app: flink-jobmanager
  sessionAffinity: None
  type: ClusterIP
