apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: flink-taskmanager
    k8s-app: flink-taskmanager
    qcloud-app: flink-taskmanager
  name: flink-taskmanager
spec:
  replicas: {{.Values.taskManager.replicas}}
  selector:
    matchLabels:
      app: flink-taskmanager
      k8s-app: flink-taskmanager
      qcloud-app: flink-taskmanager
  serviceName: "flink-taskmanager-headless"
  template:
    metadata:
      labels:
        app: flink-taskmanager
        k8s-app: flink-taskmanager
        qcloud-app: flink-taskmanager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: nodes-type
                operator: In
                values:
                - {{.Values.taskManager.deploy_on}}
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodes-type
                operator: In
                values:
                - {{.Values.taskManager.deploy_on}}
      containers:
      - args:
        - taskmanager
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIPs
        {{- if .Values.taskManager.customEnv }}
{{ toYaml .Values.taskManager.customEnv | indent 8 }}
        {{end}}
        {{- if .Values.commonCustomEnv }}
{{ toYaml .Values.commonCustomEnv | indent 8 }}
        {{end}}
        image: apache/flink:1.10.3-scala_2.12
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6122
          timeoutSeconds: 5
        name: taskmanager
        resources:
          limits:
            cpu: {{.Values.taskManager.resources.limits.cpu}}
            memory: {{.Values.taskManager.resources.limits.memory}}
          requests:
            cpu: {{.Values.taskManager.resources.requests.cpu}}
            memory: {{.Values.taskManager.resources.requests.memory}}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: flink-pvc-volume
        - mountPath: /opt/flink/conf
          name: flink-config-volume
        - mountPath: /opt/flink/usrlib
          name: flink-pvc-volume
          subPath: flink-userlib
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: flink-pvc-volume
        persistentVolumeClaim:
          claimName: {{.Values.configuration.volume_pvc}}
      - configMap:
          defaultMode: 420
          items:
          - key: flink-conf.yaml
            mode: 438
            path: flink-conf.yaml
          - key: log4j-console.properties
            mode: 438
            path: log4j-console.properties
          name: flink-config
        name: flink-config-volume
