app {
  auth {
    rmx {
      url = "https://api.rewardsmatrix.com"
      client_id = ${RMX_CLIENT_ID}
      client_password = ${RMX_CLIENT_PASSWORD}
      username = ${RMX_USER}
      password = ${RMX_PASSWORD}
      dict {
        company {
          sport-nation = "9577609b-d14f-4f14-ae6d-a6de017e8254"
          red-zone = "7b4b7e86-d9df-44e0-9170-dbfdd5a176fa"
          give-me-bet = "7b9ad578-1200-4aae-9b1f-6b5e0ab28573"
        }
      }
    }
    token {
      expiry {
        offset = 60s
        clock_skew = 0s
      }
    }
    cache {
      config {
        duration = 1h
        resilience = 1m
      }
      jwks {
        duration = 1h
        resilience = 1m
      }
    }
  }
}