# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('fb', 'FACEBOOK'), ('tw', 'TWITTER'), ('g+', 'GOOGLE PLUS')], max_length=2)),
                ('social_id', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='socialuserprofile',
            unique_together=set([('social_type', 'social_id')]),
        ),
    ]
