# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
