# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:03
from __future__ import unicode_literals

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_provider', '0022_auto_20170331_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_social', '0002_auto_20170616_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('fb', 'FACEBOOK'), ('tw', 'TWITTER'), ('g+', 'GOOGLE PLUS')], max_length=2)),
                ('social_token', jsonfield.fields.JSONField(default=dict)),
                ('oidc_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='socialtokens',
            unique_together=set([('user', 'social_type', 'oidc_client')]),
        ),
    ]
