# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_social', '0003_auto_20170628_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtokens',
            name='oidc_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oidc_provider.Client'),
        ),
    ]
