# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_provider', '0022_auto_20170331_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_social', '0004_auto_20170628_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialtokens',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='socialtokens',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='socialtokens',
            unique_together=set([('user', 'oidc_client')]),
        ),
    ]
