# Generated by Django 2.1.7 on 2019-03-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_social', '0005_auto_20170629_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtokens',
            name='oidc_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oidc_provider.Client'),
        ),
        migrations.AlterField(
            model_name='socialtokens',
            name='social_token',
            field=jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='socialtokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialuserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
