# Generated by Django 3.1 on 2020-08-10 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oidc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="oidcclientextra",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_company": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oidc_client_extra",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
