# Generated by Django 3.1 on 2020-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0002_oidcclientextra_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="oidcpermissions",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
