# Generated by Django 3.1 on 2020-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0003_oidcpermissions_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oidcclientextra",
            name="default_permissions_list",
        ),
        migrations.RemoveField(
            model_name="oidcclientextra",
            name="limited_permissions_list",
        ),
        migrations.AddField(
            model_name="oidcclientextra",
            name="default_permissions_set",
            field=models.ManyToManyField(
                blank=True, related_name="_oidcclientextra_default_permissions_set_+", to="oidc.OidcPermissions"
            ),
        ),
        migrations.AddField(
            model_name="oidcclientextra",
            name="limited_permissions_set",
            field=models.ManyToManyField(
                blank=True, related_name="_oidcclientextra_limited_permissions_set_+", to="oidc.OidcPermissions"
            ),
        ),
    ]
