# Generated by Django 3.1.1 on 2020-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0009_externalusermappingmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalusermappingmodel",
            name="external_user_id",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
