app {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?GMX_KAFKA_BOOTSTRAP}
    offset-config = "earliest"
  }
  source-topics {
    customer-details = "gmx-messaging.%s-ds-customerdetails"
    logins = "gmx-messaging.%s-ds-logins"
    wallet-transactions = "gmx-messaging.%s-ds-wallettransactions"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }
  target-topics {
    tags = "gmx-messaging.%s-customer-tagging"
    customer-abuse = "gmx-messaging.%s-customer-abuse"
    schema-registry = "http://schema-registry.gmx.prod.internal:8081"
    schema-registry = ${?GMX_KAFKA_SCHEMA_REGISTRY_URL}
  }
}

include "dev.conf"