stella {
  event-ingestor {
    kafka {
      topic-name = "dev-stella-intake.platform-events"
      topic-name = ${?EVENT_INGESTOR_KAFKA_PLATFORM_EVENTS_TOPIC_NAME}
      bootstrap-servers = "stella.local:9092"
      bootstrap-servers = ${?EVENT_INGESTOR_KAFKA_BOOTSTRAP_SERVERS}

      serializer {
        schema-registry-url = "http://stella.local:8081"
        schema-registry-url = ${?EVENT_INGESTOR_KAFKA_SCHEMA_REGISTRY_URL}
      }

      producer {
        acks = "0"
        client-id = "dev.ingestor_client"
        client-id = ${?EVENT_INGESTOR_KAFKA_CLIENT_ID}
        compression-type = "gzip"
        max-in-flight-requests-per-connection = 1
        max-in-flight-requests-per-connection = ${?EVENT_INGESTOR_KAFKA_MAX_REQUESTS_PER_CONNECTION}
        max-number-of-retries = 0
        publication-time-limit = 1000 milliseconds
        publication-time-limit = ${?EVENT_INGESTOR_KAFKA_PUBLICATION_TIME_LIMIT}
        linger-ms=1000
        linger-ms = ${?EVENT_INGESTOR_KAFKA_LINGER_MS}
        batch-size = 16384
        batch-size = ${?EVENT_INGESTOR_KAFKA_BATCH_SIZE}
      }

      consumer {
        client-id = "dev.ingestor_client"
        client-id = ${?EVENT_INGESTOR_KAFKA_CLIENT_ID}
        group-id = "dev.ingestor_group"
        group-id = ${?EVENT_INGESTOR_KAFKA_GROUP_ID}
        kafka-poll-timeout = 200 milliseconds
        kafka-poll-timeout = ${?EVENT_INGESTOR_KAFKA_POLL_TIMEOUT}
      }
    }
  }
}
