stella {
  event-ingestor {
    redis-persistence {
      collection-name = "dev-ingested-events"
      collection-name = ${?EVENT_INGESTOR_REDIS_PERSISTENCE_COLLECTION_NAME}
      event-to-publish-check-frequency-seconds = 1
      event-to-publish-check-frequency-seconds = ${?EVENT_INGESTOR_REDIS_PERSISTENCE_EVENTS_CHECK_FREQUENCY_SECONDS}
      leader-lock-name = "dev-event-ingestor-leader-lock"
      leader-lock-name = ${?EVENT_INGESTOR_REDIS_PERSISTENCE_LEADER_LOCK_NAME}
      redisson-config-in-resources = true
      redisson-config-in-resources = ${?EVENT_INGESTOR_REDIS_PERSISTENCE_REDISSON_CONFIG_IN_RESOURCES}
      redisson-config-path = "redisson-config.yaml"
      redisson-config-path = ${?EVENT_INGESTOR_REDIS_PERSISTENCE_REDISSON_CONFIG_PATH}
    }
  }
}
