#!groovy

void notifyGithub(String description) {
  githubNotify(
    description: description,
    context: env.GITHUB_NOTIFICATION_CONTEXT,
    account: env.GITHUB_ACCOUNT,
    repo: env.GITHUB_REPO,
    credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
    targetUrl: env.RUN_DISPLAY_URL,
    status: 'SUCCESS'
  )
}

// build status constants: https://www.jenkins.io/doc/book/glossary/#build-status
def notifySlack(String branch, String buildStatus) {

  if (branch == 'master') {

    // Build status of null means success.
    buildStatus = buildStatus ?: 'SUCCESS'

    def color

    if (buildStatus == 'STARTED') {
      color = '#D4DADF'
    } else if (buildStatus == 'SUCCESS') {
      color = '#BDFFC3'
    } else if (buildStatus == 'STABLE') {
      color = '#BDFFC3'
    } else if (buildStatus == 'UNSTABLE') {
      color = '#FFFE89'
    } else { // FAILED or ABORTED
      color = '#FF9FA1'
    }

    def message = "${buildStatus}: <${env.RUN_DISPLAY_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>"

    slackSend(color: color, message: message, channel: env.SLACK_NOTIFICATION_CHANNEL)
  }
}

String shOutput(String cmd) {
  return sh(script: cmd, returnStdout: true).trim()
}

void withGithubStatusUpdates(Closure<Void> block) {
  gitStatusWrapper(
    description: env.STAGE_NAME,
    gitHubContext: env.GITHUB_NOTIFICATION_CONTEXT,
    account: env.GITHUB_ACCOUNT,
    repo: env.GITHUB_REPO,
    credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
    targetUrl: env.RUN_DISPLAY_URL
  ) {
    block()
  }
}

pipeline {
  agent {
    label 'ecs-ec2-java'
  }

  parameters {
    string(name: 'releaseVersionSegmentToUpdate', defaultValue: 'patch', description: 'Which part of a version should be updated during the release. One of: major, minor, patch')
  }

  environment {
    // github status notifications
    GITHUB_ACCOUNT = 'flipadmin'
    GITHUB_REPO = 'gmx-waysun-data-api'
    GITHUB_API_TOKEN_CREDENTIALS_ID = 'CICD-GitHub-API-token'
    GITHUB_NOTIFICATION_CONTEXT = 'Jenkins Build'
    SLACK_NOTIFICATION_CHANNEL = '#gmx-waysun-platform-deployment'

    // build
    SBT_HOME = tool name: 'sbt', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'
    PATH = "${env.SBT_HOME}/bin:${env.HOME}/.local/bin:${env.PATH}"

    // github tags
    COMMIT_HASH = shOutput("git rev-parse HEAD")
    GITHUB_API_URL = "https://api.github.com/repos/${env.GITHUB_ACCOUNT}/${env.GITHUB_REPO}"
    GITHUB_API_REFS_URL = "${env.GITHUB_API_URL}/git/refs"

    // Waysun git repository mirror
    WAYSUN_GIT_CREDENTIALS = 'waysun-git-credentials'
    WAYSUN_GIT_URL = 'github.com/waysuninc/gmx-waysun-data-api.git'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout([
          $class                           : 'GitSCM',
          branches                         : scm.branches,
          doGenerateSubmoduleConfigurations: scm.doGenerateSubmoduleConfigurations,
          extensions                       : [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0, reference: '']],
          userRemoteConfigs                : scm.userRemoteConfigs,
        ])
      }
    }

    stage('Update dependencies') {
      steps {
        withGithubStatusUpdates {
          // -batch to prevent sbt from waiting on user input in case the project model is invalid
          sh 'sbt -batch update'
        }
      }
    }

    stage('Check formatting & code style') {
      steps {
        withGithubStatusUpdates {
          sh 'sbt scalafmtSbtCheck scalafmtCheckAll scalastyle'
        }
      }
    }

    stage('Compile production code') {
      steps {
        withGithubStatusUpdates {
          sh 'sbt "+ compile"'
        }
      }
    }

    stage('Compile test code') {
      steps {
        withGithubStatusUpdates {
          sh 'sbt "+ test:compile"'
        }
      }
    }

    stage('Check scalafix rules') {
      steps {
        withGithubStatusUpdates {
          sh 'sbt "scalafixAll --check"'
        }
      }
    }

    stage('Run tests') {
      steps {
        withGithubStatusUpdates {
          sh 'sbt "+ test"'
        }
      }
    }

    stage('Publish to Nexus') {
      when {
        branch 'master'
      }
      steps {
        withGithubStatusUpdates {
          sh './ci/prepare-release-version ' + params.releaseVersionSegmentToUpdate
          script {
            RELEASE_VERSION = shOutput('git describe --exact-match --abbrev=0 --tags')
          }
          echo "About to release version: ${RELEASE_VERSION}"
          withCredentials([usernamePassword(
            credentialsId: env.GITHUB_API_TOKEN_CREDENTIALS_ID,
            usernameVariable: 'GITHUB_USERNAME',
            passwordVariable: 'GITHUB_PASSWORD')
          ]) {
            sh "curl -f -X POST -d '{\"ref\": \"refs/tags/${RELEASE_VERSION}\", \"sha\":\"${env.COMMIT_HASH}\"}' -H \"Accept: application/vnd.github.v3+json\" -u \"username:${GITHUB_PASSWORD}\" ${env.GITHUB_API_REFS_URL}"
          }
          sh 'sbt "+ publish"'
        }
      }
    }

    stage('Updating Waysun GitRepo') {
      when {
        branch 'master'
      }
      steps {
        withGithubStatusUpdates {
          withCredentials([
            usernamePassword(
              credentialsId: env.WAYSUN_GIT_CREDENTIALS,
              usernameVariable: 'GITHUB_USERNAME',
              passwordVariable: 'GITHUB_PASSWORD'
            )
          ]) {
            sh 'git config --global user.email "waysun-jenkins@waysuninc.com"'
            sh 'git config --global user.name "waysun-jenkins"'
            withCredentials([sshUserPrivateKey(credentialsId: 'github', keyFileVariable: 'SSH_KEY')]) {
              sh 'GIT_SSH_COMMAND="ssh -i $SSH_KEY" git checkout ' + env.BRANCH_NAME
              sh 'GIT_SSH_COMMAND="ssh -i $SSH_KEY" git pull origin ' + env.BRANCH_NAME
            }
            sh 'git remote add waysun https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@' + env.WAYSUN_GIT_URL
            sh "git push -u waysun ${env.BRANCH_NAME}:${env.BRANCH_NAME}"
          }
        }
      }
    }
  }

  post {
    success {
      // This is to ensure that the name of the last executed stage
      // doesn't linger in GitHub's CI status once the pipeline is complete.
      notifyGithub('Complete')
    }

    always {
      notifySlack(env.BRANCH_NAME, currentBuild.result)
    }
  }
}
