# Generated by Django 3.1 on 2020-08-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_customuser_oidc_default_permissions_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="phone_numbers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
