# Generated by Django 3.1 on 2020-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_company_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="max_addresses",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="max_emails",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="max_phone_numbers",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
