# Generated by Django 3.1 on 2020-08-18 17:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_auto_20200818_1333"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccountDetails",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_account_type",
                    models.CharField(choices=[("wc", "WECHAT"), ("cm", "CHINA_MOBILE")], db_index=True, max_length=2),
                ),
                ("social_account_id", models.CharField(max_length=200)),
                ("social_account_extra", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
