// flow-typed signature: 65505bed2c4b08379214f5525c415da7
// flow-typed version: <<STUB>>/chai-xml_v^0.3.2/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-xml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-xml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-xml/Gruntfile' {
  declare module.exports: any;
}

declare module 'chai-xml/src/chai-xml' {
  declare module.exports: any;
}

declare module 'chai-xml/test/chai-xml-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-xml/Gruntfile.js' {
  declare module.exports: $Exports<'chai-xml/Gruntfile'>;
}
declare module 'chai-xml/src/chai-xml.js' {
  declare module.exports: $Exports<'chai-xml/src/chai-xml'>;
}
declare module 'chai-xml/test/chai-xml-spec.js' {
  declare module.exports: $Exports<'chai-xml/test/chai-xml-spec'>;
}
