// flow-typed signature: acdaa2b2c5a4c00cd91433dd8d2bc91d
// flow-typed version: <<STUB>>/maskdata_v^1.0.5/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'maskdata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'maskdata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'maskdata/lib/ExceptionsHandler/BadOption' {
  declare module.exports: any;
}

declare module 'maskdata/lib/helpers/MaskHelper' {
  declare module.exports: any;
}

declare module 'maskdata/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'maskdata/index' {
  declare module.exports: $Exports<'maskdata'>;
}
declare module 'maskdata/index.js' {
  declare module.exports: $Exports<'maskdata'>;
}
declare module 'maskdata/lib/ExceptionsHandler/BadOption.js' {
  declare module.exports: $Exports<'maskdata/lib/ExceptionsHandler/BadOption'>;
}
declare module 'maskdata/lib/helpers/MaskHelper.js' {
  declare module.exports: $Exports<'maskdata/lib/helpers/MaskHelper'>;
}
declare module 'maskdata/test.js' {
  declare module.exports: $Exports<'maskdata/test'>;
}
