app {
  events {
    kafka {
      bootstrap = ${KAFKA_HOST}":"${KAFKA_PORT}
      # GM-221
      topic = collector.pa.horse-racing.xml
      topic = ${?KAFKA_TOPIC}
      group = predictor-events
      group = ${?KAFKA_CONSUMER_GROUP}
      poll = 1s
    }
  }
}