package repository

import (
	"context"
	"testing"
)

func TestStaticRouteRepositoryMatch(t *testing.T) {
	repo := NewStaticRouteRepository()
	tests := []struct {
		name          string
		method        string
		path          string
		wantFound     bool
		wantService   string
		wantRouteName string
	}{
		{name: "exact auth login", method: "POST", path: "/auth/login", wantFound: true, wantService: "phoenix-user", wantRouteName: "auth-login"},
		{name: "provider idcomply callback by case", method: "POST", path: "/providers/idcomply/verification-sessions/by-case/demo-case/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "provider-idcomply-session-status-by-case"},
		{name: "api auth login exact", method: "POST", path: "/api/v1/auth/login", wantFound: true, wantService: "phoenix-user", wantRouteName: "auth-login-api"},
		{name: "api auth login with verification exact", method: "POST", path: "/api/v1/auth/login-with-verification", wantFound: true, wantService: "phoenix-user", wantRouteName: "auth-login-with-verification-api"},
		{name: "auth login with verification exact", method: "POST", path: "/login-with-verification", wantFound: true, wantService: "phoenix-user", wantRouteName: "auth-login-with-verification"},
		{name: "api password forgot exact", method: "POST", path: "/api/v1/password/forgot", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-forgot-api"},
		{name: "password forgot exact", method: "POST", path: "/password/forgot", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-forgot"},
		{name: "api password reset exact", method: "POST", path: "/api/v1/password/reset/reset-token", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-reset-api"},
		{name: "password reset exact", method: "POST", path: "/password/reset/reset-token", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-reset"},
		{name: "verification by email code exact", method: "POST", path: "/verification/request-by-verification-code/123456", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-by-email-code"},
		{name: "api verification request exact", method: "POST", path: "/api/v1/verification/request", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-request-api"},
		{name: "verification request exact", method: "POST", path: "/verification/request", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-request"},
		{name: "api verification request by phone exact", method: "POST", path: "/api/v1/verification/request-by-phone", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-request-by-phone-api"},
		{name: "verification request by phone exact", method: "POST", path: "/verification/request-by-phone", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-request-by-phone"},
		{name: "api verification check exact", method: "POST", path: "/api/v1/verification/check", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-check-api"},
		{name: "verification check exact", method: "POST", path: "/verification/check", wantFound: true, wantService: "phoenix-user", wantRouteName: "verification-check"},
		{name: "registration answer kba exact", method: "POST", path: "/registration/answer-kba-questions", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-answer-kba"},
		{name: "api registration answer kba exact", method: "POST", path: "/api/v1/registration/answer-kba-questions", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-answer-kba-api"},
		{name: "registration check idpv exact", method: "POST", path: "/registration/check-idpv-status", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-check-idpv"},
		{name: "api registration check idpv exact", method: "POST", path: "/api/v1/registration/check-idpv-status", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-check-idpv-api"},
		{name: "registration start idpv exact", method: "POST", path: "/registration/start-idpv", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-start-idpv"},
		{name: "api registration start idpv exact", method: "POST", path: "/api/v1/registration/start-idpv", wantFound: true, wantService: "phoenix-user", wantRouteName: "registration-start-idpv-api"},
		{name: "provider idcomply session status exact", method: "POST", path: "/providers/idcomply/verification-sessions/sess_123/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "provider-idcomply-session-status"},
		{name: "provider idcomply session status by reference exact", method: "POST", path: "/providers/idcomply/verification-sessions/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "provider-idcomply-session-status-by-reference"},
		{name: "geocomply license exact", method: "GET", path: "/geo-comply/license-key", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "geocomply-license-key"},
		{name: "geocomply geo packet exact", method: "POST", path: "/geo-comply/geo-packet", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "geocomply-geo-packet"},
		{name: "api geocomply license exact", method: "GET", path: "/api/v1/geo-comply/license-key", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "geocomply-license-key-api"},
		{name: "api geocomply geo packet exact", method: "POST", path: "/api/v1/geo-comply/geo-packet", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "geocomply-geo-packet-api"},
		{name: "wallet prefix", method: "GET", path: "/api/v1/wallets/usr_123", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "wallets"},
		{name: "market prefix longest match", method: "GET", path: "/api/v1/markets/featured", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "markets"},
		{name: "market liquidity template", method: "GET", path: "/api/v1/markets/mrk_123/liquidity", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "market-liquidity"},
		{name: "user bets template", method: "GET", path: "/api/v1/users/usr_123/bets", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "user-bets"},
		{name: "bets status exact", method: "POST", path: "/api/v1/bets/status", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "bets-status"},
		{name: "legacy punter bets status exact", method: "POST", path: "/punters/bets/status", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "punter-bets-status"},
		{name: "prediction overview exact", method: "GET", path: "/api/v1/prediction/overview", wantFound: true, wantService: "phoenix-prediction", wantRouteName: "prediction-overview"},
		{name: "prediction market detail template", method: "GET", path: "/api/v1/prediction/markets/pmkt_123", wantFound: true, wantService: "phoenix-prediction", wantRouteName: "prediction-market-detail"},
		{name: "prediction bot keys legacy exact", method: "POST", path: "/v1/bot/keys", wantFound: true, wantService: "phoenix-prediction", wantRouteName: "prediction-bot-keys-legacy"},
		{name: "prediction bot keys api exact", method: "POST", path: "/api/v1/bot/keys", wantFound: true, wantService: "phoenix-prediction", wantRouteName: "prediction-bot-keys-api"},
		{name: "legacy terms exact", method: "GET", path: "/terms", wantFound: true, wantService: "phoenix-config", wantRouteName: "terms-public-legacy"},
		{name: "terms current public exact", method: "GET", path: "/api/v1/terms/current", wantFound: true, wantService: "phoenix-config", wantRouteName: "terms-current-public"},
		{name: "terms accept legacy exact", method: "PUT", path: "/terms/accept", wantFound: true, wantService: "phoenix-user", wantRouteName: "terms-accept-legacy"},
		{name: "terms accept api exact", method: "PUT", path: "/api/v1/terms/accept", wantFound: true, wantService: "phoenix-user", wantRouteName: "terms-accept"},
		{name: "current session legacy exact", method: "GET", path: "/punters/current-session", wantFound: true, wantService: "phoenix-user", wantRouteName: "current-session-legacy"},
		{name: "token refresh exact", method: "POST", path: "/token/refresh", wantFound: true, wantService: "phoenix-user", wantRouteName: "token-refresh"},
		{name: "account activate exact", method: "PUT", path: "/account/activate/verify-token", wantFound: true, wantService: "phoenix-user", wantRouteName: "account-activate"},
		{name: "punter deposit limits exact", method: "POST", path: "/punters/deposit-limits", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-deposit-limits"},
		{name: "punter stake limits exact", method: "POST", path: "/punters/stake-limits", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-stake-limits"},
		{name: "punter session limits exact", method: "POST", path: "/punters/session-limits", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-session-limits"},
		{name: "punter limits history exact", method: "GET", path: "/punters/limits-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-limits-history"},
		{name: "punter cool off exact", method: "POST", path: "/punters/cool-off", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-cool-off"},
		{name: "punter self exclude exact", method: "POST", path: "/punters/self-exclude", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-self-exclude"},
		{name: "punter cool offs history exact", method: "GET", path: "/punters/cool-offs-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "punter-cool-offs-history"},
		{name: "responsibility check accept exact", method: "PUT", path: "/responsibility-check/accept", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "responsibility-check-accept"},
		{name: "profile me exact", method: "GET", path: "/profile/me", wantFound: true, wantService: "phoenix-user", wantRouteName: "profile-me"},
		{name: "profile update exact", method: "PUT", path: "/profile", wantFound: true, wantService: "phoenix-user", wantRouteName: "profile-update"},
		{name: "profile preferences update exact", method: "PUT", path: "/profile/preferences", wantFound: true, wantService: "phoenix-user", wantRouteName: "profile-preferences-update"},
		{name: "profile mfa update exact", method: "PUT", path: "/profile/multi-factor-authentication", wantFound: true, wantService: "phoenix-user", wantRouteName: "profile-mfa-update"},
		{name: "api password change exact", method: "POST", path: "/api/v1/password/change", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-change-api"},
		{name: "password change exact", method: "POST", path: "/password/change", wantFound: true, wantService: "phoenix-user", wantRouteName: "password-change"},
		{name: "api punter delete exact", method: "POST", path: "/api/v1/punters/delete", wantFound: true, wantService: "phoenix-user", wantRouteName: "punter-delete-api"},
		{name: "punter delete exact", method: "POST", path: "/punters/delete", wantFound: true, wantService: "phoenix-user", wantRouteName: "punter-delete"},
		{name: "compliance limit history exact", method: "GET", path: "/api/v1/users/usr_123/limits/history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "compliance-get-limit-history"},
		{name: "compliance cool off history exact", method: "GET", path: "/api/v1/users/usr_123/cool-offs/history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "compliance-cool-off-history"},
		{name: "match tracker fixture exact", method: "GET", path: "/api/v1/match-tracker/fixtures/f%3Alocal%3A001", wantFound: true, wantService: "phoenix-events", wantRouteName: "match-tracker-fixture"},
		{name: "fixture stats exact", method: "GET", path: "/api/v1/stats/fixtures/f%3Alocal%3A001", wantFound: true, wantService: "phoenix-events", wantRouteName: "fixture-stats"},
		{name: "provider event upsert exact", method: "POST", path: "/api/v1/providers/events/upsert", wantFound: true, wantService: "phoenix-events", wantRouteName: "provider-event-upsert"},
		{name: "provider mockdata events sync exact", method: "POST", path: "/api/v1/providers/mockdata/events/sync", wantFound: true, wantService: "phoenix-events", wantRouteName: "provider-mockdata-events-sync"},
		{name: "provider oddin events sync exact", method: "POST", path: "/api/v1/providers/oddin/events/sync", wantFound: true, wantService: "phoenix-events", wantRouteName: "provider-oddin-events-sync"},
		{name: "provider betgenius events sync exact", method: "POST", path: "/api/v1/providers/betgenius/events/sync", wantFound: true, wantService: "phoenix-events", wantRouteName: "provider-betgenius-events-sync"},
		{name: "provider mockdata markets sync exact", method: "POST", path: "/api/v1/providers/mockdata/markets/sync", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "provider-mockdata-markets-sync"},
		{name: "provider oddin markets sync exact", method: "POST", path: "/api/v1/providers/oddin/markets/sync", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "provider-oddin-markets-sync"},
		{name: "provider betgenius markets sync exact", method: "POST", path: "/api/v1/providers/betgenius/markets/sync", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "provider-betgenius-markets-sync"},
		{name: "payments deposit exact", method: "POST", path: "/payments/deposit", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "payments-deposit"},
		{name: "payments withdrawal exact", method: "POST", path: "/payments/withdrawal", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "payments-withdrawal"},
		{name: "payments cash withdrawal exact", method: "POST", path: "/payments/cash-withdrawal", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "payments-cash-withdrawal"},
		{name: "payments cheque withdrawal exact", method: "POST", path: "/payments/cheque-withdrawal", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "payments-cheque-withdrawal"},
		{name: "payments transaction details exact", method: "GET", path: "/payments/transactions/tx-123", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "payments-transaction-details"},
		{name: "admin payments transactions exact", method: "GET", path: "/admin/payments/transactions", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transactions"},
		{name: "admin payments transactions export exact", method: "GET", path: "/admin/payments/transactions/export", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transactions-export"},
		{name: "admin payments transaction summary exact", method: "GET", path: "/admin/payments/transactions/summary", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-summary"},
		{name: "admin payments reconciliation queue exact", method: "GET", path: "/admin/payments/transactions/reconciliation-queue", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-reconciliation-queue"},
		{name: "admin payments reconciliation queue export exact", method: "GET", path: "/admin/payments/transactions/reconciliation-queue/export", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-reconciliation-queue-export"},
		{name: "admin payments transaction reconcile preview exact", method: "POST", path: "/admin/payments/transactions/reconcile/preview", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-reconcile-preview"},
		{name: "admin payments transaction reconcile exact", method: "POST", path: "/admin/payments/transactions/reconcile", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-reconcile"},
		{name: "admin payments transaction by provider reference exact", method: "GET", path: "/admin/payments/transactions/by-provider-reference/pxp_123", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-by-provider-reference"},
		{name: "admin payments transaction events by provider reference exact", method: "GET", path: "/admin/payments/transactions/by-provider-reference/pxp_123/events", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-events-by-provider-reference"},
		{name: "admin payments transaction assign by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/assign", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-assign-by-provider-reference"},
		{name: "admin payments transaction note by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/notes", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-note-by-provider-reference"},
		{name: "admin payments transaction status by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/status", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-status-by-provider-reference"},
		{name: "admin payments transaction approve by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/approve", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-approve-by-provider-reference"},
		{name: "admin payments transaction decline by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/decline", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-decline-by-provider-reference"},
		{name: "admin payments transaction settle by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/settle", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-settle-by-provider-reference"},
		{name: "admin payments transaction refund by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/refund", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-refund-by-provider-reference"},
		{name: "admin payments transaction reverse by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/reverse", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-reverse-by-provider-reference"},
		{name: "admin payments transaction chargeback by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/chargeback", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-chargeback-by-provider-reference"},
		{name: "admin payments transaction retry by provider reference exact", method: "POST", path: "/admin/payments/transactions/by-provider-reference/pxp_123/retry", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-retry-by-provider-reference"},
		{name: "admin payments transaction details exact", method: "GET", path: "/admin/payments/transactions/tx-123", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-details"},
		{name: "admin payments transaction events exact", method: "GET", path: "/admin/payments/transactions/tx-123/events", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-events"},
		{name: "admin payments transaction assign exact", method: "POST", path: "/admin/payments/transactions/tx-123/assign", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-assign"},
		{name: "admin payments transaction note exact", method: "POST", path: "/admin/payments/transactions/tx-123/notes", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-note"},
		{name: "admin payments transaction approve exact", method: "POST", path: "/admin/payments/transactions/tx-123/approve", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-approve"},
		{name: "admin payments transaction decline exact", method: "POST", path: "/admin/payments/transactions/tx-123/decline", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-decline"},
		{name: "admin payments transaction status exact", method: "POST", path: "/admin/payments/transactions/tx-123/status", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-status"},
		{name: "admin payments transaction refund exact", method: "POST", path: "/admin/payments/transactions/tx-123/refund", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-refund"},
		{name: "admin payments transaction reverse exact", method: "POST", path: "/admin/payments/transactions/tx-123/reverse", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-reverse"},
		{name: "admin payments transaction chargeback exact", method: "POST", path: "/admin/payments/transactions/tx-123/chargeback", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-chargeback"},
		{name: "admin payments transaction retry exact", method: "POST", path: "/admin/payments/transactions/tx-123/retry", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-retry"},
		{name: "admin payments transaction settle exact", method: "POST", path: "/admin/payments/transactions/tx-123/settle", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-payments-transaction-settle"},
		{name: "prediction admin prefix", method: "GET", path: "/admin/prediction/orders", wantFound: true, wantService: "phoenix-prediction", wantRouteName: "prediction-admin"},
		{name: "admin audit exact", method: "GET", path: "/admin/audit-logs", wantFound: true, wantService: "phoenix-audit", wantRouteName: "admin-audit-logs"},
		{name: "admin audit export exact", method: "GET", path: "/admin/audit-logs/export", wantFound: true, wantService: "phoenix-audit", wantRouteName: "admin-audit-logs-export"},
		{name: "admin terms current exact", method: "GET", path: "/admin/terms/current", wantFound: true, wantService: "phoenix-config", wantRouteName: "admin-terms-current"},
		{name: "admin upload terms exact", method: "POST", path: "/admin/upload-terms", wantFound: true, wantService: "phoenix-config", wantRouteName: "admin-upload-terms"},
		{name: "admin user notes exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/notes", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-user-notes-get"},
		{name: "admin user timeline exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/timeline", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-user-timeline-get"},
		{name: "admin user timeline export exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/timeline/export", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-user-timeline-export"},
		{name: "admin user lifecycle exact", method: "POST", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/lifecycle/suspend", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-user-lifecycle-action"},
		{name: "admin user session history exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/session-history", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-user-session-history"},
		{name: "admin user bets exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/bets", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "admin-user-bets"},
		{name: "admin user logs exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/logs", wantFound: true, wantService: "phoenix-audit", wantRouteName: "admin-user-logs"},
		{name: "admin punter notes exact", method: "POST", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/notes", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-punter-notes-post"},
		{name: "admin punter timeline exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/timeline", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-punter-timeline-get"},
		{name: "admin punter timeline export exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/timeline/export", wantFound: true, wantService: "phoenix-support-notes", wantRouteName: "admin-punter-timeline-export"},
		{name: "admin punter lifecycle exact", method: "POST", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/lifecycle/logout", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-punter-lifecycle-action"},
		{name: "admin user deposit limit update exact", method: "PUT", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/limits/deposit", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-deposit-limit-update"},
		{name: "admin punter deposit limit update exact", method: "PUT", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/limits/deposit", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-deposit-limit-update"},
		{name: "admin user stake limit update exact", method: "PUT", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/limits/stake", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-stake-limit-update"},
		{name: "admin punter stake limit update exact", method: "PUT", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/limits/stake", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-stake-limit-update"},
		{name: "admin user session limit update exact", method: "PUT", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/limits/session", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-session-limit-update"},
		{name: "admin punter session limit update exact", method: "PUT", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/limits/session", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-session-limit-update"},
		{name: "admin user cool off lifecycle exact", method: "PUT", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/lifecycle/cool-off", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-cool-off-lifecycle"},
		{name: "admin punter cool off lifecycle exact", method: "PUT", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/lifecycle/cool-off", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-cool-off-lifecycle"},
		{name: "admin punter session history exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/session-history", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-punter-session-history"},
		{name: "admin bet cancel exact", method: "POST", path: "/admin/bets/bet_123/cancel", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "admin-bet-cancel"},
		{name: "admin bet lifecycle exact", method: "POST", path: "/admin/bets/bet_123/lifecycle/cancel", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "admin-bet-lifecycle-action"},
		{name: "admin punter bets exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/bets", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "admin-punter-bets"},
		{name: "admin punter logs exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/logs", wantFound: true, wantService: "phoenix-audit", wantRouteName: "admin-punter-logs"},
		{name: "admin user transactions exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/transactions", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-user-transactions"},
		{name: "admin punter transactions exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/transactions", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-punter-transactions"},
		{name: "admin user limits history exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/limits-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-limits-history"},
		{name: "admin punter limits history exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/limits-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-limits-history"},
		{name: "admin user cool offs history exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/cool-offs-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-user-cool-offs-history"},
		{name: "admin punter cool offs history exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/cool-offs-history", wantFound: true, wantService: "phoenix-compliance", wantRouteName: "admin-punter-cool-offs-history"},
		{name: "admin user financial summary exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/financial-summary", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-user-financial-summary"},
		{name: "admin punter financial summary exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/financial-summary", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-punter-financial-summary"},
		{name: "admin user funds credit exact", method: "POST", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/funds/credit", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-user-funds-credit"},
		{name: "admin punter funds credit exact", method: "POST", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/funds/credit", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-punter-funds-credit"},
		{name: "admin user funds debit exact", method: "POST", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/funds/debit", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-user-funds-debit"},
		{name: "admin punter funds debit exact", method: "POST", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/funds/debit", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-punter-funds-debit"},
		{name: "admin user transactions export exact", method: "GET", path: "/admin/users/550e8400-e29b-41d4-a716-446655440000/transactions/export", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-user-transactions-export"},
		{name: "admin punter transactions export exact", method: "GET", path: "/admin/punters/550e8400-e29b-41d4-a716-446655440000/transactions/export", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-punter-transactions-export"},
		{name: "admin punter exclusions export exact", method: "POST", path: "/admin/punters/exclusions/export", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-punter-exclusions-export"},
		{name: "admin daily reports exact", method: "POST", path: "/admin/reports/daily", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-daily-reports"},
		{name: "admin repeat daily reports exact", method: "GET", path: "/admin/reports/daily/repeat", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-repeat-daily-reports"},
		{name: "admin promo usage exact", method: "GET", path: "/admin/promotions/usage", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-promo-usage"},
		{name: "admin wallet correction tasks exact", method: "GET", path: "/admin/wallet/corrections/tasks", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-wallet-correction-tasks"},
		{name: "admin risk player scores exact", method: "GET", path: "/admin/risk/player-scores", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-risk-player-scores"},
		{name: "admin risk segments exact", method: "GET", path: "/admin/risk/segments", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-risk-segments"},
		{name: "admin feed health exact", method: "GET", path: "/admin/feed-health", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-feed-health"},
		{name: "admin provider cancel exact", method: "POST", path: "/admin/provider/cancel", wantFound: true, wantService: "phoenix-wallet", wantRouteName: "admin-provider-cancel"},
		{name: "admin provider acknowledgements get exact", method: "GET", path: "/admin/provider/acknowledgements", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-provider-acknowledgements-get"},
		{name: "admin provider acknowledgements post exact", method: "POST", path: "/admin/provider/acknowledgements", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-provider-acknowledgements-post"},
		{name: "admin provider acknowledgement sla get exact", method: "GET", path: "/admin/provider/acknowledgement-sla", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-provider-acknowledgement-sla-get"},
		{name: "admin provider acknowledgement sla post exact", method: "POST", path: "/admin/provider/acknowledgement-sla", wantFound: true, wantService: "phoenix-analytics", wantRouteName: "admin-provider-acknowledgement-sla-post"},
		{name: "admin user verification sessions exact", method: "GET", path: "/admin/users/usr_123/verification-sessions", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-user-verification-sessions"},
		{name: "admin verification session detail exact", method: "GET", path: "/admin/users/verification-sessions/sess_123", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-verification-session-detail"},
		{name: "admin idcomply verification session by reference exact", method: "GET", path: "/admin/providers/idcomply/verification-sessions/by-reference/idcomply:kba:sess_123", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-session-by-reference"},
		{name: "admin idcomply verification session by case exact", method: "GET", path: "/admin/providers/idcomply/verification-sessions/by-case/case_123", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-session-by-case"},
		{name: "admin idcomply review queue export exact", method: "GET", path: "/admin/providers/idcomply/verification-sessions/review-queue/export", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-review-queue-export"},
		{name: "admin idcomply review queue exact", method: "GET", path: "/admin/providers/idcomply/verification-sessions/review-queue", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-review-queue"},
		{name: "admin verification session events exact", method: "GET", path: "/admin/users/verification-sessions/sess_123/events", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-verification-session-events"},
		{name: "admin verification session decision exact", method: "POST", path: "/admin/users/verification-sessions/sess_123/decision", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-verification-session-decision"},
		{name: "admin idcomply verification decision exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/sess_123/decision", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-verification-decision"},
		{name: "admin idcomply verification decision by reference exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/by-reference/idcomply:kba:sess_123/decision", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-verification-decision-by-reference"},
		{name: "admin idcomply verification decision by case exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/by-case/case_123/decision", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-verification-decision-by-case"},
		{name: "admin idcomply verification session status exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/sess_123/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-session-status"},
		{name: "admin idcomply verification session status by case exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/by-case/case_123/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-session-status-by-case"},
		{name: "admin idcomply verification session status by reference exact", method: "POST", path: "/admin/providers/idcomply/verification-sessions/status", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-idcomply-session-status-by-reference"},
		{name: "admin users prefix", method: "GET", path: "/admin/users", wantFound: true, wantService: "phoenix-user", wantRouteName: "admin-users"},
		{name: "admin bets prefix", method: "GET", path: "/admin/bets/bet_123", wantFound: true, wantService: "phoenix-betting-engine", wantRouteName: "admin-bets"},
		{name: "admin markets prefix", method: "GET", path: "/admin/markets/mrk_123", wantFound: true, wantService: "phoenix-market-engine", wantRouteName: "admin-markets"},
		{name: "admin fixtures prefix", method: "GET", path: "/admin/fixtures/evt_123", wantFound: true, wantService: "phoenix-events", wantRouteName: "admin-fixtures"},
		{name: "admin tournaments prefix", method: "GET", path: "/admin/tournaments", wantFound: true, wantService: "phoenix-events", wantRouteName: "admin-tournaments"},
		{name: "user achievements template", method: "GET", path: "/api/v1/users/usr_123/achievements", wantFound: true, wantService: "phoenix-retention", wantRouteName: "user-achievements"},
		{name: "user loyalty template", method: "GET", path: "/api/v1/users/usr_123/loyalty-points", wantFound: true, wantService: "phoenix-retention", wantRouteName: "user-loyalty-points"},
		{name: "user loyalty redeem template", method: "POST", path: "/api/v1/users/usr_123/loyalty-points/redeem", wantFound: true, wantService: "phoenix-retention", wantRouteName: "user-loyalty-redeem"},
		{name: "freebets exact", method: "GET", path: "/api/v1/freebets", wantFound: true, wantService: "phoenix-retention", wantRouteName: "freebets"},
		{name: "freebet detail template", method: "GET", path: "/api/v1/freebets/fb:local:000001", wantFound: true, wantService: "phoenix-retention", wantRouteName: "freebet-detail"},
		{name: "odds boosts exact", method: "GET", path: "/api/v1/odds-boosts", wantFound: true, wantService: "phoenix-retention", wantRouteName: "odds-boosts"},
		{name: "odds boost detail template", method: "GET", path: "/api/v1/odds-boosts/ob:local:000001", wantFound: true, wantService: "phoenix-retention", wantRouteName: "odds-boost-detail"},
		{name: "odds boost accept template", method: "POST", path: "/api/v1/odds-boosts/ob:local:000001/accept", wantFound: true, wantService: "phoenix-retention", wantRouteName: "odds-boost-accept"},
		{name: "unknown path", method: "GET", path: "/api/v1/unknown", wantFound: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			route, found, err := repo.Match(context.Background(), tt.method, tt.path)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if found != tt.wantFound {
				t.Fatalf("found = %v, want %v", found, tt.wantFound)
			}
			if !tt.wantFound {
				return
			}
			if route.TargetService != tt.wantService {
				t.Fatalf("service = %s, want %s", route.TargetService, tt.wantService)
			}
			if route.Name != tt.wantRouteName {
				t.Fatalf("route name = %s, want %s", route.Name, tt.wantRouteName)
			}
		})
	}
}
