
apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: lenses-license
data:
 license.json: {{ .Values.secrets.license | quote }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: lenses-database
data:
 LENSES_STORAGE_POSTGRES_USERNAME: {{ .Values.secrets.database.username | quote }}
 LENSES_STORAGE_POSTGRES_PASSWORD: {{ .Values.secrets.database.password | quote }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: lenses-master-user
data:
 LENSES_SECURITY_USER: {{ .Values.secrets.login.username | quote }}
 LENSES_SECURITY_PASSWORD: {{ .Values.secrets.login.password | quote }}
