# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 23:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('profiles', '0015_customuser_is_temporary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalusermappingmodel',
            unique_together=set([('company', 'external_user_id')]),
        ),
        migrations.AlterIndexTogether(
            name='externalusermappingmodel',
            index_together=set([('company', 'external_user_id', 'user')]),
        ),
    ]
