# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 20:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc_temp_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusermappingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_user_mapping_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
