# Generated by Django 2.1.7 on 2019-03-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_temp_user', '0002_auto_20180204_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusermappingmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Company'),
        ),
        migrations.AlterField(
            model_name='externalusermappingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_user_mapping_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
