rules = [
  OrganizeImports
]

OrganizeImports.expandRelative = true
OrganizeImports.removeUnused = false
OrganizeImports.groupedImports = Explode
OrganizeImports.groups = [
  "java.",
  "scala.",
  "*",
  "stella.",
  "stella.leaderboard."
]
